### ISSUE TITLE
Dismounting your mount when going through door doesnt work

### ISSUE THREAD

**Issue by manuelinobdk** [GameFreedomGG/Maelstrom#122]
![Desktop Screenshot 2021 04 13 - 11 47 23 58](https://user-images.githubusercontent.com/82398722/114533383-21009300-9c4e-11eb-8988-b228b8ad8f8c.png)
**Description:** normally when u go through a door you automatically dismount if u fit, but it doesnt work. You just walk into a invisible wall

**How to reproduce:** Mount up and go through a fitable door

**How it should work:** if u fit through you should dismount 
![Desktop Screenshot 2021 04 13 - 11 39 02 10](https://user-images.githubusercontent.com/82398722/114533164-e860b980-9c4d-11eb-89d4-1dd05bf9ed30.png)

**Comment by xcenon92** [comment]
probably the hitbox when you mount up is bigger you can see that when you walk into the water your always deeper and you´ll lose breath
