### ISSUE TITLE
[Quest] Burn, Baby, Burn! ID: 25622 Broken

### ISSUE THREAD

**Issue by ElectrickFun** [GameFreedomGG/Maelstrom#133]
**Description:** 
https://www.wowhead.com/quest=25622/burn-baby-burn
Destroying some of the quest objectives (Warsgong Stockpile) doesnt give credit.

**How to reproduce:** 

**How it should work:** 
Destroying them should count towards the quest objective

**Comment by HerodDev** [comment]
Crate neet to be in line of sight to get credit, move just a little bit and it will work.
TODO: fix los checking

**Comment by UltraNix** [comment]
Works okay.
