### ISSUE TITLE
[Quest] Commander the Balloon! Stonetalon Mountain

### ISSUE THREAD

**Issue by xcenon92** [GameFreedomGG/Maelstrom#164]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Baloon is completly missing,  its a main quest and you cant continue without it 

**How to reproduce:**
accept the quest and the search for the non existing balloon

**How it should work:**
https://www.youtube.com/watch?v=Eonb7GMPqjo

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=25652/commandeer-that-balloon
