### ISSUE TITLE
[Quest] [Combat Training]

### ISSUE THREAD

**Issue by Allation2** [GameFreedomGG/Maelstrom#166]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
You cant complete the quest because you cant  recruit 5 soldiers for the fight.
There are no troops spawned so you cant use the valkyrs ability to recruit them.

**How to reproduce:**
Accept quest.

**How it should work:**
You have to recruit forsaken troops with the valkyr.

https://youtu.be/yrmBJVWX6PE?t=98

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=26938/combat-training
