### ISSUE TITLE
Enemy NPC totem friendly 

### ISSUE THREAD

**Issue by mafa2** [GameFreedomGG/Maelstrom#169]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Currently the enemy NPC Kurzen Witch Doctor casts a Healing Stream Totem when initiating combat. This totem is flagged as friendly and thus cannot be attacked. NPC is located in Northern STV - The Stockpile.

**How to reproduce:**
Initiate combat with the NPC

**How it should work:**
Totem should be flagged as hostile like the NPC is.

**Comment by HerodDev** [comment]
https://www.wowhead.com/npc=942/kurzen-witch-doctor

**Comment by UltraNix** [comment]
Fixed.
