### ISSUE TITLE
We're Under Attack Quest 27857

### ISSUE THREAD

**Issue by PendingtonFlex** [GameFreedomGG/Maelstrom#181]
https://www.youtube.com/watch?v=U5IjusXiA5c

**Description:**
Currently does not phase you to this combat area, just keeps you in the base world.

**How to reproduce:**
Accept quest and cannot complete due to no mobs.

**How it should work:**
See Video for reference.

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=27857/were-under-attack

**Comment by HerodDev** [comment]
https://github.com/SallyWhitemane/Herod/issues/131

**Comment by WhitemaneChronus** [comment]
The quest still has issues. it should phase you to the following picture but it doesnt.
![image](https://github.com/user-attachments/assets/b6027a17-2aea-44fa-bf6d-c0907046910e)

how it currently is:
![Screenshot 2024-08-21 124947](https://github.com/user-attachments/assets/04238d4d-a677-4a9a-a942-3a19141b3966)
