### ISSUE TITLE
[Quest] Grand Theft Palomino

### ISSUE THREAD

**Issue by llogan1233** [GameFreedomGG/Maelstrom#187]
https://www.wowhead.com/quest=12680/grand-theft-palomino

**Description:**
You cant mount any of the horses for the quest, instead you only get credit for the quest when you kill one of the horses.

**How to reproduce:**
Go to the horse stables in the DK starting zone and try to mount one of the horses

**How it should work:**
https://www.youtube.com/watch?v=xq23deehfKU

**Comment by cloud1121** [comment]
Updating: Still not working, cannot get DK mount in quest chain 
![image](https://user-images.githubusercontent.com/77916637/120371850-42cfdb00-c2cb-11eb-90c5-238362c0b2d8.png)

**Comment by cloud1121** [comment]
Update: Still not working in DK intro Chain

**Comment by cloud1121** [comment]
Another update: Killing a Non Aggressive horse in area completes quest
@HerodDev

**Comment by Afgann** [comment]
fixed
