### ISSUE TITLE
[Scripting] Andorhal NPCs dont behave as they should.

### ISSUE THREAD

**Issue by ElectrickFun** [GameFreedomGG/Maelstrom#188]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
All the NPCs at Andorhal arent fighting the mobs as they should, some seem like are just going in cricles or cant path find

**How to reproduce:**

**How it should work:** I linked a video showing that

**Wowhead links:** https://www.youtube.com/watch?v=YJZv5xeQCIk

**Comment by UltraNix** [comment]
Works okay.
