### ISSUE TITLE
[QUEST] More Skull For Brew

### ISSUE THREAD

**Issue by Zarke1408** [GameFreedomGG/Maelstrom#192]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Doesn't work
We should be able to validate the quest, there it is not possible nothing happens

![WoWScrnShot_041421_233626](https://user-images.githubusercontent.com/82468604/114783839-979aaf00-9d7a-11eb-8119-75b2a9a4f9ec.jpg)

**How to reproduce:**
Add 20x Crusader skull and try to make the quest

**How it should work:**

**Wowhead links:**
https://www.wowhead.com/quest=12718/more-skulls-for-brew
https://www.wowhead.com/item=39328/crusader-skull

**Comment by UltraNix** [comment]
Works okay.
