### ISSUE TITLE
[Profession] Archeology

### ISSUE THREAD

**Issue by Zarke1408** [GameFreedomGG/Maelstrom#198]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
When we finish a excavation site, it remains marked on our map but we can no longer excavate.

![WoWScrnShot_041521_015101](https://user-images.githubusercontent.com/82468604/114794820-7e4f2e00-9d8d-11eb-9cb1-ced51941b1fa.jpg)
![WoWScrnShot_041521_015133](https://user-images.githubusercontent.com/82468604/114794830-80b18800-9d8d-11eb-80b4-ce5417bc6dac.jpg)
![WoWScrnShot_041521_015138](https://user-images.githubusercontent.com/82468604/114794835-8313e200-9d8d-11eb-9014-ed058bc468a1.jpg)

**How to reproduce:**
Learn the profession and move to an excavation site, do three excavations then see

**How it should work:**
Once completed the excavation site should disappear from our map and then another should appear elsewhere in its place.
This should remove the dig site from our map as soon as we finish it.

**Wowhead links:**
https://www.wowhead.com/archaeology

**Comment by Zarke1408** [comment]
Edit: Some excavation sites will not disappear, but others will work

**Comment by Zarke1408** [comment]
When we disconnect then reconnect it resolves the problem

**Comment by Zarke1408** [comment]
Edit: As soon as we teleport somewhere and come back to the continent, the excavation sites bug again

**Comment by UltraNix** [comment]
Cannot reproduce it.
