### ISSUE TITLE
[QUEST] Jin'Zil's Blessing - Not all Marauders accept buff

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#199]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Jin'Zil's Blessing, the item Jin'Zil's Voodoo Stick is used to apply a buff to a number of Krom'gar Marauders. For some unknown reason, not all Marauders are accepting the buff, but some do.

**How to reproduce:**

During the quest, approach a Krom'gar Marauder, target them, and use Jin'Zil's Voodoo Stick from the quest sidebar:
![jzb0414](https://user-images.githubusercontent.com/82483575/114802147-cd339e00-9d62-11eb-9252-d2c35b8c9f40.png)

Once the channel completes, the buff should be applied. However, on roughly half of the Marauders I used the item on, no buff or credit was given:
![jzb20414](https://user-images.githubusercontent.com/82483575/114802211-ea686c80-9d62-11eb-9476-5d69d264a851.png)

**How it should work:**
In all instances where a Krom'gar Marauder is not already buffed, they should receive a buff from the item channel, and should apply credit towards the quest, as shown below:
![jzb30414](https://user-images.githubusercontent.com/82483575/114802361-31eef880-9d63-11eb-851b-fb5664b11fd0.png)

**Wowhead links:**
https://www.wowhead.com/quest=26067/jinzils-blessing

**Comment by UltraNix** [comment]
It's a single target item, not AoE.
