### ISSUE TITLE
[QUEST] Reinforcements - Quest Qualifications out of order

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#200]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest "Reinforcements..." should become available to pick up simultaneously with the quest Da Voodoo: Resonite Crystal, as noted in the wowhead links. In game, the quest "Reinforcements..." only became available after completing Jin'Zil's Blessing.

**How to reproduce:**
Quest to the point of Da Voodoo: Resonite Crystal. Confirm if the quest "Reinforcements..." is available from Subjugator Devo. If not, complete Da Voodoo: Resonite Crystal and the follow-up quest Jin'Zil's Blessing. Confirm if "Reinforcements..." is now available from Subjugator Devo.

**How it should work:**
"Reinforcements..." should be available simultaneously with Da Voodoo: Resonite Crystal, as they both take players to the same location, as noted in the wowhead links.

**Wowhead links:**
https://www.wowhead.com/quest=26066/reinforcements
https://www.wowhead.com/quest=26062/da-voodoo-resonite-crystal
https://www.wowhead.com/quest=26067/jinzils-blessing

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Jin%27Zil%27s_Blessing
Works okay.
