### ISSUE TITLE
Lashtail Hatchling Continuously Eating Corpse

### ISSUE THREAD

**Issue by Gaugeoak** [GameFreedomGG/Maelstrom#208]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Lashtail Hatchling for quest in STV eats the first corpse I kill and frantically goes back to it and keeps eating over and over.  Gives quest credit really fast!

**How to reproduce:**
Open hatchling from inventory bag, kill a murloc and hatchling goes over to the murloc corpse

**How it should work:**
Probably should only get quest credit for a few bites

**Wowhead links:**
![WoWScrnShot_041321_071310](https://user-images.githubusercontent.com/82425397/114890415-9c8a4d80-9dd0-11eb-931c-bc4380b00cc2.jpg)

**Comment by HerodDev** [comment]
@Gaugeoak Add links to wowhead

**Comment by HerodDev1** [comment]
https://www.wowhead.com/quest=26321/i-think-shes-hungry

**Comment by UltraNix** [comment]
This is how this quest works.
