### ISSUE TITLE
Blubbergut Stuck in Rock Wall

### ISSUE THREAD

**Issue by Gaugeoak** [GameFreedomGG/Maelstrom#209]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Blubbergut stuck in rock wall underwater

**How to reproduce:**
When trying to hit Blubbergut, I couldn't get a white hit or any skill hit, including aoe to hit him.  Combat wouldn't engage either untilI hit him at ranged with my heroic throw skill.

**How it should work:**
Should be swimming around outside Shadowprey Village and engage in normal combat

**Wowhead links:**

![WoWScrnShot_041421_071549](https://user-images.githubusercontent.com/82425397/114891049-2c2ffc00-9dd1-11eb-89a2-2669943a37c2.jpg)

**Comment by HerodDev** [comment]
@Gaugeoak Add links to wowhead
