### ISSUE TITLE
LOS Issues w/ Warrior Charge Skill

### ISSUE THREAD

**Issue by Gaugeoak** [GameFreedomGG/Maelstrom#210]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Lots of LOS/pathing issues throughout Classic Zones when trying to charge an enemy - especially underwater.  Receive "facing wrong way" and "no path available" errors

**How to reproduce:**
Use charge skill on enemy within range

**How it should work:**
Should charge and path towards enemy when in range and using charge skill

**Wowhead links:**

![WoWScrnShot_041421_090641](https://user-images.githubusercontent.com/82425397/114891434-803ae080-9dd1-11eb-9f04-dec475d75fa7.jpg)

**Comment by UltraNix** [comment]
Fixed.
