### ISSUE TITLE
fishing animation bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#213]
**Description:**
when using the fishing spell the cast bar for the fishing
channeling spell sometimes disapears and the fishing animation is cancelled but
the fishing bobber remains and wil still make the animation of getting a catch
without the fishing rod being cast after a certain amount of time as usual with
the fishing spell. The fishing spell is also able to be cast again but the
previous bobber that had its casting annimation cancled is unlootable.

**How to reproduce:**
use the fishing spell untill the spell cancels and the fishing bobber remains
and use the fishing spell again

**How it should work:**
when the fishing spell is used the whole animation should stay until the spell
is canceled by a player, the player loots the bobber, or the spell channel ends

**Wowhead links:**
https://www.wowhead.com/spell=7731/fishing

**Comment by UltraNix** [comment]
Cannot reproduce it.
