### ISSUE TITLE
herb and ore node harvest bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#216]
**Description:**
sometimes when gathering an herb or an ore node, the harvest animation shows but
with out the cast bar and the animation continues. relogging can fix this issue

**How to reproduce:**
harvest an herb or ore node, to fix the issue reload the ui and harvest the node
again.

**How it should work:**
ore and herb nodes should be able to be harvested with the harvest cast bar
and harvest animation showing and the node should be able to be harvested after
a certain amount of time.

**Wowhead links:**

**Comment by UltraNix** [comment]
Cannot reproduce it.
