### ISSUE TITLE
herb and ore node spawn and frequency amount

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#217]
**Description:**
herbs respawn very quickly and there seems to be many herbs
available, Herbs sometimes spawn twice close to each other.

**How to reproduce:**
find herb or ore nodes and harvest them.

**How it should work:**
ore and herb nodes should spawn less often and should respawn less frequently, i
do not know the specific frequency for the respawn rate or the available node
amount for herbs and ore.

**Wowhead links:**

**Comment by UltraNix** [comment]
No links/ no coords.
