### ISSUE TITLE
heroes call westfall bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#219]
**Description:**
the quest heroes call, westfall can be obtained twice
(and can be had two at a time) by accepting the heroes call quest from Marshal
Dughan at goldshire in Elwyn forest and from the heroes call board in stormwind
stormwind.

**How to reproduce:**
accept the heroes call quest from Marshal Dughan and from the heroes call board
in stormwind.

**How it should work:**
The quest should only be ontained once from where ever it is available.

**Wowhead links:**
https://www.wowhead.com/quest=28562/heros-call-westfall

**Comment by UltraNix** [comment]
Fixed.
