### ISSUE TITLE
Tednug

### ISSUE THREAD

**Issue by PendingtonFlex** [GameFreedomGG/Maelstrom#22]
**Description:**
NPC Tednug, and his cat pathing are broken 52.32

**How to reproduce:**

**How it should work:**
I believe his cat and him walk to Razor Hill, and to the end of the ravine.

**Comment by HerodDev** [comment]
@PendingtonFlex add wowhead links

**Comment by PendingtonFlex** [comment]
https://www.wowhead.com/npc=40970/tednug
https://www.wowhead.com/npc=40971/scratchfever
can't find any documentation for his pathing, but the wowhead link gives dots on a map.
