### ISSUE TITLE
loot option still showing after npc is looted

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#221]
**Description:**
Npc's that are killed and have a loot option sometimes still have a option to
loot after the npc was already looted. Only the loot icon shows when
a player hovers their cursor over a lootable corpse. Players can still click the
npc to loot them and the loot popup does not apear when clicking the npc, the
looting animation also cancels after clicking the lootable npc.

**How to reproduce:**
Kill a lootable npc and loot that npc then attempt to loot the npc again.

**How it should work:**
when a lootable npc is killed and looted the npc should no longer have a loot
option.

**Wowhead links:**

**Comment by UltraNix** [comment]
No links/ no coords.
