### ISSUE TITLE
Npc run speed not fast enough

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#223]
**Description:**
hostile and neutral npc's in Northshire seem to be moving slowly without
movement impairing effects applied to the npc's. Normally players are able to run
away from npc's and the npc's are still able to hit you as long as your speed
is't boosted. I do not know the exact speed but i can tell the npc's move slower
than usual.

**How to reproduce:**
attack the neutral or hostile npc's in Elwyn forest in Northsire such as the
goblin assassins, blackrock spys, or the blackrock invaders in the Northsire
vineyard.

**How it should work:**
when you attack the npc's they are supposed to be able to hit you as you run away
from them and they are supposed to move quicker in general, i remember npc's
still being able to hit players when in combat with them while a player runs
away from the npc.

**Wowhead links:**
https://www.wowhead.com/npc=50039/goblin-assassin

**Comment by UltraNix** [comment]
Mostly fixed.
