### ISSUE TITLE
Npc, Lien farner bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#224]
**Description:**
when clicking the option to talk about
gathering profesions with the npc Lien Farner in Goldshire, the dialogue closes
instead of showing list of gather profesions.

**How to reproduce:**
talk to the npc Lien Farner in Elwyn Forest, Goldshire and click the dialogue
for gathering profesions

**How it should work:**
When the dialogue is clicked it should show a list of gathering professions that
players are able to learn by cliking on them and learning the selected profession
in a profession trainer menu.

**Wowhead links:**
https://www.wowhead.com/npc=47384/lien-farner#teaches-recipe

**Comment by UltraNix** [comment]
Everything works okay.
