### ISSUE TITLE
To Legion Hold

### ISSUE THREAD

**Issue by PendingtonFlex** [GameFreedomGG/Maelstrom#226]
https://www.youtube.com/watch?v=3Xz7v8CURRA

**Description:**
Currently using the box, it does transform you into a box for 1 minute, but doesn't spawn the mob or text.

**How to reproduce:**
Grab quest, go to location.

**How it should work:**
Video for reference.

**Wowhead links:**
https://www.wowhead.com/quest=10596/to-legion-hold HORDE
https://www.wowhead.com/quest=10563/to-legion-hold ALLIANCE

**Comment by UltraNix** [comment]
Works okay.
