### ISSUE TITLE
quest text in quest log not completely showing

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#227]
**Description:**
quest text sometimes doesn't completely show in quest log for any quest in the
log, the text fades out at a certain point in the quest information in the quest
log, reloading the ui fixes the issue.

**How to reproduce:**
open the quest log ingame and view the quest information of any quest, to fix the
issue reload the game ui.

**How it should work:**
quest text in the quest log should completely show without reloading the ui

**Wowhead links:**

**Comment by UltraNix** [comment]
No links/ no coords.
