### ISSUE TITLE
Redridge dire condor flying animation not showing

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#228]
**Description:**
Dire Condors in Red ridge mountain do not have flying animation while staying
still in the air or moving.

**How to reproduce:**
find and observe a dire condor in red ridge mountain.

**How it should work:**
Dire condors in redridge mountain should have an animation of flying while
moving or staying still in the air.

**Wowhead links:**
https://www.wowhead.com/npc=428/dire-condor

**Comment by UltraNix** [comment]
Works okay.
