### ISSUE TITLE
redridge mystic npc bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#229]
**Description:**
Red Ridge Mystic gnolls in Redridge Mountain are not effected by slow
effects.

**How to reproduce:**
attack a redridge mystic and attempt to slow the npc with a movement impairing
effect.

**How it should work:**
The redridge mystic npc should be able to be slowed by movement impairing
effects

**Wowhead links:**
https://www.wowhead.com/npc=430/redridge-mystic

**Comment by UltraNix** [comment]
Works okay.
