### ISSUE TITLE
unusual npc despawn rate

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#232]
**Description:**
npc corpses seem to despawn quickly, the corpses despawn after approximately
59 seconds. This may be a normal despawn rate but it looked unusual and this was
not tested while there was loot available to pick up from the npc.

**How to reproduce:**
kill an npc and wait till corpse despawns

**How it should work:**
after an npc is killed the corpse should stay for a longer time and then despawn.

**Wowhead links:**

**Comment by UltraNix** [comment]
No links.
