### ISSUE TITLE
Missing anvil and forge in Nogg's Machine Shop (engineering trainer in Orgrimmar)

### ISSUE THREAD

**Issue by IamNylea** [GameFreedomGG/Maelstrom#234]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
There is no anvil and forge near engineering trainer in Orgrimmar.

**How to reproduce:**
This is how it looks on Herod 
![image](https://user-images.githubusercontent.com/82405893/114931695-d9892b00-9e36-11eb-9535-95875b2e3d61.png)

**How it should work:**
It should looks like here
![image](https://user-images.githubusercontent.com/82405893/114931778-f887bd00-9e36-11eb-8346-e6d020ab0c9e.png)

**Comment by UltraNix** [comment]
It's there.
