### ISSUE TITLE
 Lifting the Veil quest is missing 

### ISSUE THREAD

**Issue by ElectrickFun** [GameFreedomGG/Maelstrom#236]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:** A quest in that chain is missing. 

**How to reproduce:**

**How it should work:**

**Wowhead links:**https://www.wowhead.com/quest=27770/lifting-the-veil

**Comment by UltraNix** [comment]
Everything works okay.
