### ISSUE TITLE
random dialog errrors i gilneas

### ISSUE THREAD

**Issue by Volkyte** [GameFreedomGG/Maelstrom#239]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
as per screenshot

https://imgur.com/Npt6S7w
**How to reproduce:**

just go in gilneas worgen starting quests
**How it should work:**
ther should be no <error> message in chat

**Wowhead links:**

----

**Comment by UltraNix** [comment]
Fixed.
