### ISSUE TITLE
Duskhaven guards and forsaken not doing anything

### ISSUE THREAD

**Issue by Volkyte** [GameFreedomGG/Maelstrom#241]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
guards just look each other into their eyes doing nothing

**How to reproduce:**
---

**How it should work:**
Duskhaven guards near shore of forsaken ships should attack each other

**Wowhead links:**

**Comment by SallyWhitemane** [comment]
@Volkyte Add links please.

**Comment by UltraNix** [comment]
Fixed.
