### ISSUE TITLE
Blackrock tracker and Blackrock summoner bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#249]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
These npc's aren't wandering around in Renders cave, in Renders camp, in Redridge Mountain and should probably be wandering

**How to reproduce:**
Observe these npc's in Renders cave in Renders camp in Redridge Mountains.

**How it should work:**
The npc's should be wandering around and pausing there movement temporarily. (unless they are supposed to be standing still normally.

**Wowhead links:**
https://www.wowhead.com/redridge-mountains

**Comment by UltraNix** [comment]
No proofs.
