### ISSUE TITLE
Npc bug in Renders cave in Redridge Mountains

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#252]
**Description:**
The Blackrock scouts in Redridge Mountains in Renders cave (and outside Renders cave maybe) continue to be in the spyglass animation while moving toward the player that attacked them or they are attacking.

**How to reproduce:**
attack or be attacked by a blackrock scout in Renders cave and observe the npc's movement.

**How it should work:**
This spyglass animatio the npc is in should cancel when moving and should then be in a running or walking animation depending on the npc's movement speed.

**Wowhead links:**
https://www.wowhead.com/npc=4064/blackrock-scout

**Comment by UltraNix** [comment]
Works okay.
