### ISSUE TITLE
Npc bug in Renders cave (not attacking on there own when respawning)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#253]
**Description:**
Npc's in renders cave in Redridge mountains do not attack near by players when spawning

**How to reproduce:**
be in  Renders cave and kill some of the hostile npc's in the cave where the npc's can spawn and wait untill they respawn nearby.

**How it should work:**
Npc's In Renders cave should attack players immediately or in a short amount of time after respawning

**Wowhead links:**
https://www.wowhead.com/npc=4064/blackrock-scout

**Comment by UltraNix** [comment]
Works okay.
