### ISSUE TITLE
Abandon button in questlog

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#255]
**Description:**
The abandon button in the ingame questlog sometimes is not clickable (i have experienced this once so far) reloading the ui fixes this issue

**How to reproduce:**
Attempt to click the abandon button in the ingame questlog

**How it should work:**
the abandon button for a quest in the ingame questlog should always be clickable.

**Wowhead links:**

**Comment by UltraNix** [comment]
No links/no proofs.
