### ISSUE TITLE
Carried on the waves quest bug

### ISSUE THREAD

**Issue by GitGudNubHub** [GameFreedomGG/Maelstrom#257]
**Description:**
![WoWScrnShot_041621_233818](https://user-images.githubusercontent.com/58514021/115090403-10ce0980-9f15-11eb-9e11-0a14ec2da21d.jpg)

90% of the Bloodpetal seeds are on land.

**How to reproduce:**
Accept the quest.

**How it should work:**
The Bloodpetal seed should be only in the water. 

**Wowhead links:**
https://www.wowhead.com/quest=24686/carried-on-the-waves#videos:id=82948

**Comment by UltraNix** [comment]
No - they can be on the ground as well as you can see on other videos.
