### ISSUE TITLE
Bouquets of Death quest bug

### ISSUE THREAD

**Issue by GitGudNubHub** [GameFreedomGG/Maelstrom#261]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
In this quest you should kill 6pack of  of Juvenile Bloodpetals, which is 36.
I killed around 25-30 and I realized that I only had slain 2 packs.
My guess that it only accepts 1 pack as a kill, if you kill those 6 together  in a really small time interval .

**How to reproduce:**
Go and kill the flowers in 3-4-5 at a time.

**How it should work:**
You should get 1 pack slain done, when you kill 6 of them.
https://www.youtube.com/watch?v=PcmfndKrhkg
**Wowhead links:**
https://www.wowhead.com/quest=24687/bouquets-of-death

**Comment by UltraNix** [comment]
Works okay to me. It's not about 6 mobs, but the pack around.
