### ISSUE TITLE
[QUEST] The Fight Continues ID: 26208 the scripted dialogue is broken

### ISSUE THREAD

**Issue by ElectrickFun** [GameFreedomGG/Maelstrom#264]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:** When mekkatorque talks to the hologram it only appears as <ERROR>

**How to reproduce:** Start the quest

**How it should work:** There should be a long story that he tells 

**Wowhead links:**https://www.wowhead.com/quest=26208/the-fight-continues

**Comment by UltraNix** [comment]
Works okay.
