### ISSUE TITLE
Class trainers despawning randomly in duskhaven

### ISSUE THREAD

**Issue by Volkyte** [GameFreedomGG/Maelstrom#266]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
sometimes trainers are present, sometimes they disappearù
https://imgur.com/Ejsf5CL

**How to reproduce:**
---

**How it should work:**
there should be trainers in duskhaven for all classess

**Wowhead links:**
---

**Comment by UltraNix** [comment]
Looks okay. Visible after quest "Invasion"
