### ISSUE TITLE
Damsels Were Made to be Saved quest bug

### ISSUE THREAD

**Issue by GitGudNubHub** [GameFreedomGG/Maelstrom#267]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
https://www.wowhead.com/quest=24705/damsels-were-made-to-be-saved
Damsels Were Made to be Saved  it not scripted. The quest giver npc should talk to the woman npc I take him to and after a minute of conversation, I should get 1/3 of the quest completed . Yet  nothing happens when I take the quest giver npc to the quest npc.
![WoWScrnShot_041721_104906](https://user-images.githubusercontent.com/58514021/115107440-240bc400-9f6b-11eb-8117-0ee83c6f0b02.jpg)

**How to reproduce:**
Take the quest. Go to one of the npcs that have to be talked to.
Take the quest giver npc there. Nothing will happen.

**How it should work:**
The quest giver npc should talk with the quest npcs, as soon as they meet. And after talking I should get it completed.
https://www.youtube.com/watch?v=6Zd7g0kL3dQ
**Wowhead links:**

**Comment by UltraNix** [comment]
Works okay.
