### ISSUE TITLE
 The Secrets of Uldum quest EPIC BUG

### ISSUE THREAD

**Issue by GitGudNubHub** [GameFreedomGG/Maelstrom#271]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
https://www.youtube.com/watch?v=4vnCPEwg1lE
The quest is impossible to do, because as soon as you enter the cave you get teleported to your heartstone location.
**How to reproduce:**
Take the https://www.wowhead.com/quest=25566/the-secrets-of-uldum quest

**How it should work:**
You shouldnt get teleported away.

**Wowhead links:**
https://www.wowhead.com/quest=25566/the-secrets-of-uldum

**Comment by UltraNix** [comment]
Works okay to me.
