### ISSUE TITLE
[quest] rite of vision

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#278]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
pathing from the ghost wolf is not correct, you move out of balance and if you take dmg or aggro a mob, the spirit form cancles

**How to reproduce:**
do the quest

**How it should work:**
the ghost wolf should get you to the destination without any problems

**Wowhead links:**
https://www.wowhead.com/quest=20441/rite-of-vision

**Comment by UltraNix** [comment]
Works okay.
