### ISSUE TITLE
Dun Morogh Leveling Issues

### ISSUE THREAD

**Issue by alexspew** [GameFreedomGG/Maelstrom#28]
The Fight Continues : 26208
https://cdn.discordapp.com/attachments/830854551736680518/830933196232196106/unknown.png
----------------------------------------------------------------------------------------------------
CAN'T REPRODUCE:
Great Father Arctikus's is double attacking before I managed to hit. Swing timer bugged on elites?
https://prnt.sc/11a39ko

----------------------------------------------------------------------------------------------------

FIXED:
Npc Vallo Shinesteel is completely missing. Needed to buy better gear for Warrior since the drops are bugged on other mobs in the area.
https://cata-twinhead.twinstar.cz/?npc=42626

----------------------------------------------------------------------------------------------------

Down with Crushcog!  : 26364

Fight bugged. Razlo Crushcog gets insta one shot by High Tinker Mekkatorque or Orbital Targetting Device spells does way too much damage.

----------------------------------------------------------------------------------------------------

Beer Basted Boar Ribs : 384

Ragnar Thunderbrew <1267> is missing the quest.

----------------------------------------------------------------------------------------------------

Frostmane Seer : 41121
Bugged spawn at Dun Morogh: 48.19, 37.60
Mob also seems to ignore combat, unless ur in melee range it resets combat. After casting Lightning Bolt.

----------------------------------------------------------------------------------------------------

Wendigo : 40941
Bugged spawn in the air at Dun Morogh: 49.46, 52.05
Missing a few spawns inside the cave

Bugged Wild Boar spawn at ::
Dun Morogh: 49.13, 51.71 (Unable to interact with this mob)
Dun Morogh: 49.23, 50.69 (Unable to interact with this mob)

I believe these are suppose to be hidden from players as they are spawnpoints?

----------------------------------------------------------------------------------------------------

**Comment by HerodDev** [comment]
@alexspew  next time create only one issue for each problem
