### ISSUE TITLE
[Quest] [Horde] [StoneTalon Mountain Pre-quest] We're here to do one thing. Maybe two...

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#280]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Hop in the caravan to stonetalon. Get dropped off at the first hub.

**How to reproduce:**
Hop in and ride into nothingness.

**How it should work:**
Drops you off at The Fold. Instead of riding onwards

![image](https://user-images.githubusercontent.com/82404667/115121634-12024380-9fb4-11eb-847a-a1eb117eeb10.png)

**Wowhead links:**
https://www.wowhead.com/quest=25945/were-here-to-do-one-thing-maybe-two

**Comment by UltraNix** [comment]
Works okay.
