### ISSUE TITLE
[NPC] Corrupted Cliff Giant and Cliff Giant - Do not fight after initial spawn

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#281]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
This appears to be a minor issue, but it appears that when the Corrupted Cliff Giants and Cliff Giants at The Twin Colossals in Feralas initially spawn (server restart, I imagine), they do not fight each other:
![ccg0417](https://user-images.githubusercontent.com/82483575/115122643-9afe8800-9f7e-11eb-9d51-b4140ae169d1.png)

**How to reproduce:**
Navigate to The Twin Colossals in Feralas and observe the actions of the sets of NPCs near each other. Some may be fighting if the Corrupted Cliff Giant was killed.

**How it should work:**
When a Corrupted Cliff Giant is killed, when it respawns, the set of NPCs will engage in combat, shown below. This should happen with the initial spawn as well:
![ccg20417](https://user-images.githubusercontent.com/82483575/115122708-f761a780-9f7e-11eb-867e-43934e8b3181.png)

**Wowhead links:**
https://www.wowhead.com/npc=40972/corrupted-cliff-giant
https://www.wowhead.com/npc=39339/cliff-giant

**Comment by UltraNix** [comment]
Fixed.
