### ISSUE TITLE
[NPC] Theramore Deckhand

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#289]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
there are two Theramore Deckhand spawns in the ratched Inn

**How to reproduce:**

**How it should work:**
i dont believe they belong in there

**Wowhead links:**

**Comment by TheRealTangsten** [comment]
They do belong there, they are part of Club Foote quest. They are supposed to be friendly, and turn hostile once you clob Foote to take his ship schematics.
