### ISSUE TITLE
[GAMEOBJECT] Ravenwind sign not attached to signpost

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#290]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Ravenwind sign at The Forgotten Coast signpost is not attached to the signpost:
![rav0417](https://user-images.githubusercontent.com/82483575/115126613-ea9c7e00-9f95-11eb-86f4-6cae5a6fb4df.png)

**How to reproduce:**
Go to the signpost located next to Zorbin Fandazzle in The Forgotten Coast.

**How it should work:**
The sign should be attached to the signpost.

**Wowhead links:**
https://www.wowhead.com/npc=14637/zorbin-fandazzle

**Comment by SallyWhitemane** [comment]
Lack of sniff makes it not fixable for now.
