### ISSUE TITLE
[GAMEPLAY] Silence Abilities - Silenced Enemies do not run towards Melee range

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#296]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
I have been noticing this in several areas against many caster enemies. When interrupted or silenced, the caster NPC will not run towards melee range, and will instead stay still until the silence wears off, and will then start using spells.
https://user-images.githubusercontent.com/82483575/115128510-e2e3d600-9fa3-11eb-86ad-dab64966d81e.mp4

**How to reproduce:**
Engage combat at range with a spellcasting enemy. Silence them with a ranged silence ability, such as Avenger's Shield. Observe as the enemy does not approach you.

**How it should work:**
Once silenced, enemies should move towards melee range with the aggro target.

**Wowhead links:**
https://www.wowhead.com/spell=31935/avengers-shield

**Comment by UltraNix** [comment]
No links.
This mob works okay to me.
