### ISSUE TITLE
[NPC] D-1000 (HIllsbrad Foothills)

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#297]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
D-1000 doesn't attack if you have the high ground, he's just stuck. 

**How to reproduce:**
![image](https://user-images.githubusercontent.com/47416114/115128724-1b090a00-9fe0-11eb-8f9b-e86fe33d55d6.png)

**How it should work:**
he should either reset or walk around and up the stairs to the player

**Wowhead links:**

**Comment by UltraNix** [comment]
Fixed.
