### ISSUE TITLE
[QUEST] What I Do Best - Tarenar Sunstrike does not follow you as a companion

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#299]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
When the quest What I Do Best is accepted, Tarenar Sunstrike should join you as a companion but is not doing so.
![tar0417](https://user-images.githubusercontent.com/82483575/115131245-37934b00-9fbc-11eb-9f9c-d222ea247259.png)

**How to reproduce:**
Accept the quest What I Do Best. Observe that you have no companion.

**How it should work:**
Tarenar Sunstrike should join you as a companion.

**Wowhead links:**
https://www.wowhead.com/quest=27371/what-i-do-best

**Comment by Afgann** [comment]
fixed
