### ISSUE TITLE
[QUEST] Pamela's Doll - Mobs do not spawn

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#302]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Pamela's Doll, hostile mobs do not spawn when each doll piece is collected.

**How to reproduce:**
Obtain the quest Pamela's Doll and pick up each doll piece. Notice that hostile mobs do not spawn.

**How it should work:**
Hostile mobs should spawn when each piece is collected.

**Wowhead links:**
https://www.wowhead.com/quest=27384/pamelas-doll

**Comment by Afgann** [comment]
fixed
