### ISSUE TITLE
[CONTAINER] Hidden Stash - Only contains Mr. Grubbs

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#309]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
While questing in Eastern Plaguelands, you can select Fiona's Lucky Charm from Fiona's Caravan as a zone-wide buff. This buff adds a drop chance for a Hidden Stash from all creatures. Currently, these Hidden Stashes only contain the Mr. Grubbs pet, and nothing else.
![hid0417](https://user-images.githubusercontent.com/82483575/115133604-3b7c9880-9fcf-11eb-8db3-f2a7f9723e45.png)

**How to reproduce:**
Open a Hidden Stash container. Mr. Grubbs will be the only item inside.

**How it should work:**
Gold, items, and other possibilities may be contained within each Hidden Stash.

**Wowhead links:**
https://www.wowhead.com/item=61387/hidden-stash

**Comment by Ahumaya** [comment]
To add to this issue, a few new bugs have been encountered:

The Hidden Stash will drop from EPL enemies regardless of if the player has Fiona's Lucky Charm or not. If the player does not have Fiona's Lucky Charm, the Hidden Stash item will not contain anything.

Also, per reports from Vantrith, players with Fiona's Lucky Charm will also sometimes get nothing.

**Comment by UltraNix** [comment]
Dropping works okay. Cannot drop if does not have the aura.
