### ISSUE TITLE
[PHASING] Tyr's Hand - After Soft Landing

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#310]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
After turning in the quest Soft Landing, a Phase change should be made which will place you in a phase with Commander Eligor Dawnbringer and Crusade Commander Korfax. Currently, no Phase change is made, leaving the 2 necessary NPCs outside of the gates to Tyr's Hand.
![tyr0417](https://user-images.githubusercontent.com/82483575/115133753-42f07180-9fd0-11eb-8e86-f70251879862.png)

**How to reproduce:**
Complete Soft Landing while in Tyr's Hand. Obtain the next 2 quests, To Take the Abbey and To Take the Barracks. Observe that the hand-in NPCs are not inside Tyr's Hand, but are still outside.

**How it should work:**
A phase change should be made once the quest Soft Landing is handed in.

**Wowhead links:**
https://www.wowhead.com/quest=27460/soft-landing
https://www.wowhead.com/quest=27461/to-take-the-abbey
https://www.wowhead.com/quest=27462/to-take-the-barracks

**Comment by UltraNix** [comment]
Fixed.
