### ISSUE TITLE
[Ability] [Hunter] Track Hidden not working

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#315]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The ability 'Track Hidden' should reveal hidden units on the minimap. It however does nothing.

**How to reproduce:**
Use 'Track Hidden' near stealthed monsters. See nothing on minimap.

**How it should work:**
Use 'Track Hidden' near stealthed mobs. See circles of the monsters on the minimap.

**Comment by Xeraton** [comment]
If i remember this correctly, this should increade just the range to see hidden Enemies.

**Comment by UltraNix** [comment]
Everything works okay.
