### ISSUE TITLE
[Quest] Stomp to my Beat

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#316]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
you can't use the drums to boost the Revantusk Hexxer NPCs, it always shows "invalid target" 

**How to reproduce:**
use the drum on the NPC

**How it should work:**

**Wowhead links:**
https://www.wowhead.com/quest=26240/stomp-to-my-beat

**Comment by UltraNix** [comment]
Works okay.
