### ISSUE TITLE
[Rares][Eastern Plague Lands] Rares in EPL drop level 50+ loot. (Its a 40-45 zone)

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#319]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Kill a rare, see level 50+ loot dropped. Should be level appropiate loot (40-45)

**How to reproduce:**
Kill a rare, loot it. See high level loot

**How it should work:**
Kill a rare, loot it. See level appropiate loot (40-45)

![image](https://user-images.githubusercontent.com/82404667/115266458-82d26880-a138-11eb-9888-2ee32ff9a3b7.png)
Imagine of the spawn location of the rares.

List of rares:
Lord Darkscythe https://www.wowhead.com/npc=10826/lord-darkscythe
Duke Ragereaver https://www.wowhead.com/npc=10820/duke-ragereaver
Deathspeaker selendre: https://www.wowhead.com/npc=10827/deathspeaker-selendre
Foreman Marcrid https://www.wowhead.com/npc=1844/foreman-marcrid
Duggan wildhammer https://www.wowhead.com/npc=10817/duggan-wildhammer
Foreman Jerris https://www.wowhead.com/npc=1843/foreman-jerris
Deathhunter Hawkspear: https://www.wowhead.com/npc=10824/death-hunter-hawkspear
Lynnia Abbendis: https://www.wowhead.com/npc=10828/lynnia-abbendis
Nerubian Overseer: https://www.wowhead.com/npc=16184/nerubian-overseer

**Comment by HerodDev** [comment]
Add links to those npcs

**Comment by Lapaco94** [comment]
Those are the one's I could find/kill with wrong loot.
