### ISSUE TITLE
[Quest Items] Long Respawn Time

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#320]
**Description:**
Almost all the lootable quest items, have a 2-5 minute-ish respawn time. From blowing up ammo in ratchet, to looting a prayerbook in EPL. It all takes a pretty long time with two players. The respawns are slow. It'll be absolutely horrible if it launches like this.

**How to reproduce:**
Loot almost any loot-only quest item. And watch it respawn painfully slow.

**How it should work:**
Item respawns in a reasonable time.

**Comment by UltraNix** [comment]
No links/no examples.
