### ISSUE TITLE
[Quest] [Tanaris] Rocket Rescue pirate kills dont count

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#321]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Kills on the pirates don't count. Life-saving rockets do work.

**How to reproduce:**
Throw bomb at pirates. Get 0 killcount

**How it should work:**
Throw bomb at pirates. Get kill count

**Wowhead links:**
https://www.wowhead.com/quest=24910/rocket-rescue

**Comment by UltraNix** [comment]
Works okay.
