### ISSUE TITLE
[Quest] [Un'Goro] Finding the source, only one spawn.

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#322]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
There's only one hot lava spot, randomzing temperatures. There should be several throughout the area

**How to reproduce:**

**How it should work:**
There should be several hot spots around 'The Plume Ridge'

**Wowhead links:**

**Comment by HerodDev** [comment]
Add wowhead links to this quest

**Comment by Lapaco94** [comment]
My bad, forgot to do that. It's supposed to be the spot ontop of the mountain. It's randomised now.

https://www.wowhead.com/quest=24742/finding-the-source

**Comment by UltraNix** [comment]
There are 5 spots around the mountain.
