### ISSUE TITLE
[Object] [Un'goro]  Power Crystal Spawns are very low

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#323]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
There are alot of Power Crystals spawn missing. There's very few around (Blue seems fine though)

**How to reproduce:**

**How it should work:**

**Wowhead links:**
https://www.wowhead.com/quest=24720/crystals-of-power

**Comment by HerodDev** [comment]
Add wowhead links

**Comment by Lapaco94** [comment]
Added wowhead link.
