### ISSUE TITLE
[Quest] [Ungoro] Crystals of Power, cant deliver with items present

### ISSUE THREAD

**Issue by Lapaco94** [GameFreedomGG/Maelstrom#325]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Can't deliver the quest while having all crystals of power (see screenshot)

**How to reproduce:**
Get items, try to deliver. Fail

**How it should work:**
Completing quest with items present

**Wowhead links:**
https://www.wowhead.com/quest=24720/crystals-of-power
![image](https://user-images.githubusercontent.com/82404667/115155732-7c34ea00-a081-11eb-900b-02b576a5d8b3.png)

**Comment by HerodDev** [comment]
Add links to wowhead

**Comment by V3n1m** [comment]
i was able to turn them in, no problem 🤷

**Comment by Lapaco94** [comment]
I was able to turn them in after abandoning the quest, and then retaking it. Idk...

**Comment by UltraNix** [comment]
Works okay.
