### ISSUE TITLE
Westfall Homeless stormwind citizen bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#333]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
When i attacked a homeless stormwind Citizen and ran away from the npc, the npc continued to follow me after i was far away from the pumpkin patch the npc was supposed to stay at. The npc also did not attack me while i was running away and when i was still, the npc did not attack me. https://imgur.com/a/pzTVs0k

**How to reproduce:**
attack a homeless stormwind citizen npc and run away from the npc away from the pumpkin patch they spawn in near lieutenant Horatio Lane.

**How it should work:**
The Homeless Stormwind Citizen should stop following the attacking player after a short to medium distance away from the pumpkin patch and should also attack the player when attacked. 

**Wowhead links:**
https://www.wowhead.com/npc=42386/homeless-stormwind-citizen

**Comment by UltraNix** [comment]
Cannot reproduce it.
