### ISSUE TITLE
[Quest] [Southern Barrens] A Line in the Dirt (Horde)

### ISSUE THREAD

**Issue by IamNylea** [GameFreedomGG/Maelstrom#334]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Quest doesn't work. After clicking on the Field Banner, it disappears and nothing else happens.

**How to reproduce:**
Pick up q from Kirge Sternhorn. Go to the Fields of Blood and find grey banner. Click on it.

**How it should work:**
https://www.youtube.com/watch?v=7GlWgjEPukU

**Wowhead links:**
https://www.wowhead.com/quest=24546/a-line-in-the-dirt

**Comment by Ahumaya** [comment]
The Alliance version of this quest has the same issue.
