### ISSUE TITLE
Murlocks in Lake Everstill bugs

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#335]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Murlocks in Lake Everstill seem to have a large pull range and Murlock Scouts specifically have the ability to shoot but the projectiles do not show and the damage numbers of the ranged attacks show, The Murlock scouts also do not show a Shooting animation.

**How to reproduce:**
Attack a Murlock Scout in Lake Everstill In Redridge Mountains

**How it should work:**
The Murlocks should not have a Large Pull range and should Only engage at medium to close range (this could be an issue with all npc's). The Murlocks scouts should also show a shooting animation and the projectiles of the ranged attack should also show

**Wowhead links:**
https://www.wowhead.com/npc=578/murloc-scout

**Comment by UltraNix** [comment]
Fixed.
