### ISSUE TITLE
Wanted signs in Redridge Mountains (two exist) near Tower watch in three corners

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#336]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The wanted signs for the Wanted: Redridge gnolls quest spawns twice but the quest cannot be accepted twice.

**How to reproduce:**
Go to Tower Watch, in Three corners, in Redridge Mountains and outside the entrance of Tower Watch there are two wanted signs, one on each side of the tower entrance. These signs have the quest, observe the signs to see that there are two of them and accept the quest from one of them.

**How it should work:**
Only one sign offering the Wanted: Redridge gnolls quest should exist Near Tower watch in Three corners

**Wowhead links:**
https://www.wowhead.com/quest=26504/wanted-redridge-gnolls

**Comment by UltraNix** [comment]
It's okay. It's the same sign, but doubled spawn.
