### ISSUE TITLE
[Quest] Pirate Accuracy Increasing

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#337]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
you can't extinguish the fire while on the boat

**How to reproduce:**
accept the quest, get into the boat and shoot the fire

**How it should work:**
fires should be extinguished if you aim the skill at them

**Wowhead links:**
https://www.wowhead.com/quest=25533/pirate-accuracy-increasing

**Comment by UltraNix** [comment]
Fixed.
