### ISSUE TITLE
[NPC] Krixx

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#338]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
he's floating while moving

**How to reproduce:**
teleport to him

**How it should work:**
he should have the usual walk animation

**Wowhead links:**
https://www.wowhead.com/npc=23635/krixx

**Comment by UltraNix** [comment]
Works okay.
