### ISSUE TITLE
Crossroad Caravan Delivery

### ISSUE THREAD

**Issue by PendingtonFlex** [GameFreedomGG/Maelstrom#34]
**Description:**
Northern Barrens quest from Rocco Whipshank, you have to speak to him after you grab the quest to start the escort, he's giving up no secondary dialogue to start it. Currently unable to complete.

**Comment by HerodDev** [comment]
https://www.wowhead.com/npc=34578/rocco-whipshank
https://www.wowhead.com/quest=13975/crossroads-caravan-delivery
whole caravan to script

**Comment by HerodDev** [comment]
https://www.youtube.com/watch?v=LSXvGXA6ovY
