### ISSUE TITLE
[NPC] Braindead Enemies in Tanaris (and possible all over the world)

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#346]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
In Northern Tanaris, all the npcs don't have waypoints. 

EDIT: after close inspection, every mob in the ungoro crater has missing waypoints. 

Full List
Glasshide Basilisk
Blisterpaw Hyena 
Duneclaw Burrower
Duneclaw Lasher
Duneclaw Matriarch
Tidal Strider
Sandfury Hideskinner
Sandfury Firecaller
Sandfury Axethrower
Sandstone Golem
Sand Slitherer

**How to reproduce:**
just look at them, they stand still. 

**How it should work:**
Usualy all NPCs have some area where they walk around

**Wowhead links:**
https://www.wowhead.com/npc=5419/glasshide-basilisk
https://www.wowhead.com/npc=5426/blisterpaw-hyena
https://www.wowhead.com/npc=44546/duneclaw-burrower
https://www.wowhead.com/npc=39022/tidal-strider
https://www.wowhead.com/npc=40656/duneclaw-matriarch
https://www.wowhead.com/npc=40717/duneclaw-lasher
https://www.wowhead.com/npc=93503/sandfury-firecaller
https://www.wowhead.com/npc=93502/sandfury-hideskinner
https://www.wowhead.com/npc=5646/sandfury-axe-thrower
https://www.wowhead.com/npc=38914/sandstone-golem
https://www.wowhead.com/npc=44595/sand-slitherer

**Comment by UltraNix** [comment]
Fixed.
