### ISSUE TITLE
[Quest] The Secrets of Uldum

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#348]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
If you run towards the quest marker in uldum, you get teleported to your hearthstone location

**How to reproduce:**
Try to complete the quest inside the cave

**How it should work:**
i assume its because you closed the cata zones, but still you should be able to reach the npc inside the cave

**Wowhead links:**
https://www.wowhead.com/quest=25069/the-secrets-of-uldum

**Comment by UltraNix** [comment]
Cannot reproduce it.
