### ISSUE TITLE
Breaking the Line Quest

### ISSUE THREAD

**Issue by PendingtonFlex** [GameFreedomGG/Maelstrom#350]
https://www.wowhead.com/quest=25035/breaking-the-line
https://www.wowhead.com/npc=38442/morakki

**Description:**
Doesn't properly dismount you at the intended location, for some reason mounting, not like regular mounts, but for instance like wintergrasp vehicles, or instances in which the player takes over a creature interacts with water very harshly and you cant move around properly.

**How to reproduce:**
this quest will stop you in the water and you will have a difficult time getting out of the water for some odd reason, my forward movement key (W) wont work and I have to M1 + M2 to move forward

**How it should work:**
Should drop you off right infront of cave by Morakki

**Comment by UltraNix** [comment]
?? I don't understand at all.
