### ISSUE TITLE
[QUEST] Visual bug on Adana Thunderhorn

### ISSUE THREAD

**Issue by Volkyte** [GameFreedomGG/Maelstrom#353]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
she remains with exclamation amrk despite getting her quests: https://imgur.com/z5QXakN

**How to reproduce:**
just take quests from her

**How it should work:**
once accepted quests there should be a question mark, not exclamation mark

**Wowhead links:**
https://www.wowhead.com/quest=14455/stop-the-thorncallers

**Comment by V3n1m** [comment]
duplicate
https://github.com/SallyWhitemane/Herod/issues/274
