### ISSUE TITLE
[QUEST] A Spirit Guide - Credit automatically awarded

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#358]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Quest credit for A Spirit Guide is automatically awarded on quest accept. Turn-in on map indicates location of Krun Spinebreaker's corpse, which is not the correct location.

https://user-images.githubusercontent.com/82483575/115304187-40a22a80-a12a-11eb-893f-6da7301535af.mp4

**How to reproduce:**
Accept the quest A Spirit Guide from Far Seer Regulkut in Thrallmar, Hellfire Peninsula

**How it should work:**
Quest credit should not be automatically awarded.

**Wowhead links:**
https://www.wowhead.com/quest=9410/a-spirit-guide

**Comment by Ahumaya** [comment]
Update, this issue appears to make the quest impossible. The Mag'har remain Unfriendly, and you can not talk to them to complete the quest.

**Comment by UltraNix** [comment]
Everything works okay.
