### ISSUE TITLE
[NPC] Marauding Crust Burster - Move while above ground

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#359]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Marauding Crust Burster (and possibly other sand worm type creatures) will move while above ground.

https://user-images.githubusercontent.com/82483575/115304979-3cc2d800-a12b-11eb-8ced-287473be9b16.mp4

**How to reproduce:**
Engage Marauding Crust Bursters in combat, observe their AI.

**How it should work:**
They should not move while above ground. If the AI needs to move, they should submerge.

**Wowhead links:**
https://www.wowhead.com/npc=16857/marauding-crust-burster

**Comment by UltraNix** [comment]
Works okay.
