### ISSUE TITLE
Npc's not evading

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#366]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Npc's when staying still while inside an object or in a place where they cannot attack the player do not evade the players attacks, there may be some cases when an npc is not supposed to evade attacks but this seems to be a case where the npc is supposed to evade.

**How to reproduce:**
attack an npc and try to get the npc inside an object and continue to attack the npc

**How it should work:**
The npc should in some cases evade player attacks when the npc cannot attack the player.

**Wowhead links:**

**Comment by UltraNix** [comment]
No links/no proofs.
