### ISSUE TITLE
Mind Flay bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#367]
**Description:**
casting mindflay as a shadowpriest as soon as the current mindflay being cast finishes will increase the duration of the new mind flay.

**How to reproduce:**
cast mind flay on an attackable target and cast a new mind flay as soon as the mind flay channel affect finishes at the right time.

**How it should work:**
Recasting mindflay should not extend the duration of a new mindflay no matter when the ability is re-cast.

**Wowhead links:**
https://www.wowhead.com/spell=15407/mind-flay

**Comment by UltraNix** [comment]
Cannot reproduce it.
