### ISSUE TITLE
[Gameobject][Outland-Hellfire Peninsula] Salvaged Wood/Metal 

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#369]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
you can still click the items on the ground even if have completed the quest already and turned it in.

**How to reproduce:**
look for item and loot it

**How it should work:**
you shouldnt be able to click it, right now you can camp them and prevent other players from completing their quest

**Wowhead links:**

https://www.wowhead.com/quest=10055/waste-not-want-not
https://www.wowhead.com/quest=10086/i-work-for-the-horde

**Comment by Afgann** [comment]
fixed
