### ISSUE TITLE
Daggertooth Shark

### ISSUE THREAD

**Issue by Turbocoom** [GameFreedomGG/Maelstrom#37]
**Description:**
Daggertooth shark mobs in The Lost Isles can't attack you if your character isn't fully submerged. I'd imagine this isn't the only aquatic mob this applies to.

**How to reproduce:**
Pull aggro on a shark and swim up.

**How it should work:**
The shark should be able to find a path to my character. 
![WoWScrnShot_041121_204248](https://user-images.githubusercontent.com/82345768/114337861-c577bd80-9b06-11eb-91c9-29bf2186c312.jpg)

**Comment by UltraNix** [comment]
Looks okay.
