### ISSUE TITLE
[QUEST] Red Snapper - Very Tasy!

### ISSUE THREAD

**Issue by konradkolota** [GameFreedomGG/Maelstrom#371]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
You can click hasty on the net to aquire fish or spawn murlock on one fish school even if it was used earlier

**How to reproduce:**
spam-click on `[Draenei Fishing Net]` near one of `[School of Red Snapper]` 

**How it should work:**
Afer using net near one school it should disappear and could not be used again. You have to travel to another school to use net again.

**Wowhead links:**
https://www.wowhead.com/quest=9452/red-snapper-very-tasty

**Comment by UltraNix** [comment]
Cannot reproduce it.
