### ISSUE TITLE
[NPC] unknown ghost model in hellfire peninsula

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#372]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
i have never seen this before, you can't attack it or pull aggro from him
![image](https://user-images.githubusercontent.com/47416114/115446971-3a8a7780-a218-11eb-8943-d8552ef9ccae.png)

found another one
![image](https://user-images.githubusercontent.com/47416114/115450318-07e27e00-a21c-11eb-9375-37d0bbc6b079.png)

**How to reproduce:**

**How it should work:**

**Wowhead links:**

**Comment by UltraNix** [comment]
Should be fixed.
