### ISSUE TITLE
[SPELL] Item - Place Signaling Gem DND - Odd Spell text during quest item usage

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#374]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest The Cleansing Must Be Stopped, the item Signaling Gem is used in the Pools of Aggonar. When used, a Spell bar appears with the text "Item - Place Signaling Gem DND". This text should not appear here.
![sig0420](https://user-images.githubusercontent.com/82483575/115453337-237e6200-a1e5-11eb-8bc8-6694718d6b86.png)

**How to reproduce:**
Use the Signaling Gem next to the altar in the Pools of Aggonar.

**How it should work:**
The text should be invisible, showing only a progress bar.

**Wowhead links:**
https://www.wowhead.com/quest=9370/the-cleansing-must-be-stopped
https://www.wowhead.com/item=23358/signaling-gem
https://www.wowhead.com/spell=29279/item-place-signaling-gem-dnd

**Comment by Afgann** [comment]
fixed
