### ISSUE TITLE
[QUEST] Vision Guide - Credit not awarded

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#375]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
When arriving at the Thunderlord Spear, no quest credit is provided, and the spear can not be interacted with, nor does walking near the spear provide credit.
![vsg0420](https://user-images.githubusercontent.com/82483575/115454673-aa800a00-a1e6-11eb-8aa4-33d0936cc250.png)

**How to reproduce:**
Attempt to complete the quest Vision Guide

**How it should work:**
Credit should be awarded with the Fiery Spirit Fragment buff Vision Guide arrives at the Thunderlord Spear.

**Wowhead links:**
https://www.wowhead.com/quest=10525/vision-guide

**Comment by UltraNix** [comment]
Works okay.
