### ISSUE TITLE
[QUEST] Teleport This! - Cyber-Rage Forgelords can not be controlled

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#381]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Teleport This!, you need to use the Mental Interference Rod to mind control Cyber-Rage Forgelords. Currently, this does not work, and the Charmed buff is applied to the player character.
![tet0420](https://user-images.githubusercontent.com/82483575/115488849-d15b3200-a220-11eb-8040-68636d3c4759.png)

**How to reproduce:**
Attempt to control Cyber-Rage Forgelords during the quest Teleport This!

**How it should work:**
The creatures should be controlled, and a pet bar should appear, allowing you to use the Detonate ability to destroy the portals, giving quest credit.

**Wowhead links:**
https://www.wowhead.com/quest=10857/teleport-this

**Comment by UltraNix** [comment]
Works okay.
