### ISSUE TITLE
[QUEST] Waltz Right In - Disguise not shown

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#384]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Mook disguise is not displayed visually during the quest Waltz Right In.
![wal0420](https://user-images.githubusercontent.com/82483575/115494233-d9b86a80-a22a-11eb-893f-4ba5571302ef.png)

**How to reproduce:**
Accept the quest Waltz Right In and enter Gallywix's Villa

**How it should work:**
A visual disguise should be shown over the player character:
![image](https://user-images.githubusercontent.com/82483575/115494195-c3121380-a22a-11eb-81dc-d419c509aa25.png)

**Wowhead links:**
https://www.wowhead.com/quest=14123/waltz-right-in

**Comment by UltraNix** [comment]
As I can see on different videos, I thinks it's not related to this quest.
