### ISSUE TITLE
[PHASING] Trade Prince Gallywix still inside KTC Headquarters during quest 447

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#385]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Trade Prince Gallywix is still inside KTC Headquarters during 447, just as we're about to blow up the place. Also note that Assistant Greely and Hobart Grapplehammer are also still insite.
![gal0420](https://user-images.githubusercontent.com/82483575/115494672-bc37d080-a22b-11eb-9591-3e2d08333b4f.png)

**How to reproduce:**
Head upstairs in KTC Headquarters during the quest 447. Observe that Trade Prince Gallywix, Assistant Greely, and Hobart Grapplehammer are still inside. 

**How it should work:**
Trade Prince Gallywix should not be inside the building. Nor should Assistant Greely or Hobart Grapplehammer.

**Wowhead links:**
https://www.wowhead.com/quest=14125/447

**Comment by UltraNix** [comment]
Fixed.
