### ISSUE TITLE
[QUEST] Goblin Escape Pods - Survivors are bugged, sometimes do not spawn

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#386]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Goblin Survivors from Goblin Escape Pods during the quest Goblin Escape Pods act erratically and jump around on the screen, and sometimes do not spawn. Additionally, the pods can be clicked repeatedly. Also, the first person rescued should be Trade Prince Gallywix, who should have a text bubble conversation with the player character.

https://user-images.githubusercontent.com/82483575/115495497-5c422980-a22d-11eb-8e57-4bce91e9083c.mp4

**How to reproduce:**
Attempt to complete the Goblin Escape Pods quest

**How it should work:**
Goblin survivors should spawn, thank the player, and head to shore. Goblin Escape Pods should only allow each player to click on a pod once before moving on. The first pod opened should contain Trade Prince Gallywix.

**Wowhead links:**
https://www.wowhead.com/quest=14001/goblin-escape-pods

**Comment by UltraNix** [comment]
Fixed.
