### ISSUE TITLE
[PRIEST] Shadow Orb - Visual bug, number of orbs doesn't match stack

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#390]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The number of Shadow Orbs rotating around your character does not match the number of stacks of Shadow Orb you have.

https://user-images.githubusercontent.com/82483575/115607561-bd5c1280-a2aa-11eb-93d6-4fbba0c263c4.mp4

**How to reproduce:**
Acquire the Shadow Orb buff while on a Shadow Priest.

**How it should work:**
The number of Shadow Orbs revolving around your character should match the number of stacks of the Shadow Orb buff you have.

**Wowhead links:**

**Comment by UltraNix** [comment]
It's a clientside visual. Number of rotating orbs means nothing.
