### ISSUE TITLE
[QUEST] Mine Disposal, the Goblin Way - Satchel of Grenades does not detonate Land Mines

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#391]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest Mine Disposal, the Goblin Way, the Satchel of Grenades item does not detonate Land Mines and award quest credit. Instead, the land mines must be interacted with directly.

https://user-images.githubusercontent.com/82483575/115611785-26925480-a2b0-11eb-9b41-86acecdac5fa.mp4

**How to reproduce:**
Attempt to use the Satchel of Grenades item on the Land Mine gameobjects.

**How it should work:**
The Satchel of Grenades item should detonate Land Mines and award quest credit.

**Wowhead links:**
https://www.wowhead.com/quest=25058/mine-disposal-the-goblin-way

**Comment by UltraNix** [comment]
Works okay.
