### ISSUE TITLE
[QUEST] Wild Mine Cart Ride - Mine Cart despawns when entering combat

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#392]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Similar to #388 if the Mine Cart aggroes an enemy during the ride, the Mine Cart will despawn, leaving you in combat. This is worse than #388 however, as you must complete the ride in the Mine Cart to get quest credit.

**How to reproduce:**
Attempt to complete Wild Mine Cart Ride while aggressive enemies are nearby.

**How it should work:**
The Mine Cart should not despawn if it aggroes enemies.

**Wowhead links:**
https://www.wowhead.com/quest=25184/wild-mine-cart-ride

**Comment by UltraNix** [comment]
Fixed.
