### ISSUE TITLE
[QUEST] She Loves Me, She Loves Me NOT! and What Kind of Name is Candy, Anyway? - Wrong Gender

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#394]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
She Loves Me, She Loves Me NOT! and What Kind of Name is Candy, Anyway? are Male and Female versions, respectively, of the same quest to kill Candy Cane. Currently, Male Goblins can receive both quests. This is similar to #393 
![she0421](https://user-images.githubusercontent.com/82483575/115617347-eaaebd80-a2b6-11eb-9ab2-819af673f7c4.png)

**How to reproduce:**
As a Male Goblin, speak with Sassy Hardwrench after turning in The Slave Pits.

**How it should work:**
Male Goblins should only receive She Loves Me, She Loves Me NOT!, and Female Goblins should only receive What Kind of Name is Candy, Anyway?

**Wowhead links:**
https://www.wowhead.com/quest=25243/she-loves-me-she-loves-me-not
https://www.wowhead.com/quest=25244/what-kind-of-name-is-candy-anyway

**Comment by UltraNix** [comment]
Fixed.
