### ISSUE TITLE
[QUEST] By the Skin of His Teeth

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#395]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
During the quest By the Skin of His Teeth, as Worgen are jumping across the roof, an emote is given in the chatbox that says <error> repeatedly.
![ski0421](https://user-images.githubusercontent.com/82483575/115621548-4af42e00-a2bc-11eb-872d-1e6146ec527f.png)

**How to reproduce:**
Attempt to complete the quest By the Skin of His Teeth.

**How it should work:**
The emote should instead say "Worgen Runt goes into a frenzy!"

**Wowhead links:**
https://www.wowhead.com/quest=14154/by-the-skin-of-his-teeth

**Comment by UltraNix** [comment]
Fixed.
