### ISSUE TITLE
Quest: Teron Gorefiend, I am

### ISSUE THREAD

**Issue by Suriass** [GameFreedomGG/Maelstrom#408]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest once started, you control Teron Gorefiend but after first attack you get out of him and can't do the quest for some minutes till Gorefiend resets 

**How to reproduce:**
Just accept and try to do the quest, its not working

**How it should work:**
Once getting Gorefiend a Elite Draenei should spawn and we had to kill it, but the draenei don't spawn 

**Wowhead links:**
https://www.wowhead.com/quest=10639/teron-gorefiend-i-am

**Comment by Suriass** [comment]
![image](https://user-images.githubusercontent.com/83075715/115877117-780c2200-a41d-11eb-8a70-57f21273483f.png)

**Comment by Malphaes** [comment]
Greetings,
As of today, 10.09.2023 the quest has started acting once again like Suriass mentioned 2 years ago. 
Description:
After you control Teron Gorefiend  you get out of him in no more then 3-4 seconds and can't do the quest for some minutes untill Gorefiend resets

How to reproduce:
Just accept and try to do the quest. Add the despawn time.

How it should work:
Once getting Gorefiend a Elite Draenei should spawn and we had to kill it, but the draenei npc will not spawn

Wowhead links:
https://www.wowhead.com/quest=10639/teron-gorefiend-i-am

**Comment by Malphaes** [comment]
![WoWScrnShot_100923_125135](https://github.com/gamefreedomgit/Maelstrom/assets/147389713/ce894fff-6e26-4828-bd8c-27ac7dcb3a25)
