### ISSUE TITLE
Shield slam bug

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#411]
**Description:**
The shield slam ability for warriors does not remove a beneficial magic effect from an eligible target

**How to reproduce:**
Use the ability shield slam on a target and observe the targets beneficial magic effect

**How it should work:**
The shield slam ability should remove a beneficial magic effect when used on a target that has a removable effect

**Wowhead links:**
https://www.wowhead.com/spell=23922/shield-slam

**Comment by UltraNix** [comment]
Works okay.
