### ISSUE TITLE
npc doubling

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#413]
**Description:**
each npc for the quest chain that the quest "last but not least....danforth" is a part of doubles in amount each time a player dies and ressurects.

**How to reproduce:**
accept one of the quests for that quest chain and have one or more of the npc's follow you, then die and resurrect.

**How it should work:**
The npc's should not keep doubling each time a player ressurects and the npc's should maybe disapear when the player dies and reapear when the player ressurects.

**Wowhead links:**
https://www.wowhead.com/quest=26562/and-last-but-not-least-danforth

**Comment by UltraNix** [comment]
Works okay to me.
