### ISSUE TITLE
Guild rep gain

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#415]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
guild reputation seems to be obtained in small amounts, this seems unusual.

**How to reproduce:**
Do an activity that can give guild reputation, or use a guild tabarb

**How it should work:**
Guild reputation should be obtained in larger amounts (exact amount unknown).

**Wowhead links:**

**Comment by UltraNix** [comment]
No proofs.
