### ISSUE TITLE
[Quest] High Priest Jeklik 

### ISSUE THREAD

**Issue by llogan1233** [GameFreedomGG/Maelstrom#42]
**Description:**
The quest "High Priest Jeklik" isn't scripted at all apart from the two dialogue lines Zanzil has at the start and doesn't do any of the mechanics it's meant to.  High Priest Jeklik just evades all attacks when she should be able to take damage.
**How to reproduce:**
Damage Zanzil until he disappears and try to attack High Priestess Jeklik

**How it should work:**
https://www.youtube.com/watch?v=Z5snxP4qs7Q

**Comment by HerodDev** [comment]
merging other issues into one

**Comment by HerodDev** [comment]
**Description**:
After doing this quest https://www.wowhead.com/quest=26553/high-priestess-jeklik#videos.
You should get the follow up quest instantly : https://www.wowhead.com/quest=26554/plunging-into-zulgurub#videos:id=51492
where you could go into the portal in front of you, by clicking it. But you dont get the quest, and you cant even go into the portal.
**How to reproduce**:
Finish the High Priestess Jeklik quest, complete it, try going into the portal
**How it should work**:
You should get the next quest after completing the current one, and you should be able to go to the portal by clicking it.
![WoWScrnShot_041321_112946](https://user-images.githubusercontent.com/58514021/114531565-4d1b1480-9c4c-11eb-94f8-ea00c169e2b5.jpg)

**Comment by HerodDev** [comment]
Can confirm that there is no follow up quest right after you complete quest. Somehow after you use fetish item to return to npc and teleport back to Zul'Gurrub after you talk to her, quest gets auto-completed although I didn't even accept it nor see it.

**Comment by HerodDev** [comment]
**Description:**
The boss is evade, we can't kill her
The gameobject it's located on should probably bug it

**How to reproduce:**


**How it should work:**
We should be able to kill the boss

**Comment by HerodDev** [comment]
[/]: # (Add links to things related to the bug using for example http://wowhead.com)

**Description:**https://www.wowhead.com/quest=26553/high-priestess-jeklik

 This quest is totally broken, too much to explain none of the scripting works and after finishing it the follow up quest https://www.wowhead.com/quest=26554/plunging-into-zulgurub doesnt become avaible.


**How to reproduce:**


**How it should work:** https://www.youtube.com/watch?v=cE8hbHWkU-g

**Comment by Greywolf59** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/118
@UltraNix The issue with the Quest Chain persists.
Timestamp 3:14 at https://www.youtube.com/watch?v=cE8hbHWkU-g&t=17s
After handing in [High Priestess Jeklik](https://www.wowhead.com/quest=26812/high-priestess-jeklik) via comm, you should be offered the next quest, [Plunging Into Zul'Gurub](https://www.wowhead.com/quest=26813/plunging-into-zulgurub), also via comm. When you use the portal, which is not usable without the quest, you complete the quest and you should hand it via comm again, which is also not the case on the server atm. After that, you should get quest [High Priest Venoxis](https://www.wowhead.com/quest=26814/high-priest-venoxis), again via comm.
