### ISSUE TITLE
Eastern Plague Lands - Terrorweb Tunnel

### ISSUE THREAD

**Issue by Zeldrone0** [GameFreedomGG/Maelstrom#420]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The mobs just stand still and do nothing 

**How to reproduce:**
Go to the location mentioned in the title

**How it should work:**
the mobs there should attack you
**Wowhead links:**

**Comment by HerodDev** [comment]
Add wowhead links

**Comment by UltraNix** [comment]
No links - I don't know which creatures have wrong SAI.
