### ISSUE TITLE
Fenros elite mob bugged

### ISSUE THREAD

**Issue by GitGudNubHub** [GameFreedomGG/Maelstrom#43]
**Description:**
Its impossible to hit a elite mob called Fenros in duskwood.
He literally parries and dodges all attack. Spent 2 minutes attacking it, and the only way I could hit him was with thunder clap,. which cannot be dodged or parried.

**How to reproduce:**
Find the mob. Attack it

**How it should work:**
You should  be able to hit him,
screenshots
![WoWScrnShot_041221_112423](https://user-images.githubusercontent.com/58514021/114372628-0fea5000-9b82-11eb-9f35-dc65e9822b47.jpg)
![WoWScrnShot_041221_112425](https://user-images.githubusercontent.com/58514021/114372635-1082e680-9b82-11eb-88a2-25f22f25c997.jpg)
![WoWScrnShot_041221_112429](https://user-images.githubusercontent.com/58514021/114372639-111b7d00-9b82-11eb-855f-c8ff13589084.jpg)
![WoWScrnShot_041221_112432](https://user-images.githubusercontent.com/58514021/114372641-111b7d00-9b82-11eb-9e20-c2f3bd63d2bc.jpg)

**Comment by xcenon92** [comment]
![WoWScrnShot_041221_120855](https://user-images.githubusercontent.com/82336595/114378343-e7fdeb00-9b87-11eb-913b-ef746db743e7.jpg)
![WoWScrnShot_041221_120900](https://user-images.githubusercontent.com/82336595/114378363-ec2a0880-9b87-11eb-87f1-b93080cdec0b.jpg)


thank  me later i killed a unkillable mob

**Comment by GitGudNubHub** [comment]
> ![WoWScrnShot_041221_120855](https://user-images.githubusercontent.com/82336595/114378343-e7fdeb00-9b87-11eb-913b-ef746db743e7.jpg)
> ![WoWScrnShot_041221_120900](https://user-images.githubusercontent.com/82336595/114378363-ec2a0880-9b87-11eb-87f1-b93080cdec0b.jpg)
> 
> thank me later i killed an unkillable mob

You used spells, if you are a warrior,rog you cannot kill that mob...

**Comment by xcenon92** [comment]
yep thats why my felguard killed him

**Comment by xcenon92** [comment]
> > ![WoWScrnShot_041221_120855](https://user-images.githubusercontent.com/82336595/114378343-e7fdeb00-9b87-11eb-913b-ef746db743e7.jpg)
> > ![WoWScrnShot_041221_120900](https://user-images.githubusercontent.com/82336595/114378363-ec2a0880-9b87-11eb-87f1-b93080cdec0b.jpg)
> > thank me later i killed an unkillable mob
> 
> You used spells, if you are a warrior,rog you cannot kill that mob...
>mate your lvl was just to low there is skull on his portrait

**Comment by GitGudNubHub** [comment]
> > > ![WoWScrnShot_041221_120855](https://user-images.githubusercontent.com/82336595/114378343-e7fdeb00-9b87-11eb-913b-ef746db743e7.jpg)
> > > ![WoWScrnShot_041221_120900](https://user-images.githubusercontent.com/82336595/114378363-ec2a0880-9b87-11eb-87f1-b93080cdec0b.jpg)
> > > thank me later i killed an unkillable mob
> > 
> > 
> > You used spells, if you are a warrior,rog you cannot kill that mob...
> > mate your lvl was just to low there is skull on his portrait

Thats not how it works, mate. Even if a  mob is higher lvl than you, you should still be able to hit it. Its just less likely.

**Comment by UltraNix** [comment]
No bug here.
