### ISSUE TITLE
[NPC] Neptool - Text interaction from another NPC

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#435]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Neptool appears to have a text interaction from the NPC Old Ironbark in Dire Maul. Please see the screenshot below:
![nep0425](https://user-images.githubusercontent.com/82483575/116003599-471a2180-a5c4-11eb-91c6-5c9a9728ef9b.png)

**How to reproduce:**
Speak with Neptool in The Red Reaches in the Blasted Lands. You may need to be on Home... Gone... Naga...

**How it should work:**
Neptool should not have this text interaction.

**Wowhead links:**
https://www.wowhead.com/npc=41354/neptool
https://www.wowhead.com/npc=11491/old-ironbark
https://www.wowhead.com/quest=25702/home-gone-naga

**Comment by Ahumaya** [comment]
The Old Ironbark in Dire Maul has the exact same flavor text and interact option

**Comment by UltraNix** [comment]
Works okay.
