### ISSUE TITLE
npcs not following player while not in line of sight

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#440]
**Description:**
the Nightbane shadow weaver npc in Duskwood does not follow player after being out of line of sight and this might be happening with any
npc the player is in combat with.

**How to reproduce:**
attack the nightbane worgen npc and move out of the line of sight of the npc.

**How it should work:**
The nightbane worgen npc should follow the player untill the player is within line of sight of the npc.

**Wowhead links:**
https://www.wowhead.com/npc=898/nightbane-worgen

**Comment by UltraNix** [comment]
Works okay.
