### ISSUE TITLE
[ITEM] Totem of Spirits - Moves, but can not be used in Shadowmoon Valley (named area)

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#448]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The Totem of Spirits item cannot be used in any area primarily named "Shadowmoon Valley". Nearby named areas, such as The Fel Pits, or Coilskar Cistern, the totem can be used. The totem can also move when summoned.
![tos0426](https://user-images.githubusercontent.com/82483575/116185646-a15fd300-a6e7-11eb-946a-b46978457a2a.png)

https://user-images.githubusercontent.com/82483575/116185658-a886e100-a6e7-11eb-8c22-c85be4a303a2.mp4

**How to reproduce:**
During Enraged Spirits of Fire and Earth and/or Enraged Spirits of Water and/or Enraged Spirits of Air, attempt to use the Totem of Spirits in an area named Shadowmoon Valley. Also, once summoned, move around and observe that the totem follows you.

**How it should work:**
The totem should be able to be summoned in areas named Shadowmoon Valley. Additionally, the totem should not move.

**Wowhead links:**
https://www.wowhead.com/item=30094/totem-of-spirits
https://www.wowhead.com/quest=10458/enraged-spirits-of-fire-and-earth
https://www.wowhead.com/quest=10480/enraged-spirits-of-water
https://www.wowhead.com/quest=10481/enraged-spirits-of-air

**Comment by UltraNix** [comment]
Totem can be used only in The Fel Pits.
