### ISSUE TITLE
Blackrock Depths donjon

### ISSUE THREAD

**Issue by larken999** [GameFreedomGG/Maelstrom#451]
No problem at thw beginning of donjon , start at the inn and domicil zone of the donjon for the quest "The Grim Guzzler" and "The Heart of the Mountain"

1st one the boss Hurley Blackbreath don't pop when we broke the barrel on the zone

2nd after opening all the chest at the treasure cell, the named don't pop and we can get the secret trap for quest item.

**How to reproduce:**

1st clean donjon normaly to the grim guzzler zone try to break the barrel at the left room and nothing happend

2nd loot 14 relic key on donjon and open the 14 door at treasure room.

**How it should work:**

1st the boss may pop after break the 3 barrel

2nd the named pop after open the 14 door

**Comment by HerodDev** [comment]
Add wowhead links

**Comment by larken999** [comment]
https://fr.wowhead.com/quest=27571/le-sinistre-%C3%A9cluseur

https://fr.wowhead.com/quest=27596/le-c%C5%93ur-de-la-montagne

**Comment by UltraNix** [comment]
Fixed.
