### ISSUE TITLE
[DUNGEON] The Deadmines - Instance Portal not visible, but works

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#456]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The dungeon portal for The Deadmines is not visible, but does work when you walk where it should be.
![dea0428](https://user-images.githubusercontent.com/82483575/116473214-86eb3e00-a83c-11eb-9c4a-c8c7d6c54da9.png)

**How to reproduce:**
Navigate to the entrance portal for The Deadmines, and observe that the portal is not visible.

**How it should work:**
The portal should be visible as a standard normal dungeon portal.

**Wowhead links:**
https://www.wowhead.com/the-deadmines

**Comment by HerodDev** [comment]
From other issue:

> ![WoWScrnShot_043021_124918](https://user-images.githubusercontent.com/66841484/116703342-7799fb00-a9ca-11eb-92c9-89803074585e.jpg)
> ![WoWScrnShot_043021_124943](https://user-images.githubusercontent.com/66841484/116703351-79fc5500-a9ca-11eb-9bf6-4e81e9270ee3.jpg)
> ![WoWScrnShot_043021_125136](https://user-images.githubusercontent.com/66841484/116703360-7bc61880-a9ca-11eb-87a8-780e455a93a6.jpg)
> ![WoWScrnShot_043021_125226](https://user-images.githubusercontent.com/66841484/116703368-7d8fdc00-a9ca-11eb-8f6b-1b7ee87539d9.jpg)
> 
> **Description:**
> Mobs walking beneath the terrain, "Alliance Mage" and "Alliance Hunter" in "A Vision of the Past" are standing inside each other. And the portal to Deadmines is also missing.
