### ISSUE TITLE
[QUEST] AHHHHHHHHHHHH! AHHHHHHHHH!!! - Colonel Troteman not located in Shalewind Canyon

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#458]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
The quest AHHHHHHHHHHHH! AHHHHHHHHH!!! is currently available from Colonel Troteman, but not at the intended location. Troteman should be located in Shalewind Canyon at roughly 77.2, 65.8. Currently, however, Colonel Troteman is instead located at Keeshan's Post, at roughly 63.0, 38.0

**How to reproduce:**
Complete The Grand Magus Doane at John J. Keeshan in Shalewind Canyon. Observe that there are no nearby quests to take. Travel to Keeshan's Post, and observe that Colonel Troteman is offering a quest in this location.

**How it should work:**
Colonel Troteman should be located at 77.2, 65.8 in Shalewind Canyon, Redridge Mountains.

**Wowhead links:**
https://www.wowhead.com/quest=26708/ahhhhhhhhhhhh-ahhhhhhhhh
https://www.wowhead.com/quest=26694/the-grand-magus-doane
https://www.wowhead.com/npc=43733/colonel-troteman

**Comment by Ahumaya** [comment]
Please note that this quest also automatically completes when accepted.

**Comment by UltraNix** [comment]
He's in both locations and it's okay.
