### ISSUE TITLE
[NPC]Ashenvale Bowman

### ISSUE THREAD

**Issue by TheRealTangsten** [GameFreedomGG/Maelstrom#464]
**Description:** Ashenvale Bowman does not attack, only aggroes. It does not follow the player either when he's supposedly out of their range.
**EDIT:** This is only partially true; I've had them not attacking me the first time I attacked them, but the second time around when they respawned they started using their ranged attacks and abilities, although not all of them.

**How to reproduce:** Go to The Mor'Shan Rampart, aggro an Ashenvale Bowman.

**How it should work:** They should fight back, and move when you are out of range.

**Wowhead links:**https://www.wowhead.com/npc=33195/ashenvale-bowman

**Video recording:** https://youtu.be/OxYOQG-efo8

**Comment by Afgann** [comment]
fixed
