### ISSUE TITLE
[Profession]: Lua Error when hit 75 herb skill

### ISSUE THREAD

**Issue by LukaszSzczygielski** [GameFreedomGG/Maelstrom#465]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Lua Error when hit 75 herb skill

**How to reproduce:**
Skill herb

**How it should work:**

**Wowhead links:**

![WoWScrnShot_042921_194618](https://user-images.githubusercontent.com/81674221/116595560-bb85f500-a923-11eb-9164-7a02a362d604.jpg)

**Comment by LukaszSzczygielski** [comment]
Now I noticed that i can't use Lifeblood.
Also I get error whenever I open professions tab.
![WoWScrnShot_042921_194854](https://user-images.githubusercontent.com/81674221/116595765-f12ade00-a923-11eb-851f-7e630db76b86.jpg)

**Comment by LukaszSzczygielski** [comment]
Learned herb.
Now I have 2 Herb Gathering skills. Still can use Lifeblood by /cast command  (even tho its not working as before).
![WoWScrnShot_042921_195559](https://user-images.githubusercontent.com/81674221/116596651-ee7cb880-a924-11eb-9dfc-9784cfba9d2e.jpg)

**Comment by Xenothang** [comment]
Double icon like on the last Pic happens on every Profession if you learn the next rank

**Comment by UltraNix** [comment]
Cannot reproduce it.
