### ISSUE TITLE
Hogger missing abilities

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#470]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Hogger misses 3 of his abilities.
"Head Butt" "Pierce Armor" and "Rushing Charge"

**Wowhead links:**
https://cata-twinhead.twinstar.cz/?npc=448#abilities

**Comment by UltraNix** [comment]
These are classic abilities.
