### ISSUE TITLE
Priest Glyph of Pain Suppression

### ISSUE THREAD

**Issue by Maxillo** [GameFreedomGG/Maelstrom#479]
A glyph for priest named "Glyph Of Pain Suppression" doesnt work.

It must allow Pain Suppression spell to be cast while stunned.

My character is a disc priest and i'm doing pvp and it's tested both battlegrounds,arenas and 1v1 duels.

Well it should work when you're in a stun situation like rog kidney or paladin hammer of justice etc. It cant work if you're in a silence or a druid cc like Cyclone etc.

http://wowhead.com/

**Comment by UltraNix** [comment]
Works okay.
