### ISSUE TITLE
"And Last but Not Least... ***" - Chainquest

### ISSUE THREAD

**Issue by empantv** [GameFreedomGG/Maelstrom#48]
**Description:**
Quest Bugged

**How to reproduce:**
The ads which i let lose from the cages in Redridge Mountains wont help u attack the "bosses" in the quest chain up the cavern in the north.

**How it should work:**
They should help u during the fight

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=26562/and-last-but-not-least-danforth

**Comment by UltraNix** [comment]
Everything works okay.
