### ISSUE TITLE
[NPC] Avrus Illwhisper - Doesn't Exist

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#484]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Avrus Illwhisper NPC doesn't appear to exist. He should be at roughly 59.0 59.8 in Ashenvale.
![avr0502](https://user-images.githubusercontent.com/82483575/116826145-30da0b80-ab58-11eb-9419-016c2155b73d.png)

**How to reproduce:**
Navigate to roughly 59.0 59.8 in Ashenvale. Observe that the Avrus Illwhisper NPC is not there. Please note that I have completed the quests A Trip to the Moonwell and He Who Would Be Forgiven, so this may be a phasing issue.

**How it should work:**
The Avrus Illwhisper NPC should be available as a quest giver.

**Database links:**
https://www.wowhead.com/npc=34335/avrus-illwhisper
https://www.wowhead.com/quest=13919/a-trip-to-the-moonwell
https://www.wowhead.com/quest=13921/he-who-would-be-forgiven

**Comment by UltraNix** [comment]
This NPC does exist.

**Comment by UltraNix** [comment]
NPC is invisible after quest "In the Hands of the Perverse"
Tested - works okay.
