### ISSUE TITLE
[quest] Back to the Orphanage

### ISSUE THREAD

**Issue by Tolunay2021** [GameFreedomGG/Maelstrom#485]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I have done the quest chain of orphan in shattrat (dranei orphan) but when I completed 'Time to Visit the Caverns' & 'The Seat of the Naaru' the orphan did not give me the ending quest 'Back to the Orphanage' so I can not complete and get my pet

**How to reproduce:**
do quest 'Time to Visit the Caverns' & 'The Seat of the Naaru' 

**How it should work:**
the orphan should give the quest 'Back to the Orphanage'

**Database links:**
https://www.wowhead.com/childrens-week-guide

**Comment by UltraNix** [comment]
You also need https://tbc.wowhead.com/quest=10968/call-on-the-farseer.
