### ISSUE TITLE
[QUEST] Bombs Away: Windshear Mine! - Quest not provided remotely

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#488]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest Bombs Away: Windshear Mine! is not provided remotely after completing Burn, Baby, Burn!.

**How to reproduce:**
Complete the quest Burn, Baby, Burn! while in Stonetalon Mountains.

**How it should work:**
After completing Burn, Baby, Burn!, this quest should be provided remotely.

**Database links:**
https://www.wowhead.com/quest=25640/bombs-away-windshear-mine
https://www.wowhead.com/quest=25622/burn-baby-burn

**Comment by HerodDev1** [comment]
Fixed in rev 25.

**Comment by UltraNix** [comment]
Works okay.
