### ISSUE TITLE
Arthas is the new leeroy jenkins 

### ISSUE THREAD

**Issue by MadeinNoxus** [GameFreedomGG/Maelstrom#507]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Arthas for a reason decides to run it down in the 2nd phase of the map without stop and dies. ( 2 phase is the one behind the bookshelf he waits here until you talk to him, he takes a small amount of time for rest and literally run it down).

**How to reproduce:**
Reach the 2nd phase of the culling of stratholme and talk to arthas.

**How it should work:**
Arthas should kill one enemy and go back to the place he comes until everything is clear and he decides to fight mal'ganis.

**Database links:**
https://www.wowhead.com/npc=26499/arthas

**Comment by UltraNix** [comment]
Cannot reproduce it.
