### ISSUE TITLE
Blink from mage can get you up on roof

### ISSUE THREAD

**Issue by Pallaladin** [GameFreedomGG/Maelstrom#51]
**Description:**

i used blink in front of a kolkarr camp and it took me on the roof of a tent

**How to reproduce:**

use blink near a building with a roof

**How it should work:**

it should tell me no space to use blink or teleport me near the house not on the house :)

![image](https://user-images.githubusercontent.com/51074371/114381218-2943ca00-9b8b-11eb-88cc-0cb4c59e9ede.png)

**Comment by UltraNix** [comment]
Fixed
