### ISSUE TITLE
[QUEST] Against the Legion - Quest is missing

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#515]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest Against the Legion is not currently in the game.

**How to reproduce:**
Complete the quest Altruis. Observe that only 2 quests are made available, instead of 3. The third, missing quest is Against the Legion.

**How it should work:**
Against the Legion should be offered after completing Altruis.

**Database links:**
https://www.wowhead.com/quest=10641/against-the-legion
https://www.wowhead.com/quest=10689/altruis

**Comment by UltraNix** [comment]
Works okay.
