### ISSUE TITLE
[QUEST] Planting the Banner - Default quest marker does not show correct location

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#518]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest marker for Planting the Banner does not correctly identify where to first get the Bladespire Clan Banner needed for the quest. This item must be acquired before the second objective can be completed.
![ptb0510](https://user-images.githubusercontent.com/82483575/117743757-0548c800-b1cd-11eb-96df-9943396f506d.png)

**How to reproduce:**
Accept the quest Planting the Banner. Observe the default quest marker.

**How it should work:**
The quest indicator should show over the Bladespire Hold, indicating that the Bladespire Clan Banner must be collected first.

**Database links:**
https://www.wowhead.com/quest=10518/planting-the-banner

**Comment by UltraNix** [comment]
It's okay - this blizz.
