### ISSUE TITLE
The Deadmines Bug List

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#520]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

![aa](https://user-images.githubusercontent.com/66841484/117880500-7ad59680-b2a8-11eb-84db-6a26e536c455.png)
https://www.wowhead.com/npc=47162/glubtok#abilities;mode:normal
Glubtoks auto attack range is too long. 
He is also missing his AoE freeze ability as he starts his second phase while shooting missiles on the ground as seen here:
https://youtu.be/UWSOU2yPPS8?t=266
He is also only shooting one missile at a time, in the video he is shooting multiple.

Helix Geartbreaker
https://www.wowhead.com/npc=47296/helix-gearbreaker#abilities;mode:heroic
When his Oaf dies he is supposed to jump around on random players necks, a bit hard to see but:
https://www.youtube.com/watch?v=UWSOU2yPPS8&t=275s

![gob](https://user-images.githubusercontent.com/66841484/117881376-78277100-b2a9-11eb-8ca2-7f090a2f3f9e.png)
Mine Bunny
https://cata-twinhead.twinstar.cz/?npc=48338
Is supposed to patrol the area but just stands still, tray is also not in her hand & she just ignores you as you kill her.

![gobb](https://user-images.githubusercontent.com/66841484/117881646-c63c7480-b2a9-11eb-81fb-3ab598a88553.png)
Mining Monkey
https://cata-twinhead.twinstar.cz/?npc=48442
If you free them they're supposed to help you shortly before disappearing. And if you attack them they also just ignore you, can't attack.

![miner johns](https://user-images.githubusercontent.com/66841484/117881862-04d22f00-b2aa-11eb-97b6-74c3fbae23fc.png)
Miner Johnson
https://www.wowhead.com/npc=3586/unused-4-x-miner-johnson
https://cata-twinhead.twinstar.cz/?npc=3586
^Both databases say he is not supposed to be in Cata. His items also already drops from other bosses.

https://youtu.be/sWTAGVRJ0oY?t=125
^When you open this area there is supposed to be some fleeing NPCs and corpses laying around but it is all empty.

![def](https://user-images.githubusercontent.com/66841484/117882147-537fc900-b2aa-11eb-8eb5-3a686bd3c741.png)
Defias Reaper
https://www.wowhead.com/npc=47403/defias-reaper#abilities;mode:normal
Missing all his abilities, you also can't enter it as a vehicle when it gets low, and his auto attack damage is only 1.

![fhs](https://user-images.githubusercontent.com/66841484/117882552-c0935e80-b2aa-11eb-9ed4-111808574b48.png)
Quartermaster Lewis
https://cata-twinhead.twinstar.cz/?npc=491
This guy is not supposed to be here. Also don't think those whisps should be either.

![fly](https://user-images.githubusercontent.com/66841484/117882836-04866380-b2ab-11eb-976a-36d72fc05ea7.png)
There is multiple spawns of this guy, one which just flies across the room and through the mountain when you reach the higher parts of the boat. I also saw him when I took the starting quests in the beginning running through the wall.

**Comment by cloud1121** [comment]
Adding to list:
Glubtok Auto attacks in phase 2.
Barrels will auto attack players. 
Foe Reaper 5000 does 6k Damage to players when boss phase starts. 
https://www.wowhead.com/spell=88481/overdrive

**Comment by Ahumaya** [comment]
Adding to list:

There are two duplicate Goblin Teleporters in the Furnace room.
![dgt0531](https://user-images.githubusercontent.com/82483575/120249308-0a36ef80-c240-11eb-9024-9df783ddff08.png)

The Foe Reaper 5000 can be skinned.
![dfr0531](https://user-images.githubusercontent.com/82483575/120249322-17ec7500-c240-11eb-9384-a55bcf078c17.png)

**Comment by UltraNix** [comment]
@WarlordXecc 
```
https://www.wowhead.com/npc=47162/glubtok#abilities;mode:normal
Glubtoks auto attack range is too long.
He is also missing his AoE freeze ability as he starts his second phase while shooting missiles on the ground as seen here:
https://youtu.be/UWSOU2yPPS8?t=266
He is also only shooting one missile at a time, in the video he is shooting multiple.
```
1. His auto attack range is okay to me.
2. his freeze ability for me works okay - it always worked okay when switch to 2nd phase.
3. Number of missiles dependent on players count.

**Comment by UltraNix** [comment]
@WarlordXecc All of the reported bugs here should be fixed. Once PTR is updated (I will let you know about it), please restest the whole instance once again and write here any bug you will find. Don't forget about the heroic mode.
