### ISSUE TITLE
Wailing Caverns Bug List

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#522]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

![WoWScrnShot_051121_173358](https://user-images.githubusercontent.com/66841484/117885286-f6861200-b2ad-11eb-9ab0-4f78babded81.jpg)
Pretty sure this chest is not supposed to be here.

![WoWScrnShot_051121_173509](https://user-images.githubusercontent.com/66841484/117885312-fede4d00-b2ad-11eb-8219-aa8047bbff64.jpg)
https://cata-twinhead.twinstar.cz/?npc=3653
Kresh is supposed to patrol the area but just standing still here.

![cobrahn](https://user-images.githubusercontent.com/66841484/117885582-4d8be700-b2ae-11eb-8fa1-1d873d3305c7.png)
https://www.wowhead.com/npc=3669/lord-cobrahn#abilities;mode:normal
I am like 99% sure Cobrahn is not supposed to be casting spells when in his Serpent Form. Also he is missing his Poison ability.

https://www.wowhead.com/npc=3654/mutanus-the-devourer#abilities;mode:normal
Mutanus the Devourer
During the event to summon him, a couple of the mobs does not automatically move towards you and two of them does not even do it if you attack them since they can't find a path.
Also his ability "Naralex's Nightmare" while it does technically work, it is supposed to make you hostile to your party member allowing them to attack you to break it but it does not.

**Comment by cloud1121** [comment]
Adding to list: 
Disciple of naralex moves about 5m then stands still. Unable to finish dungeon
