### ISSUE TITLE
Gnomeregan Bug List

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#524]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

![WoWScrnShot_051121_185041](https://user-images.githubusercontent.com/66841484/117886913-32ba7200-b2b0-11eb-9862-f7e47a830a57.jpg)
https://cata-twinhead.twinstar.cz/?npc=44556
Murd Doc is supposed to give you a quest but does not.

https://cata-twinhead.twinstar.cz/?npc=7998
Blastmaster Emi Shortfuse event is pretty scuffed, her movements and position seems very off and I know there are some rocks which are supposed to fall down at one point which does not happen.

https://cata-twinhead.twinstar.cz/?npc=7079
Viscous Fallout should patrol the area but just stands still.

![WoWScrnShot_051121_190244](https://user-images.githubusercontent.com/66841484/117887114-7e6d1b80-b2b0-11eb-8d7a-f93e6be7400a.jpg)
https://cata-twinhead.twinstar.cz/?npc=44560
B.E Barechus is also supposed to give you a quest, but idk if he just doesn't because the first guy does not give you the first part of "The G-Team" chain.

![WoWScrnShot_051121_192515](https://user-images.githubusercontent.com/66841484/117887229-ac526000-b2b0-11eb-97ad-42c2e61dcf8c.jpg)
Last Boss Door is missing, so are all the red buttons in this room and there are kind of no bombs spawning either. Some seem to just be standing around being buggy.
![bomb](https://user-images.githubusercontent.com/66841484/117887395-eb80b100-b2b0-11eb-82f4-1eca9acbe8ac.png)

**Comment by UltraNix** [comment]
`https://cata-twinhead.twinstar.cz/?npc=44556
Murd Doc is supposed to give you a quest but does not.`
https://cata-twinhead.twinstar.cz/?quest=26943 is the previous quest.
