### ISSUE TITLE
Razorfen Kraul Bug List

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#526]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

https://cata-twinhead.twinstar.cz/?npc=4440#abilities
Razorfen Totemic works fine but the Earthgrab Totem he summons has like 3000hp instead of 15.

![WoWScrnShot_051121_202435](https://user-images.githubusercontent.com/66841484/117888953-13711400-b2b3-11eb-8c0f-9495ad7a9056.jpg)
https://cata-twinhead.twinstar.cz/?npc=4420
Overlord Ramtusk does not drop any items.

![WoWScrnShot_051121_202959](https://user-images.githubusercontent.com/66841484/117889086-40252b80-b2b3-11eb-8041-7633bb8a85e4.jpg)
https://cata-twinhead.twinstar.cz/?npc=4422
Agathelos the Raging is supposed to run out of his area when you kill the two guys to open the portal into his cave but he just stands in his place, all abilities seem to work fine tho.

![WoWScrnShot_051121_203247](https://user-images.githubusercontent.com/66841484/117889271-8d090200-b2b3-11eb-9c6f-36aa70161d24.jpg)
https://cata-twinhead.twinstar.cz/?npc=4508
Willix the Importers escort quest does not work, after picking it up he just stands there.

**Comment by cloud1121** [comment]
Adding: 
1. Getting Rested Status in Razorfen Kraul
2. Last boss Charlga Razorflank only drops quest item, nothing else off loot table
