### ISSUE TITLE
Hinterlands zone bug ?

### ISSUE THREAD

**Issue by larken999** [GameFreedomGG/Maelstrom#533]
**Description:**
Hinterland zone bug at entrance, when i pass the arathi to hinterland tunnel to get to ally base, i have server crash with my lv 31 character and the crash reproduce each time i try to log it , Xecc unlock me and i avoid the zone, not sure if the zone be bug or just unlucky , don't know if ppl make quest here.

**How to reproduce:**
Pass the tunnel from arathi to hinterland and move in the zone

**How it should work:**
Suppose to don't crash the serv , maybe phasing bug i don't know

**Database links:**
https://fr.wowhead.com/the-hinterlands#show:vignettes
![WoWScrnShot_051221_153159](https://user-images.githubusercontent.com/82697607/117983442-3f35dd80-b337-11eb-8b5e-1e3bd042785a.jpg)

**Comment by UltraNix** [comment]
Cannot reproduce it.
