### ISSUE TITLE
[QUEST] Dr. Boom! - Does not work as expected.

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#535]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, Dr. Boom engages the player in direct combat.
![doo0512](https://user-images.githubusercontent.com/82483575/118052794-fab33d80-b348-11eb-99e4-795d939f7b33.png)

**How to reproduce:**
Attempt to engage Dr. Boom in combat using the Boom's Doom item.

**How it should work:**
Dr. Boom should remain in the same location, continuously spawning new bomb bots.

**Database links:**
https://www.wowhead.com/quest=10221/dr-boom
https://www.wowhead.com/npc=20284/dr-boom

**Comment by UltraNix** [comment]
Cannot reproduce it.
