### ISSUE TITLE
[QUEST] Rediscovering Your Roots - Razorthorn Ravagers do not become pets

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#542]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Rediscovering Your Roots, the player needs to kill Razorthorn Flayers to obtain Razorthorn Flayer Glands. Once obtained, the player needs to use these glands on the nearby Razorthorn Ravagers to temporarily tame them to hunt for Razorthorn Roots. Currently, using the Razorthorn Flayer Glands does not tame the Ravagers.

**How to reproduce:**
Accept the quest Rediscovering Your Roots. Head to Razorthorn Rise. Kill Razorthorn Flayers until a Razorthorn Flayer Gland drops. Use the Razorthorn Flayer Gland on a nearby Razorthorn Ravager. Observe that the Ravager is not tamed as your pet.

**How it should work:**
Using a Razorthorn Flayer Gland on a Razorthorn Ravager should tame the ravager as a pet temporarily.

**Database links:**
https://www.wowhead.com/quest=11521/rediscovering-your-roots

**Comment by UltraNix** [comment]
Works okay.
