### ISSUE TITLE
[INSTANCE] The Arcatraz - Void Zones spawned by Zereketh move towards player

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#547]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Void Zones spawned by Zereketh the Unbound in The Arcatraz will follow the player instead of remaining in a static location.

https://user-images.githubusercontent.com/82483575/118341268-07b86400-b4e4-11eb-875a-b0c7c83a9c6d.mp4

**How to reproduce:**
Engage Zereketh the Unbound in Combat. Allow him to cast a Void Zone. Observe that the Void Zone will move on the ground to follow the player.

**How it should work:**
The Void Zones should not move.

**Database links:**
https://www.wowhead.com/npc=20870/zereketh-the-unbound
https://www.wowhead.com/the-arcatraz

**Comment by Afgann** [comment]
fixed
