### ISSUE TITLE
Mob bug

### ISSUE THREAD

**Issue by haysekn** [GameFreedomGG/Maelstrom#550]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Teldrasill, mob quest kill the spider boss LVL 5

**How to reproduce:**
Boss when you hit him he doesn't come to yoy

**How it should work:**
When you hit him the boss shouldn't stuck in his place and you can hit him he must move 
Https://youtu.be/5z9AG-N4qQM

**Database links:**

**Comment by UltraNix** [comment]
No links/no info.
