### ISSUE TITLE
[CRASH] Ruins of Gilneas City - Entering causes server to crash

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#555]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Found on my character Fun. On entering Gilneas City in the Ruins of Gilneas, the server will begin to crash.
![WoWScrnShot_051721_094528](https://user-images.githubusercontent.com/82483575/118508648-fc885280-b6f4-11eb-8461-923155a65699.jpg)

**How to reproduce:**
Enter Gilneas City in the Ruins of Gilneas. Observe that the server crashes.

**How it should work:**
It should not crash.

**Database links:**
https://www.wowhead.com/zone=5351/ruins-of-gilneas-city

**Comment by UltraNix** [comment]
Cannot reproduce it.
