### ISSUE TITLE
Group queueing RDF crashes server

### ISSUE THREAD

**Issue by cloud1121** [GameFreedomGG/Maelstrom#572]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When queueing for Random Dungeon finder in a group, upon queue, crashes the server. 

**How to reproduce:**
Group of 2 or more queue for a dungeon, when dungeon is ready and accepted, server will crash.

**How it should work:**
No server crash, join dungeon.

**Database links:**

**Comment by UltraNix** [comment]
Cannot reproduce it.
