### ISSUE TITLE
[HUNTER] Auto Shot - Auto Shot does not continue during use of other abilities

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#576]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
As identified by Enider/Vantrith and confirmed by myself, Auto Shot does not continue while using other abilities, such as Explosive Shot, Serpent Sting, Steady Shot, Kill Command, or others.

**How to reproduce:**
On a Hunter, attack an enemy creature (a Combat Dummy works), and continue using abilities such as those listed above, especially Steady Shot. Observe as, with using abilities as often as you can, an Auto Shot will never fire.

**How it should work:**
Per the comments on the wowhead links below, Auto Shot should continue to "cast" while using other abilities, and queue while the hunter is actively using other abilities. Immediately upon finishing any other ability, if an Auto Shot is successfully queued, the shot should fire.

**Database links:**
https://www.wowhead.com/spell=75/auto-shot
https://www.wowhead.com/spell=56641/steady-shot

**Comment by xHAGENx** [comment]
+ Hunter should also use auto shot during cast steady/cobra shot.

**Comment by xHAGENx** [comment]
![image](https://user-images.githubusercontent.com/90351303/132575050-21cd3531-9e1f-4108-929c-1e07555b17be.png)

**Comment by UltraNix** [comment]
Everything works okay.
