### ISSUE TITLE
Blackrock Depths Arena

### ISSUE THREAD

**Issue by cloud1121** [GameFreedomGG/Maelstrom#580]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
NPC to start event walks to center of room and gets stuck, event cannot be completed. Current workaround is to portal out and back in to skip the encounter. 
https://imgur.com/a/KgjLlmr

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
