### ISSUE TITLE
DK Intro: Scarlet Armies Approach doesn't grant Talent Point

### ISSUE THREAD

**Issue by cloud1121** [GameFreedomGG/Maelstrom#591]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When turning in **Scarlet Armies Approach** system message says you gain one talent point but it is not added to Talent sheet

**How to reproduce:**
Turn in Quest

**How it should work:**
Grant a talent point

**Database links:**
https://wowpedia.fandom.com/wiki/Scarlet_Armies_Approach...

**Comment by UltraNix** [comment]
Works okay.
