### ISSUE TITLE
DK Intro Final Quest: The Light of Dawn Bug List (incompletable)

### ISSUE THREAD

**Issue by cloud1121** [GameFreedomGG/Maelstrom#593]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

When starting the event, the ghouls freeze for about 15 seconds into their path
![light of dawn event pathing](https://user-images.githubusercontent.com/77916637/120386423-73b90b80-c2dd-11eb-89dc-49d02d9895bf.PNG)

After the 15 seconds, rest of the NPC's join, and float into the area
![comedy](https://user-images.githubusercontent.com/77916637/120386468-82072780-c2dd-11eb-9890-e8179c9b45f8.PNG)

Once arrived, no enemy NPC's join. Making it Incompletable
![Light of dawn event pathing 2](https://user-images.githubusercontent.com/77916637/120386501-91867080-c2dd-11eb-96d4-eea25c37cbfd.PNG)

https://streamable.com/7hlr0t

**Comment by UltraNix** [comment]
Quest works itself. The problem with movement is a core general bug.
