### ISSUE TITLE
[OBJECT] Stack of Barrels in Valley of Kings - Draw distance set too low

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#595]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Draw distance of the Stack of Barrels outside the Bunker in the Valley of Kings is set low enough that the camera zoom and cull the object. Please see video below.

https://user-images.githubusercontent.com/82483575/120408795-5b64e300-c315-11eb-8ffd-f6d027027568.mp4

**How to reproduce:**
Navigate to roughly 23.4 75.0 in Loch Modan. Head outside of the Bunker. Observe the stack of barrels. Move the camera and adjust zoom to see the draw distance cull the barrels if the camera gets too far away, even if the player is standing on the stack.

**How it should work:**
The barrel draw distance should be higher, matching the nearby objects.

**Database links:**

**Comment by UltraNix** [comment]
Clientside.
