### ISSUE TITLE
[PROFESSION] Archaeology - Lakeridge Highway Fossil Bank - Digsite does not despawn.

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#598]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, the Lakeridge Highway Fossil Bank digsite does not properly despawn, and the player can continue to attempt to find fossils. However, this process causes an error to appear in the chat window stating "You Occured Error! Digsite removed and genereate new one." (sic). Please note that this error message also has grammatical errors.
![arc0602](https://user-images.githubusercontent.com/82483575/120548435-f57d6780-c3b7-11eb-9cfc-073d86ffe522.png)

**How to reproduce:**
Perform Archaeology in Eastern Kingdoms until the Lakeridge Highway Fossil Bank spawns. Find all 3 finds, and then observe if the digsite has despawned. If it has not, attempt to Survey again.

**How it should work:**
The digsite should properly despawn after finding the 3rd find.

**Database links:**
N/A

**Comment by UltraNix** [comment]
Can't reproduce it.
