### ISSUE TITLE
Ranger Glynda Nal'Shea floats when she pats

### ISSUE THREAD

**Issue by nealliu** [GameFreedomGG/Maelstrom#599]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Ranger Glynda Nal'Shea does not walk when she pats but floats

**How to reproduce:**
Watch her pat in Lor'danel

**How it should work:**
Should walk like normal npc.

**Database links:**
![image](https://user-images.githubusercontent.com/3328456/120588313-d698c880-c3eb-11eb-8691-4643c01c63ca.png)

**Comment by Afgann** [comment]
works fine
