### ISSUE TITLE
The Nexus(Normal) Bug List

### ISSUE THREAD

**Issue by cloud1121** [GameFreedomGG/Maelstrom#603]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**Spawn Location**
When using RDF you port in below the map and fall far down. Confirmed with xecc the map exists, but spawn location is incorrect. 

**Grand Magus Telestra**
When making mirror images, not using any casts, only meleeing. 

**Anamolus**
*Chaotic Rift* - Is not the correct ID, using Infernal model instead of rift model. 

**Ormorok the Tree-Shaper**
Adds that patrol around are not patrolling
Ormorok has movements of a world enemy mob, patrolling in a small motion

**Keristrasza**
Tail Swipe is larger than a cone, getting swiped from side of dragon. 

**Adds**

*Crazed Mana Wraith* Fluctuating levels from 65-80, should be closer to dungeon level of 70-73

*Crystalline Frayer* Fluctuating levels from 65-80, should be closer to dungeon level of 70-73

https://cata-twinhead.twinstar.cz/?zone=4265

**Comment by Afgann** [comment]
fixed
