### ISSUE TITLE
[Quest] To the Rescue!

### ISSUE THREAD

**Issue by Zube18** [GameFreedomGG/Maelstrom#605]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
In the case the alliance nightelf defenders are still alive with 1HP, the kodo will stop in front of the adds and stop moving

**How to reproduce:**
Dont kill the alliance guards in front of the wall.

**How it should work:**
The kodo should move trough them. (normally the horde guards should kill the nightelfs invaders)

**Database links:**
https://www.wowhead.com/quest=13712/to-the-rescue

**Comment by UltraNix** [comment]
Everything works okay.
