### ISSUE TITLE
[Quest] Fel Orc Scavengers

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#611]
Description: The mob 'Bonechewer Scavenger' does not give quest credit for the named quest. EDIT: After further testing, some of the spawns of Bonechewer Scavenger will give credit, and others will not. It is unclear why, they are interspersed through the entire line of the ravine on the alliance side, ones that give credit and ones that do not.

How to reproduce: Accept quest Fel Orc Scavengers at the destroyed tower outside Honor Hold and kill Bonechewer Scavengers.

How it should work: Should award 1 credit when killing Bonechewer Scavenger mobs, every time. Shown in the link below at around 0:55, when he starts killing mobs.

Database links: 
https://www.wowhead.com/quest=10482/fel-orc-scavengers
https://www.youtube.com/watch?v=z6WA69bNbxY&ab_channel=SipderSipder

**Comment by Godmatik** [comment]
You don't get credit if your pet lands the killing blow.

**Comment by Afgann** [comment]
works correctly
