### ISSUE TITLE
[QUEST] As the Crow Flies

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#613]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** When using the quest item 'Stormcrow Amulet' for the quest 'As the Crow Flies', it is supposed to transform your character model into a crow, to fly around. I tried twice and each time I used it, it did not transform me into a crow but instead just sent my character model sailing off in a sitting animation, like I was mounted/riding a broom from the halloween event.

**How to reproduce:** Accept the quest 'As the Crow Flies' and use the quest item generated 'Stormcrow Amulet'

**How it should work:** The character model should be converted into the graphic of a crow for the duration of the flight.

**Database links:**
![image](https://user-images.githubusercontent.com/45482752/120942109-dea28200-c6e3-11eb-9972-b49a500fb55f.png)

**Comment by HerodDev** [comment]
@Enider890 remember to add wowhead/other database links
https://www.wowhead.com/quest=9718/as-the-crow-flies
