### ISSUE TITLE
[QUEST] Guardian of the Monument

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#616]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** When accessing the Apexis Monument (The large shards in the middle) and selecting the dialogue option 'Replace an Apexis Shard, and begin!' nothing happens. I had gathered 51 apexis crystals and still no reaction.

**How to reproduce:** Accept the quest Guardian of the Monument and find the large crystal to 'open' it and select its dialogue.

**How it should work:** It should begin the 'Simon Says' type minigame with the colored buttons to summon an Apexis Guardian to be killed, in order to loot the item Apexis Guardian's Head for quest credit.

**Database links:** https://www.youtube.com/watch?v=wS4hBz8V-iQ&ab_channel=MichaSMichaS

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=11059/guardian-of-the-monument

**Comment by UltraNix** [comment]
Works okay.
