### ISSUE TITLE
[QUEST] Potential for Brain Damage = High

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#617]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** The quest Potential for brain Damage = High is missing many of the quest credit spawns. You are supposed to kill mob 'Ethereum Relay' for the item it drops, but they only spawn along the water. Per the linked video, there are supposed to be many more spawns all around the land and questing area. As it is now, I only found 2/3 of the quest credit and had to wait for respawns. Potential for bottlenecking.

**How to reproduce:** Accept the quest Potential for Brain Damage = High at the Ethereum Staging Grounds and kill an Ethereum mob. Use the item Ethereum Essence to activate sight of the quest credit mobs.ddd

**How it should work:** There should be many more spawns of the credit-giving NPC. There are currently only 10 and the quest requires 15 items looted. That, or it would probably be fine if the required amount of loot/items was reduced to 5.

**Database links:** https://www.youtube.com/watch?v=2M-PFuNikYk&ab_channel=MichaSMichaS

**Comment by HerodDev** [comment]
@Enider890 please add also everytime link to wowhead or other database like this one:
https://www.wowhead.com/quest=10385/potential-for-brain-damage-high

**Comment by UltraNix** [comment]
Mobs count seems to be okay.
