### ISSUE TITLE
Quest The Day that deathwing came

### ISSUE THREAD

**Issue by Klohunt** [GameFreedomGG/Maelstrom#619]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you pickup quest nothing happens while you should get a phase and enter a vehicle like state

**How to reproduce:** 
pickup quest

**How it should work:**
when you accept the quest you should be put in a vehicle like state of the person that you got the quest from.

**Database links:**
https://www.wowhead.com/quest=27713/the-day-that-deathwing-came#see-also

**Comment by UltraNix** [comment]
Fixed.
