### ISSUE TITLE
[QUEST] Honor Challenge

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#623]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** (Minor, quest is completable) When using the item Challenge Flag, it does not visibly spawn a flag in-game. Also, it does not aggro one of the enemies, and instead just debuffs all enemies in range of the flag where clicked to give credit when killed normally.

**How to reproduce:** Accept the quest Honor Challenge from The Shadow Vault and use Challenge Flag at the Savage Ledge on a Mjordin Combatant. View results.

**How it should work:** It should flag the enemy for combat and cause it to aggro to the player after a moment, and a flag should visibly appear.

**Database links:** https://cata-twinhead.twinstar.cz/?quest=12939

**Comment by Afgann** [comment]
fixed
