### ISSUE TITLE
[PROFESSION]Titanium Vein

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#624]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Sometimes does not grant skill increase despite being orange/guaranteed

**How to reproduce:** Mine a Titanium Vein within 450-475 mining

**How it should work:** Should grant +1 skillup every time when in the orange/guaranteed levels.

**Database links:** https://cata-twinhead.twinstar.cz/?object=191133

**Comment by UltraNix** [comment]
It's Blizzlike.
