### ISSUE TITLE
[QUEST]Shadow Vault Decree

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#625]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Cannot use Shadow Vault Decree to engage combat with Thane Ufrang the Mighty

**How to reproduce:** Accept quest Shadow Vault Decree and run to Thane Ufrang the Mighty. Use the item, it will state he must be seated and present while he is there.

**How it should work:** The item should cause Thane Ufrang the Mighty to initiate dialogue, stand, and engage the player. 

**Database links:** https://cata-twinhead.twinstar.cz/?quest=12943

![image](https://user-images.githubusercontent.com/45482752/122862611-a0f64980-d2de-11eb-8001-4e1a30124948.png)

**Comment by Afgann** [comment]
fixed
