### ISSUE TITLE
[VEHICLE] [NPC] - Stabled Argent Warhorse and Stabled Quel'dorei Steed - Walk after first starting combat

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#628]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Both the Stabled Argent Warhorse and the Stabled Quel'dorei Steed will walk after first entering combat. This makes mounted combat exceedingly difficult, as you can not get enough space in to use ranged abilities. Toggling run/walk will cause the vehicle to run momentarily before completely stopping.

**How to reproduce:**
Mount a Stabled Argent Warhorse or Stabled Quel'dorei Steed (I was on a Female Night Elf). Once mounted, enter combat, either with a mounted opponent or against a target dummy. Observe that the mount will now only move at a slow walking speed.

**How it should work:**
The mount should run at a high speed at all times unless slowed by a special effect.

**Database links:**
https://www.wowhead.com/npc=33870/stabled-argent-warhorse
https://www.wowhead.com/npc=33843/stabled-queldorei-steed

**Comment by UltraNix** [comment]
Works okay to me.
