### ISSUE TITLE
line of sight bug

### ISSUE THREAD

**Issue by V3n1m** [GameFreedomGG/Maelstrom#63]
**Description:**
example NPC "Armored Battleboar" in Mulgore does stand to close to the wall and is not in line of sight to cast spells on it

**How to reproduce:**
![image](https://user-images.githubusercontent.com/47416114/114402273-f22de280-9ba3-11eb-9691-23ca73b83903.png)

**How it should work:**
enemies in this area should be attackable with spells

**Comment by UltraNix** [comment]
Fixed.
