### ISSUE TITLE
[NPC] Scourged Flamespitter - Model drops from sky, hitbox stays in air

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#630]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Scourged Flamespitter enemies outside of Valiance Keep will appear to fall to the ground when they enter visual range, however their hitbox stays in the sky, and they cannot be melee'd next to their model.
![sfs0622](https://user-images.githubusercontent.com/82483575/122978232-e73dbe00-d35b-11eb-97fa-843b26b8c97b.png)

**How to reproduce:**
Head outside of Valiance Keep in Borean Tundra. Observe that the Scourged Flamespitters fall from the sky. Attempt to engage in melee combat.

**How it should work:**
The Models should stay flying in the air, attached to their hitbox.

**Database links:**
https://www.wowhead.com/npc=25582/scourged-flamespitter

**Comment by UltraNix** [comment]
It loos okay.
