### ISSUE TITLE
[QUEST] Hah... You're Not So Big Now! - Credit not awarded if target already in combat

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#632]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Hah... You're Not So Big Now!, the player must use the item Crafty's Ultra-Advanced Proto-Typical Shortening Blaster on Magmoth Crushers or Mate of Magmothregar. Currently, credit is awarded only if the item is used on a target out of combat AND the effect works. Using the item initiates combat, and the effect is (deliberately) not 100% (this low rate is accurate). If the target is in combat and the item is used, no credit is awarded. Per Wowhead notes, the item may need to be used several times to apply the debuff, but currently if the target is already in combat when the item is used, quest credit will not be awarded on kill.

**How to reproduce:**
While on the quest, engage a Magmoth Crusher in combat. While thus engaged, attempt to use the quest item on the Magmoth Crusher until the debuff is applied. Once applied, kill the Magmoth Crusher and observe that quest credit is not awarded.

**How it should work:**
Quest credit should be awarded as long as the debuff is applied.

**Database links:**
https://www.wowhead.com/quest=11653/hah-youre-not-so-big-now

**Comment by Afgann** [comment]
fixed
