### ISSUE TITLE
[QUEST] Emergency Protocol: Section 8.2, Paragraph D - Crashed Flying Machines have very limited interaction area

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#634]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Many of the Crashed Flying Machines have difficult interaction areas for the Emergency Torch item during the quest. Some only allow the item to be used in the rear right quarter of the machine, and some do not allow usage at all. This makes it difficult to complete the quest.

**How to reproduce:**
While on the quest, attempt to use the Emergency Torch near each of the Crashed Flying Machines in the nearby area.

**How it should work:**
The Emergency Torch should be usable within a reasonable distance at any angle of the Crashed Flying Machine.

**Database links:**
https://www.wowhead.com/quest=11796/emergency-protocol-section-8-2-paragraph-d

**Comment by UltraNix** [comment]
Fixed.
