### ISSUE TITLE
[QUEST] Help Those That Cannot Help Themselves - Cast and Cooldown not triggered.

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#637]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Help Those That Cannot Help Themselves, the player must use the D.E.H.T.A. Trap Smasher on Trapped Mammoth Calf's. Currently, the Cast and Cooldown is not triggered, but quest credit is awarded when the item is used.

https://user-images.githubusercontent.com/82483575/123003777-5249bd80-d379-11eb-9f96-b4a9208b7207.mp4

**How to reproduce:**
During the quest, use the quest item on a Trapped Mammoth Calf. Observe that the Calf is instantly freed, and that no cast or cooldown is triggered.

**How it should work:**
A short cast should occur for swinging the hammer, and then a 5 second cooldown should start.

**Database links:**
https://www.wowhead.com/quest=11876/help-those-that-cannot-help-themselves

**Comment by Afgann** [comment]
fixed
