### ISSUE TITLE
[QUEST] Rescuing Evanor - Event does not trigger as expected

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#640]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Rescuing Evanor, an event should begin that kills the Ascended Mage Hunters on the elevated platform. Additionally, once the player lands on the platform, Evanor should spawn and teleport the character back to the Amber Ledge. Currently, none of this happens, and the player is left stranded on the elevated platform.

**How to reproduce:**
Accept the quest Rescuing Evanor. Observe the events that follow.

**How it should work:**
Once the player has landed, the nearby Ascended Mage Hunters should be dead, and Evanor should spawn after opening the Evanor's Prison object. Once spawned, she should teleport the player to the Amber Ledge.

**Database links:**
https://www.wowhead.com/quest=11681/rescuing-evanor

**Comment by Afgann** [comment]
fixed
