### ISSUE TITLE
[QUEST] The Art of Being a Water Terror

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#641]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** It is possible to enter the vehicle but the Frostbolt is extremely buggy. Very hard to get it to start casting, many times it just doesn't react when pressing the button. It 'fails' (interrupts itself, like when you move during a cast) very frequently (above 99% occurrence in my tries) and the two instances that I got the cast off successfully, it only did ~200 damage. The vehicle in general also seems to behave extremely oddly - Saying 'That spell is not ready yet' when the spells are off cooldown, Spell Reflection does nothing at all.

**How to reproduce:** Accept the quest 'The art of being a water terror' and activate the vehicle.

**How it should work:** The Frostbolt should about 5shot the mobs. The vehicle should be able to regularly cast spells on GCD without being interrupted, and without any issue of being unable to use spells as normal.

**Database links:** https://cata-twinhead.twinstar.cz/?quest=13091

**Comment by Afgann** [comment]
fixed
