### ISSUE TITLE
[QUEST] Find the Ancient Hero

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#642]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** (Minor importance) When Iskalder spawns and the item is used on him, it does not despawn the aggressive Iskalder, so you have two copies - a friendly subdued one, and the other that is still attacking you.

**How to reproduce:** Accept the quest 'Find the Ancient Hero' and interact with the Slumbering Mjordin NPCs until one becomes Iskalder. Use the item on him, and see that both copies are available. I was perfectly fine because of health pool, but this might be an issue for someone that is questing and unexpectedly has to deal with the elite mob's damage.

**How it should work:** Once the item is used, the aggressive Iskalder should despawn and no longer be attacking the player.

**Database links:** https://cata-twinhead.twinstar.cz/?quest=13133

**Comment by Afgann** [comment]
fixed
