### ISSUE TITLE
[QUEST] Aces High! - Wyrmrest Skytalon doesn't work and can spawn infinitely

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#644]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Aces High!, the player is sat on a Wyrmrest Skytalon. Currently, none of the abilities work, including flight.

**How to reproduce:**
Accept the quest Aces High!, then speak with Corastrasza to mount on a Wyrmrest Skytalon. Observe that all abilities are dimmed except the Flight ability, but that the Flight ability doesn't work anyway.

**How it should work:**
The Wyrmrest Skytalon should work as expected, allowing flight and the use of its abilities.

**Database links:**
https://www.wowhead.com/quest=13413/aces-high

**Comment by Ahumaya** [comment]
Please also note that an infinite number of Wyrmrest Skytalons can be spawned by dismounting and requesting a new one.

![wrs0622](https://user-images.githubusercontent.com/82483575/123018105-9649bc00-d393-11eb-96ed-16e968cb4fc8.png)

**Comment by Afgann** [comment]
fixed
