### ISSUE TITLE
[QUEST] Into Hostile Territory - Gryphon Commander Urik does not offer transport option.

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#646]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Per the quest description for Into Hostile Territory, the player must speak with Gryphon Commander Urik to secure a ride to Thorson's Post. Currently, no dialog option exists on Gryphon Commander Urik.

**How to reproduce:**
Accept the quest Into Hostile Territory. Speak with Gryphon Commander Urik. Observe that he has no dialog options.

**How it should work:**
Gryphon Commander Urik should have a dialog option to fly to Thorson's Post.

**Database links:**
https://www.wowhead.com/quest=12325/into-hostile-territory

**Comment by Afgann** [comment]
fixed
