### ISSUE TITLE
[QUEST] The Stone That Started A Revolution

### ISSUE THREAD

**Issue by Enider890** [GameFreedomGG/Maelstrom#652]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** Many of the interactable items to pick up from the ground for this quest have a 10 second 'opening' cast time, when there should not be a cast at all - you should just click the item and loot it, like a mob's corpse.

**How to reproduce:** Accept the named quest and complete the objectives, observe the long cast time on many of the object.

**How it should work:** The item should be looted instantly.

**Database links:**https://cata-twinhead.twinstar.cz/?quest=13130
![image](https://user-images.githubusercontent.com/45482752/123150141-41538780-d41f-11eb-97e5-2aac365fa2b6.png)

**Comment by Afgann** [comment]
fixed
