### ISSUE TITLE
[QUEST] Lumber Hack - Collection sites are incorrect

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#654]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest, the player must use Xink's Shredder to collect lumber from select trees. Currently there are several issues with the collection process. Some trees are marked but can not be collected from. Some trees are marked but can only be collected from specific angles. Some trees are marked and can be collected from and infinite number of times, not requiring the player to move to complete the whole quest.

https://user-images.githubusercontent.com/82483575/123151184-d5761c80-d428-11eb-8a94-3807eadbdbc8.mp4

**How to reproduce:**
Accept the quest Lumber Hack. Approach the quest area. Use the Xink's Shredder Control Device to summon Xink's Shredder, and then enter the Shredder. Approach trees and attempt to gather from them.

**How it should work:**
Each marked tree should only be collectable once, but should be collectable as long as they are marked.

**Database links:**
https://www.wowhead.com/quest=12050/lumber-hack

**Comment by Afgann** [comment]
fixed
