### ISSUE TITLE
[QUEST] Defending Wyrmrest Temple - Wyrmrest Defender spazes out in combat

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#658]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Defending Wyrmrest Temple, once the Wyrmrest Defender enters combat with anything, it begins to spaz out, shown in the video below. This does not end, makes flight impossible, and makes the quest impossible.

https://user-images.githubusercontent.com/82483575/123355580-8e248480-d52b-11eb-8c72-1dc60f6f6c95.mp4

**How to reproduce:**
Accept the quest Defending Wyrmrest Temple. Speak with a Wyrmrest Defender to mount one. Enter combat. Observe the spazing.

**How it should work:**
The Wyrmrest Defenders should act like normal dragon vehicles.

**Database links:**
https://www.wowhead.com/quest=12372/defending-wyrmrest-temple

**Comment by UltraNix** [comment]
Cannot reproduce it.
