### ISSUE TITLE
[QUEST] Mystery of the Infinite, Redux - Past You doesn't spawn

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#660]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently, Past You doesn't spawn when using the Hourglass of Eternity in the Bronze Dragonshrine.

**How to reproduce:**
Accept the quest Mystery of the Infinite. Navigate to the Bronze Dragonshrine. Use the Hourglass of Eternity. Observe that Past You doesn't spawn.

**How it should work:**
Past You should spawn to assist you with killing the enemies that do spawn.

**Database links:**
https://www.wowhead.com/quest=13343/mystery-of-the-infinite-redux

**Comment by Afgann** [comment]
fixed
