### ISSUE TITLE
[Quest Chain] Knights Of Ebon Blade

### ISSUE THREAD

**Issue by cloud1121** [GameFreedomGG/Maelstrom#661]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
**An Undead's Best Friend
Honor is for the Weak
From Whence They Came**

All 3 quest's use an item to take control of an Eidolon Watcher. 

The watchers abilities are not scripted correctly and not working as needed. The food does not count towards quest when feeding dogs, you cannot get close enough to Scourge to assassinate, and crystals are not clickable. 

**How to reproduce:**
Do the quests

**How it should work:**
Abilities should work as intended

**Database links:**
https://www.wowhead.com/quest=13169/an-undeads-best-friend

**Comment by UltraNix** [comment]
Everything works okay.
