### ISSUE TITLE
[QUEST] Head Games - Item interaction does not work

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#666]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Head Games, the player must use the Kurzel's Blouse Scrap on the corpse of Novos the Summoner. Currently this interaction doesn't work.

**How to reproduce:**
Accept the quest Head Games. Kill Novos the Summoner. Attempt to use Kurzel's Blouse Scrap on the corpse. Observe that the interaction does not work.

**How it should work:**
Using the quest item on the corpse should create the Ichor-Stained Cloth, which is the needed quest item.

**Database links:**
https://www.wowhead.com/quest=13129/head-games

**Comment by Afgann** [comment]
fixed
