### ISSUE TITLE
[QUEST] Cleansing Drak'Tharon - Quest not mutually exclusive

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#667]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Cleansing Drak'Tharon (ID 12238) and Cleansing Drak'Tharon (ID 30120) are not mutually exclusive. The player can accept and complete both quests.

**How to reproduce:**
Complete the Drakuru quest line in Grizzly Hills until the point that Cleansing Drak'Tharon becomes available. Accept this quest. Walk into Drak'Tharon Keep. Observe that the Image of Drakuru offers Cleansing Drak'Tharon, and that you can accept both quests.

**How it should work:**
Only one (or the other) should be available for the player to complete.

**Database links:**
https://www.wowhead.com/quest=12238/cleansing-draktharon
https://www.wowhead.com/quest=30120/cleansing-draktharon

**Comment by UltraNix** [comment]
Works okay.
