### ISSUE TITLE
[QUEST] Betrayal - Drakuru doesn't begin event at low heath, dies instead.

### ISSUE THREAD

**Issue by Ahumaya** [GameFreedomGG/Maelstrom#670]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
During the quest Betrayal, the player duels against Drakuru. Currently, you can simply kill him, and he doesn't begin the event that will provide quest credit.

**How to reproduce:**
Accept the quest Betrayal. Speak with Drakuru to begin the duel. Damage Drakuru normally, to low health and then eventually to his death. 

**How it should work:**
At low health (approx 5%), Drakuru should become friendly and start an event. At the conclusion of this event, an object should spawn with the quest item.

**Database links:**
https://www.wowhead.com/quest=12713/betrayal

**Comment by UltraNix** [comment]
Works okay.
