### ISSUE TITLE
level of an item drop in stranglethorn vale is too high

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#671]
**Description:**
In stranglethorn valley, in Mosh ogg ogre compound a level 40 shoulder uncommon item dropped from an npc in the cave.

**How to reproduce:**
kill npc's in the cave or anywhere in Stranglethorn valley

**How it should work:**
items that have a required level should be within the level range of the zone the item drops in.

**Database links:**
https://www.wowhead.com/stranglethorn-vale

**Comment by HerodDev** [comment]
which shoulder?

**Comment by Kreanor** [comment]
I don't remember the npc name or the shoulder item.

**Comment by UltraNix** [comment]
No links/no info.
