### ISSUE TITLE
random ice spike attack while in hinterlands

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#672]
**Description:**
In the hinterlands when attacking attackable npc's, the player
may randomly recieve an ice spike attack that does around 600 damage

**How to reproduce:**
attack an attackable npc in the hinterlands

**How it should work:**
the player should not receive a random ice spike attack that does a high amount of damage for players within the level range of
the Hinterlands unless the npc is supposed to have that attack.

**Database links:**
https://www.wowhead.com/the-hinterlands

**Comment by HerodDev** [comment]
which npc?

**Comment by Kreanor** [comment]
it is any npc in the hinterlands, it would randomly occur, i have experienced this happening at the shore near Shaol' Watha from a turtle npc and another time from a troll npc at Shaol' Watha.

**Comment by UltraNix** [comment]
Cannot reproduce it.
