### ISSUE TITLE
npc bug in Western Plaguelands (Andorhal deathguard and Andohal defender)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#679]
**Description:**
An Andorhal deathguard and an Andorhal Defender
far infront of Thassarian stand still and dont attack anything. The Andorhal
Defender is in an attacking stance and does not target anything and has close
to half health. The Andorhal deathguard is not attackable.

**How to reproduce:**
observe the defender and deathguard npc's far in front of Thassarian  in The Hinterlands in a town with the flightmaster,
Ginny Goodwin.

**How it should work:**
The defender and deathguard npc's should attack any nearby hostile npc's and should be either standing still or be wandering in a certain area.

**Database links:**
https://www.wowhead.com/npc=44448/andorhal-defender
https://www.wowhead.com/npc=44447/andorhal-deathguard

**Comment by UltraNix** [comment]
Fixed.
