### ISSUE TITLE
Humanoids do not run away

### ISSUE THREAD

**Issue by CluckyBoomy** [GameFreedomGG/Maelstrom#68]
**Description:**
When humanoids are getting spanked to death, on low HP they should start running away. They dont. Atleast the elwynn forest ones.

**How to reproduce:**
Fight humanoid

**How it should work:**
Humanoids should start running away from you when they get low

**Comment by UltraNix** [comment]
No info provided.

**Comment by Greywolf59** [comment]
Goldtooth: https://www.wowhead.com/npc=327/goldtooth
This NPC does run away when low on HP, but there is no emote "[Name] runs away in fear" or how exactly was the phrase. Not sure if the emote is there past-Wotlk, never played past that expansion.
However I indeed haven't noticed any other mob run away in fear, which is pretty custom behaviour on pre-cata servers I have played on.
