### ISSUE TITLE
Issue with daily quest **Gormok Wants His Snobolds**

### ISSUE THREAD

**Issue by Costosos** [GameFreedomGG/Maelstrom#684]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest daily quest Gormok Wants His Snobolds seems to not be working as I spent 10 minutes trying to capture Kobolds with the net at Garm's Bane in southeast Storm Peaks. The player  is supposed to throw the net at 8 different kobolds to capture them and then return to Argent Tournament Grounds to hand in the quest.

**How to reproduce:**
Throw the net at the kobolds and see that nothing happens as the kobolds disappear but it doesn't count towards the completion of the quest.

**How it should work:**
Throw the net at the kobolds and have it count towards the 8 needed to complete the quest.

**Database links:**
https://www.wowhead.com/quest=14090/gormok-wants-his-snobolds

**Comment by Afgann** [comment]
fixed
