### ISSUE TITLE
Quest [The Exorcism of Colonel Jules] failed event is continued after npc's death

### ISSUE THREAD

**Issue by Bluecow941** [GameFreedomGG/Maelstrom#686]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently bug makes quest easier to complete if you failed it and just looks creepy. When Anchorite Barada dies during quest event by fiends and respawns, quest event doesn't reset but continues the first one, and gives credit for it after few seconds. 

**How to reproduce:**
Get quest [The Exorcism of Colonel Jules] -> Talk to Anchorite Barada & enable quest event -> go AFK, let NPC die -> wait until NPC respawns -> if script doesn't continue after his respawn, talk to him to enable it again, he should continue the last one and after it, begin another quest event

**How it should work:**
After NPC's death, the quest event on his side should be reset and start from 0 after talking to him in order to begin exorcism

**Database links:**
https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules
https://www.wowhead.com/npc=22431/anchorite-barada

**Comment by UltraNix** [comment]
Everything works okay.
