### ISSUE TITLE
Occassional mobs bugged in textures

### ISSUE THREAD

**Issue by CluckyBoomy** [GameFreedomGG/Maelstrom#69]
**Description:**
Mobs pathfinding sometimes leads into other textures, in this case tree for example

**How to reproduce:**
Hard to reproduce, you need to see ones movement and watch it go (see screenshot)

**How it should work:**
Mobs should not have pathfidning leading into textures, rather avoiding them or stopping infrontof.
![WoWScrnShot_041221_170510](https://user-images.githubusercontent.com/82396034/114418051-6ec7bd80-9bb2-11eb-985a-abe26b6d3a91.jpg)

**Comment by CluckyBoomy** [comment]
![Uploading WoWScrnShot_041221_171645.jpg…]()

**Comment by CluckyBoomy** [comment]
![WoWScrnShot_041221_171645](https://user-images.githubusercontent.com/82396034/114419586-d6323d00-9bb3-11eb-83ee-9d57b2f2d46c.jpg)

**Comment by UltraNix** [comment]
Fixed.
