### ISSUE TITLE
Quest [It Goes to 11...], Dragonflayer Defenders are not spawning correctly

### ISSUE THREAD

**Issue by Bluecow941** [GameFreedomGG/Maelstrom#690]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently quest is impossible to complete, unless you are going to question your sanity and go into place where I found missing guys. When you use harpoon gun, destroying buildings works fine, but Dragonflayer Defenders aren't spawning after that, while they should. Since they almost don't exist, quest is not completeable without them. Also they were present in this place when I gave up and went to do another quests. I assume their amount depends on how many times you destroyed exact building or you entered harpoon gun or left it, but it shouldn't be like that for sure.
![WoWScrnShot_070921_182437](https://user-images.githubusercontent.com/77903973/125202699-f9cd5800-e274-11eb-8e81-0532fa686c86.jpg)

**How to reproduce:**
Get quest [It Goes to 11...] -> jump into gun, destroy buildings -> question sanity

**How it should work:**
Dragonflayer Defenders should arrive every time once you destroy buildings mentioned in quest. Their way of appearance should look like in this video https://www.youtube.com/watch?v=JBiE2hLGqOE, not like currently.

**Database links:**
https://www.wowhead.com/npc=24533/dragonflayer-defender
https://www.wowhead.com/quest=11421/it-goes-to-11

**Comment by UltraNix** [comment]
Works okay.
