### ISSUE TITLE
Quest [Trust is Earned] terribly awful slow cast bar

### ISSUE THREAD

**Issue by Bluecow941** [GameFreedomGG/Maelstrom#691]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently quest is completeable, but for next quests in chain it's awful and not retail-like, so for me it's a bug. When you pick a Fjord Grub from Loose Rock object, you have to simulate looking in that rock by having a looooooooong cast bar in order to find just 1 Grub. It affects at least next 2 quests from chain. Other parts of quest work fine.

**How to reproduce:**
Get quest [Trust is Earned] -> grab Fjord Grub from Loose Rock -> watch that cast bar

**How it should work:**
Actually there should not be any cast bar, it should be an instant interaction to loot rock and I haven't found any information claiming there should be this king of cast bar upon clicking rocks.

**Database links:**
https://youtu.be/YhyRLg9kepI?t=10 - moment of grabbing rock
https://www.wowhead.com/quest=11460/trust-is-earned

**Comment by Afgann** [comment]
fixed
