### ISSUE TITLE
Quest [The Delicate Sound of Thunder] no event after entering quest zone

### ISSUE THREAD

**Issue by Bluecow941** [GameFreedomGG/Maelstrom#694]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
At this moment quest is impossible to complete. When you appear in a Iron Rune Construct to quest zone, which is a titan in middle of Thundering Cave, the event with Loken doesn't appear, while it should.

**How to reproduce:**
Get quest [The Delicate Sound of Thunder] -> go to Thundering Cave to stone titan in middle of it -> walk around him, try to trigger event and get credit for quest

**How it should work:**
The event which gives credit for quest should appear and work correctly. Additionally:
-Bluff spell should work immediately, without delay so you can defend yourself against suspicious dwarves
-Dwarves should attack your Construct when Bluff doesn't work

**Database links:**
https://youtu.be/O98BhP_zJBU?t=49
https://www.wowhead.com/quest=11495/the-delicate-sound-of-thunder

**Comment by UltraNix** [comment]
Works okay.
