### ISSUE TITLE
Eastern Plaguelands (Npc bug)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#698]
**Description:**
The rare npc named Deathspeaker Selendre located in Death's Step in Eastern Plaguelands continues to walk in the npc's walking circuit while in combat and will attack while moving if the target is within range of attack for the npc. The npc will stop walking on the npc's usual walking circuit when casting a spell.

**How to reproduce:**
Find and attack the npc in Death's Step then move out of range in order to observe the bug then get close to the npc so the npc can attack the player.

**How it should work:**
The npc should move toward the player while attacking instead of continuing on the npc's usual path.

**Database links:**
https://www.wowhead.com/npc=10827/deathspeaker-selendre

**Comment by UltraNix** [comment]
Works okay.
