### ISSUE TITLE
Quest Endgame

### ISSUE THREAD

**Issue by Bluecow941** [GameFreedomGG/Maelstrom#70]
**Description:**
One of last quests in Glineas, [Endgame] is at this moment autocompleted, so it's not possible to complete it retail-like.

**How to reproduce:**
Take quest Endgame from NPC -> it becomes auto-completed, you can't jump on hippogryph

**How it should work:**
Quest should be scripted and doable like in retail: https://youtu.be/PLsMrew_ui4?t=722

**Comment by UltraNix** [comment]
Quest works okay.
