### ISSUE TITLE
Eastern PLaguelands (npc bug) Gidwin Goldbraids and Tarenar Sunstrike

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#704]
**Description:**
The npc's Gidwin Gold braids and Tarenar Sunstrike while in Light's Hope Chapel walks through the chapel floor when following the player in the chapel.

**How to reproduce:**
Enter the Light's Hope Chapel building in Lights hope Chapel while having a quest obtained after completing the quest named boys will be boys.

**How it should work:**
The npc's should walk on top of the chapel floor instead of in the floor.

**Database links:**
https://www.wowhead.com/quest=27455/boys-will-be-boys
https://www.wowhead.com/npc=52221/gidwin-goldbraids#outfit
https://www.wowhead.com/npc=45729/tarenar-sunstrike

**Comment by UltraNix** [comment]
Works okay.
