### ISSUE TITLE
Right clicking quest items withouch channel

### ISSUE THREAD

**Issue by KochamLolitki** [GameFreedomGG/Maelstrom#708]
**Description:**
Right clicking quest items that do not require to cast allow to complete multiple ticks from one object
By using touchpad + mouse i was able to get 4 off a single object
Just spamming mouse max 2
With autoclicker i was able to get 8 and instantly complete quest out of one object
**How to reproduce:**
Spam right mouse button on object in quest that does not require channeling eg. trolls in first goblin quest

**How it should work:**
one object one tick to quest completion

https://user-images.githubusercontent.com/38408955/132591936-0ecd5bc0-c972-4bbd-a8c1-9bc1ce87812b.mp4

**Comment by UltraNix** [comment]
Cannot reproduce it.
