### ISSUE TITLE
[Quest] Fight Fire and Water and Air with

### ISSUE THREAD

**Issue by nogunk** [GameFreedomGG/Maelstrom#710]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Bound Water Elemental for the Quest does not give the Water Ward buff that is needed to complete the quest.

**How to reproduce:**
Just kill the Bound Water Elemental and youll see it doesnt give the buff

**How it should work:**
Read Above. Killing the Bound Water Elemental should give you a buff needed to complete the quest requirements.

**Database links:**
https://www.wowhead.com/quest=27042/fight-fire-and-water-and-air-with
https://www.wowhead.com/npc=44886/bound-water-elemental

**Comment by Afgann** [comment]
fixed
