### ISSUE TITLE
[Hunter] Ice Trap and Lock and Load

### ISSUE THREAD

**Issue by nogunk** [GameFreedomGG/Maelstrom#711]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
At the moment, Ice trap does not proc Lock and Load if an already existing Ice Trap effect is active on the ground.

**How to reproduce:**
Simply place a Ice trap to trigger Lock and Load and then place another one before the previous Ice Trap slick wears off.

**How it should work:**
Ice trap should overwrite the previous Ice trap slick if it hasnt expired yet and proc lock and load each time it is triggered. 

**Database links:**

https://cata-twinhead.twinstar.cz/?spell=56343

**Comment by xHAGENx** [comment]
+1
L&L didnt proc when u use ice trap on targets which are on existing traps, but if u throw trap on npc without trap debuff its ok.
When 1. trap has expired and npc got debuf from second one l&l also proc.
