### ISSUE TITLE
[QUEST] A bird in hand

### ISSUE THREAD

**Issue by Akempis228** [GameFreedomGG/Maelstrom#713]
**Description:**
Unable to finish the quest "A bird in hand" due to Marion Wormwing wont be captured. When you engage her, the druid comes but she dont get captured. 
If you wwait until the debuff "SMoked out" is removed you can interrogate her but you dont get the "Captured"-part completed.

**How to reproduce:**
Accept the quest and start the engagement

**How it should work:**
Accept the quest, start engagement when she gets low she should be captured. 

**Database links:**

**Comment by Jackomighty** [comment]
Database links:
https://www.wowhead.com/quest=25731/a-bird-in-hand
https://www.wowhead.com/npc=41169/marion-wormwing-captured

**Comment by Exorcista** [comment]
This is again Bug as for 8/15 the part to "capture" her never gets credit
