### ISSUE TITLE
[HUNTER] [SPELL] Tame Beast

### ISSUE THREAD

**Issue by xHAGENx** [GameFreedomGG/Maelstrom#716]
**Description:**
When hunter tame new pet and dismiss him, he cant summon him again until relog.
Pets stats are also not correct after tamed, pet don't get any profit from hunter stats scaling until relog.

**How to reproduce:**
-

**How it should work:**
Pet after taming should have proper stats, and hunter could use him normally.

**Database links:**
-

**Comment by UltraNix** [comment]
Fixed.
