### ISSUE TITLE
Quest: "Black Heart of Flame"

### ISSUE THREAD

**Issue by Aidaidu** [GameFreedomGG/Maelstrom#719]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Can't summon Thol'embaar. It says that I'm in the wrong zone but I'm in the correct place.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=bK1HjCDM_Cc

**Database links:**
https://www.wowhead.com/quest=25428/black-heart-of-flame

![WoWScrnShot_090921_125125](https://user-images.githubusercontent.com/90389326/132673471-d5e97753-f490-42f5-bcb4-86ceac516857.jpg)

**Comment by malekd1** [comment]
still not working, stuck at 73 out 115 quests in mount hyjal.
its a crucial quest because it leads to rest of the quest line.

**Comment by Pocokk** [comment]
He is at 13, 37, standing still.

**Comment by Afgann** [comment]
fixed
