### ISSUE TITLE
Weird animation pause of warrior attacks

### ISSUE THREAD

**Issue by CluckyBoomy** [GameFreedomGG/Maelstrom#72]
**Description:**
When fighting a mob, character (warrior) does weird "not doing anything" poses between the auto attack animations.

**How to reproduce:**
!CHARGE IN FIRST!, start autoattacking, watch the warriors animation.

**How it should work:**
The character should be in "fight pose" for the whole duration of combat

**Comment by UltraNix** [comment]
Looks okay to me.
