### ISSUE TITLE
NPC Wormwing Screecher

### ISSUE THREAD

**Issue by Jackomighty** [GameFreedomGG/Maelstrom#722]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Some Wormwing Screecher NPC's are not attackable, not reacting on AOE damage and while trying to melee or range attack, error message pops out saying "You are facing the wrong way!".

**How to reproduce:**
Accept the quest The Wormwing Problem and try to attack Wormwing Screecher NPC's.

**How it should work:**
They should be attackable.

**Database links:**
https://www.wowhead.com/quest=25655/the-wormwing-problem
https://www.wowhead.com/npc=41028/wormwing-swifttalon

**Comment by Afgann** [comment]
fixed
