### ISSUE TITLE
[HUNTER]  [Improved Serpent Sting]

### ISSUE THREAD

**Issue by xHAGENx** [GameFreedomGG/Maelstrom#723]
**Description:**
![image](https://user-images.githubusercontent.com/90351303/132686761-22122a3b-d35f-4747-9094-3cd904de0a05.png)
Improved Serpent Sting dmg is too low.
When we have crit there should be dmg calculate as every tick of serpent sting with crit with toxicology (+100% dmg)
**How to reproduce:**
-

**How it should work:**
![image](https://user-images.githubusercontent.com/90351303/132686741-acac9612-0822-4abd-b514-28b1c4714f9a.png)

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=82834
https://cata-twinhead.twinstar.cz/?spell=82833

**Comment by xHAGENx** [comment]
Connected with https://github.com/SallyWhitemane/Herod/issues/725

**Comment by UltraNix** [comment]
Looks okay.
