### ISSUE TITLE
Inciting the elements quest

### ISSUE THREAD

**Issue by Qtaurentino** [GameFreedomGG/Maelstrom#724]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Bug I encountered is the following : The Twilight Inciter can be killed without the help of the Faerie Dragon, they should be stealthed and undetectable.

**How to reproduce:**
I was in Mount Hyjal on my Rogue - name Selenius and tried to do the first quest, the Faerie Dragon script works just fine but you need to add an undetectable stealth to the Twilight Inciter so only the Faerie Dragon will be able to spot him. After that the Twilight Inciter will aggro you and that's it.

**How it should work:**

In order to do the quest you must feed the Faerie Dragon with Juniper Berries that you can find around, then after few second the Faerie will reveal the Twilight Inciter and you can kill him.

**Database links:**
https://www.wowhead.com/quest=25370/inciting-the-elements

**Comment by Platinumcoated** [comment]
**Additional minor quest corrections**

Juniper Berry bushes are openable even without the quest, but without the quest there will be nothing inside, this will then destroy the bush.
---
The Twilight Inciters drop Juniper Berries too for some reason, in none of the playthrough videos on wowhead does it appear that they would have any loot though.
https://www.wowhead.com/quest=25370/inciting-the-elements#videos

The wowhead database lists Juniper Berries as 92% drop from Twilight Inciters, which makes no sense, but could be from later patch
[Twilight Inciter on wowhead](https://www.wowhead.com/npc=39926/twilight-inciter)

Twinhead database lists drops the way they would make sense (it's still a private server database though)
[Twilight Inciter on twinhead](https://cata-twinhead.twinstar.cz/?npc=39926)
[Juniper Berries on twinhead](https://cata-twinhead.twinstar.cz/?item=53009)
