### ISSUE TITLE
Quest Disassembly

### ISSUE THREAD

**Issue by Jackomighty** [GameFreedomGG/Maelstrom#727]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
NPC Twilight Juggernaut seems to have it's buff Armor Plating nor working properly at all

**How to reproduce:**
Accelpt the quest Disassembly

**How it should work:**
NPC should have proper 5 stacks of Armor Plating buff and with provided item from quest Thisalee's Shiv should take one stack by the time used on the NPC and do appropriate damage too.

**Database links:**

https://www.wowhead.com/quest=25761/disassembly
https://www.wowhead.com/npc=41031/twilight-juggernaut#abilities
https://www.wowhead.com/item=55883/thisalees-shiv

**Comment by Afgann** [comment]
fixed
