### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by xHAGENx** [GameFreedomGG/Maelstrom#731]
**Description:** + **How it should work:**
When npc is trying look for path and and doesnt find any in a few sec, he should change target if there is no more targets, npc should reset.
I clear first 4 bosses on arena in TH solo that way.
It could be also abused to clear fl trash solo.
**How to reproduce:**
Just stay on some roof where npc cant enter and hit him.

**Database links:**
-

**Comment by UltraNix** [comment]
Fixed.
