### ISSUE TITLE
Combat bug after you use Vanish

### ISSUE THREAD

**Issue by Qtaurentino** [GameFreedomGG/Maelstrom#732]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Bug I encountered is the following : After I get aggro from any mob and use Vanish I am still stuck in combat and can't mount up for exemple

**How to reproduce:**
I met this problem on my rogue Selenius in Mouny Hyjal doing quests, after I used Vanish and went far away from mob pack it followed me back.

**How it should work:**
After you use Vanish your threat must be 0, and you must lose all the threat from the respective mob.

**Database links:**

https://www.wowhead.com/spell=1856/vanish

**Comment by UltraNix** [comment]
Works okay to me.
