### ISSUE TITLE
Quest An Ancient Reborn

### ISSUE THREAD

**Issue by Jackomighty** [GameFreedomGG/Maelstrom#735]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The NPC Aviana is always spawned, she shouldn't be.

**How to reproduce:**
Accept the quest

**How it should work:**
NPC should be spawned only upon using the quest item Herald's Incense, NPC should have a dialog and animation upon spawning.

**Database links:**
https://www.wowhead.com/quest=25807/an-ancient-reborn

**Comment by Afgann** [comment]
fixed
