### ISSUE TITLE
Quest: Magma Monrach

### ISSUE THREAD

**Issue by Aidaidu** [GameFreedomGG/Maelstrom#736]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After using drums near King Moltron Tortolla spawns but does nothing

**How to reproduce:**

**How it should work:**
Tortolla should engage and fight Moltron
https://www.youtube.com/watch?v=m-IRXiHRR9Y

**Database links:**
https://www.wowhead.com/quest=25550/magma-monarch
![WoWScrnShot_090921_162721](https://user-images.githubusercontent.com/90389326/132705025-dbfda9e4-b897-4372-b61e-12b6cea789e4.jpg)

**Comment by Afgann** [comment]
fixed
