### ISSUE TITLE
Murloc pathfinding in water

### ISSUE THREAD

**Issue by manuelinobdk** [GameFreedomGG/Maelstrom#74]
When u aggro a murloc in elwynn forest and swim to the top of the water, the mob willl stay on the bottom of the water and wont attack u

**How to reproduce:** just fight a murloc in water

**How it should work:**
he should swim up to attack u 
![Desktop Screenshot 2021 04 12 - 17 43 54 19](https://user-images.githubusercontent.com/82398722/114423463-7d64a380-9bb7-11eb-9842-881b29c7d937.png)

**Comment by Afgann** [comment]
fixed
