### ISSUE TITLE
Quest Flight in the Firelands

### ISSUE THREAD

**Issue by Jackomighty** [GameFreedomGG/Maelstrom#740]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Duplicate of NPC-s are spawned in the area, the warning text dialog is not appearing to grab a lance from the rack, to equip a lance and to mount one of Aviana's guardians ect.
Upon completing the quest, those duplicate NPC-s disappear, leaving just one of the kind spawned around the player. 

**How to reproduce:**
Accept the quest.

**How it should work:**
Duplicate NPC-s should not exist in a first place. The warning text dialog should appear on the screen to guide the player throughout the quest.

**Database links:**
https://www.wowhead.com/quest=25523/flight-in-the-firelands

**Comment by Afgann** [comment]
fixed
