### ISSUE TITLE
Quest: Be Prepared

### ISSUE THREAD

**Issue by Aidaidu** [GameFreedomGG/Maelstrom#741]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After stepping on bones skeleton should spawn and it does but you can't attack that target and it just stays there and does nothing

**How to reproduce:**

**How it should work:**
Skeletons should be attackable 
https://www.youtube.com/watch?v=qKuIa01GTpw

**Database links:**
https://www.wowhead.com/quest=27517/be-prepared
![WoWScrnShot_090921_172112](https://user-images.githubusercontent.com/90389326/132716474-5e9c0175-38e6-4bfa-ad06-66e9d6970721.jpg)

**Comment by Pocokk** [comment]
Also if you handle in the "By the Light of the Stars" quest, you can no longer see the "other phase", so you can't even accept this quest.

**Comment by Afgann** [comment]
fixed
