### ISSUE TITLE
Worgen Starting Area - Stuck in Combat

### ISSUE THREAD

**Issue by blackey191** [GameFreedomGG/Maelstrom#743]
**Description:**
Anytime you run from a mob and they evade you do not leave combat. The character was a rogue and I have not tested other classes. Cannot stealth, heal, logout, or exit game when in combat.

**How to reproduce:**
Start rogue Worgen and try running from a mob. I do not recall if it happened immediately or after a few quests in. I do know it still happens when fighting the horrors where you throw a gun powder barrel over their head.

**How it should work:**
Once they evade you should leave combat.

**Comment by UltraNix** [comment]
Cannot reproduce it.
