### ISSUE TITLE
Quest Wave One

### ISSUE THREAD

**Issue by Jackomighty** [GameFreedomGG/Maelstrom#744]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Similar story as with the quest Flight in the Firelands, the warning text dialog is not appearing which is guiding the players throughout the quest.

**How to reproduce:**
Accept the quest.

**How it should work:**
The Warning text dialog should be implemented.

**Database links:**
https://www.wowhead.com/quest=25525/wave-one

**Comment by Afgann** [comment]
fixed
