### ISSUE TITLE
Quest Wave Two

### ISSUE THREAD

**Issue by Jackomighty** [GameFreedomGG/Maelstrom#746]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Same as quest Flight in the Firelands and Wave One, the warning text dialog is not appearing which is guiding the players throughout the quest.

**How to reproduce:**
Accept the quest.

**How it should work:**
The Warning text dialog should be implemented.

**Database links:**
https://www.wowhead.com/quest=25544/wave-two

**Comment by Afgann** [comment]
fixed
