### ISSUE TITLE
Quest Egg Wave

### ISSUE THREAD

**Issue by Jackomighty** [GameFreedomGG/Maelstrom#747]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Same issue as from previous quests in the same questchain, the warning text dialog is not appearing which is guiding the players throughout the quest.
Fireland Egg animation upon destroying them is not correct.

**How to reproduce:**
Accept the quest

**How it should work:**
The Warning text dialog should be implemented.
Fireland Egg animation upon destroying them should be in much bigger range and for last for a longer time; see the video in Wowhead link down below for a reference. 

**Database links:**
https://www.wowhead.com/quest=25560/egg-wave

**Comment by Afgann** [comment]
fixed
