### ISSUE TITLE
Hunter pets pathfinding is buggy

### ISSUE THREAD

**Issue by manuelinobdk** [GameFreedomGG/Maelstrom#75]
![Desktop Screenshot 2021 04 12 - 18 13 39 05](https://user-images.githubusercontent.com/82398722/114427002-edc0f400-9bba-11eb-8c92-b73edd217b25.png)
**Description:** pet runs behind u and u often have to wait for it when u initiate combat

**How to reproduce:** get a spell

**How it should work:** pet should be next to you
![Desktop Screenshot 2021 04 12 - 18 07 26 30](https://user-images.githubusercontent.com/82398722/114426152-0e3c7e80-9bba-11eb-94ca-7f48acd79e82.png)

**Comment by UltraNix** [comment]
Fixed.
