### ISSUE TITLE
The Pit of Scales

### ISSUE THREAD

**Issue by GitGudNubHub** [GameFreedomGG/Maelstrom#750]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
 The pit of scales quest in uldum is bugged. There is no npc that starts the quest when you appear.

**How to reproduce:**
Go to the Pit of Scales place in Uldum.

**How it should work:**
There should be an npc that starts the quest when u you appear in front of him.

**Database links:**
https://www.youtube.com/watch?v=ITRveyq_X8o

**Comment by UltraNix** [comment]
Works okay.
