### ISSUE TITLE
[Quest] [Tol Barad] The Forgotten

### ISSUE THREAD

**Issue by Zube18** [GameFreedomGG/Maelstrom#755]
**Description:**
The ghosts that spawn when you click the graveyard stone should spawn close to the angel/tombstone
currently is spawns at the player position

**How to reproduce:**
Click tombstone

**How it should work:**
The ghosts that spawns, should spawn next to the tombstone

**Database links:**
https://www.wowhead.com/quest=28689/the-forgotten
https://youtu.be/wCT1QkkFnWU?t=77

Addition**: NPCs around that area dont have pathing

**Comment by Afgann** [comment]
fixed
