### ISSUE TITLE
[Quest] Violent Gale

### ISSUE THREAD

**Issue by Zube18** [GameFreedomGG/Maelstrom#757]
**Description:**
Quest window doesnt pop up after completing the tasks

**How to reproduce:**
Complete tasks

**How it should work:**
After completing the two requirements a quest log should pop up to complete it.

**Database links:**
https://www.wowhead.com/quest=26426/violent-gale
https://youtu.be/jFLvCpdkZ7c?t=40

**Comment by Afgann** [comment]
fixed
