### ISSUE TITLE
Hyjal Warden can be hit with cleave from felguard

### ISSUE THREAD

**Issue by malekd1** [GameFreedomGG/Maelstrom#760]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:** warlock pet felguard can aggro them with cleave.
they should be friendly . 

**How to reproduce:**
use felstrom or legion strike on any hyjal warden in mount hyjal

**How it should work:**
it shouldn't be hit with the felstorm and should show invalid target with legion strike

**Database links:**
https://www.wowhead.com/npc=43427/furious-hyjal-warden
https://cata-twinhead.twinstar.cz/?spell=89751
https://cata-twinhead.twinstar.cz/?spell=30213
https://cata-twinhead.twinstar.cz/?npc=38915

![WoWScrnShot_091021_224934](https://user-images.githubusercontent.com/90353437/132916232-2b4b8cc8-bbf8-4153-8581-be46161285a0.jpg)
![WoWScrnShot_091021_222653](https://user-images.githubusercontent.com/90353437/132916265-79fc8b7b-2ece-43f4-9708-ef555bc9a2a0.jpg)

**Comment by UltraNix** [comment]
Cannot reproduce it.
