### ISSUE TITLE
[NPC] Lycanthoth Vandal

### ISSUE THREAD

**Issue by SallyWhitemane** [GameFreedomGG/Maelstrom#762]
This NPC after being pulled should charge on player. but apparently it stops in the halfway and keeps doing nothing until player get closer to melee range.

db link: https://www.wowhead.com/npc=39445/lycanthoth-vandal

Reproduction: https://youtu.be/4Ud9JCjga-0 

NPC should reach player with his charge.

**Comment by UltraNix** [comment]
Looks okay.
