### ISSUE TITLE
[Quest][minor] As Hyjal Burns

### ISSUE THREAD

**Issue by Platinumcoated** [GameFreedomGG/Maelstrom#765]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
None of this causes any actual problems actually, just minor things

**Description:**
-For Alliance the quest doesn't have it's requirement set correctly, can be picked up without completing the pre-quest
Alliance pre-quest: [Hero's Call: Mount Hyjal!](https://cata-twinhead.twinstar.cz/?quest=27726)
(As Hyjal Burns itself is multi-faction)
(Horde have the pre-quest set correctly)

-The music during the quest is force-played and will play even if in-game music is turned off

-The roleplay is also really cirnge but I guess that's blizzlike actually

**Database links:**
[As Hyjal Burns](https://cata-twinhead.twinstar.cz/?quest=25316)

**Comment by UltraNix** [comment]
Not a bug.
