### ISSUE TITLE
Melee attack range behaviour - can attack enemies behind me

### ISSUE THREAD

**Issue by Platinumcoated** [GameFreedomGG/Maelstrom#766]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
It is possible to attack enemies behind me if I'm standing close enough within certain range. (!!!)

Attempting auto-attacks and melee abilities against enemies produces different error messages depending on whether I'm standing outside melee-range or within melee range but not close enough to trigger the bug (might be unrelated and irrelevant)

**Behaviours:**
Standing further than regular melee range I am unable to use auto-attakcs or melee abilities (good)
Auto-attacks say "You are facing the wrong way!" (even if I'm facing enemy)
Melee abilitites say "Out of range"
[video](https://www.youtube.com/watch?v=Psda2g1lVuY)

Standing just on the edge of the melee range I am able to use auto-attakcs and melee abilities when facing enemy (good)
I am unable to use auto-attacks and melee abilities when **not** facing the enemy (good)
Auto-attacks say "You are too far away!"
Melee abilities say "Target needs to be in front of you."

Standing within melee range and close to the enemy I am able to use auto-attacks and melee abilites **both** when facing and facing away from the enemy (bad)

[works in pvp](https://www.youtube.com/watch?v=klTHyvAKKqE)
[ video showcasing against mobs, shows the odd range threshold for bug to work](https://www.youtube.com/watch?v=s0dIEOultyY)

**How it should work:**
I should be unable to use any melee attacks against an enemy if I am not facing them

**Source**
uhhh I dunno how to disprove that, just doesn't make sense

**Comment by Afgann** [comment]
fixed
