### ISSUE TITLE
[Quest] [Hyjal] Graduation Speech

### ISSUE THREAD

**Issue by pkumar313** [GameFreedomGG/Maelstrom#767]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When standing on the podium the action bar should have four options: Inspire, Incite, Pander and Leave but only two show making the quest incompletable.

**How to reproduce:**
![image](https://user-images.githubusercontent.com/54285227/132972728-3795c7fc-8a99-43ea-b73a-22506e6ee100.png)

**How it should work:**
https://www.youtube.com/watch?v=YDHJlF8HxsU

**Database links:**
https://www.wowhead.com/quest=25315/graduation-speech

**Comment by xHAGENx** [comment]
I had the same problem, and I just alt+f4 and when I log next day that quest work properly. Relog probably helps, but anyway its quest to fix.

**Comment by Pocokk** [comment]
> 
> 
> I had the same problem, and I just alt+f4 and when I log next day that quest work properly. Relog probably helps, but anyway its quest to fix.

Or just pressing randomly the buttons.
