### ISSUE TITLE
[Quest] [Hyjal] Magma Monarch

### ISSUE THREAD

**Issue by pkumar313** [GameFreedomGG/Maelstrom#768]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After using the quest item Tortolla just stays in place instead of fighting King Moltron

**How to reproduce:**
![image](https://user-images.githubusercontent.com/54285227/132973189-36805019-0c63-4fd6-a582-2b13b26f0524.png)

**How it should work:**
https://www.youtube.com/watch?v=m-IRXiHRR9Y

**Database links:**
https://www.wowhead.com/quest=25550/magma-monarch

**Comment by xHAGENx** [comment]
Duplicate:
https://github.com/SallyWhitemane/Herod/issues/736
