### ISSUE TITLE
[QUEST] graduation speech

### ISSUE THREAD

**Issue by malekd1** [GameFreedomGG/Maelstrom#769]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when u start giving ur speech u lack 2 spells on the action bar 
 *Pander!
 *and the walk away spell
two drakes shouldn't be there Aronus.
![WoWScrnShot_091221_124126](https://user-images.githubusercontent.com/90353437/132984597-c6ee05c0-fbf0-46d2-9b6c-1d7011c9337c.jpg)

**How to reproduce:**
try doing the quest

**How it should work:**
the pander! spell should appear and use it convenietly with how the crowd react.
the walk away spell to step out of podium.
noaronus drakes.

**Database links:**
https://www.wowhead.com/quest=25315/graduation-speech
https://www.youtube.com/watch?v=YDHJlF8HxsU

**Comment by malekd1** [comment]
you can't advance through the quest because u need the pander! spell so no idea how thongs will sort out.

**Comment by Pocokk** [comment]
> 
> 
> you can't advance through the quest because u need the pander! spell so no idea how things will sort out.

Its there, just press "number 3" on your keyboard.

**Comment by UltraNix** [comment]
Looks okay.
