### ISSUE TITLE
Misleading Queues

### ISSUE THREAD

**Issue by Gaugeoak** [GameFreedomGG/Maelstrom#772]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Started last night with queue time claiming to be waiting on a tank and I was in queue for 7 hours.  Today is says waiting for tank and less than 1 min wait time.  Confirmed in World chat that others weren't queued.

**How to reproduce:**
Queue for a random dungeon

**How it should work:**
Should show accurate party makeup and queue time

<img width="1142" alt="Endless Queue" src="https://user-images.githubusercontent.com/82425397/132999119-90fc36d6-147a-4498-9889-08edecfe5b7f.png">

**Database links:**

**Comment by UltraNix** [comment]
Looks okay to me.
