### ISSUE TITLE
Resonating Blow Quest in Deepholm 

### ISSUE THREAD

**Issue by Gaugeoak** [GameFreedomGG/Maelstrom#773]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When hitting the crystal to summon the dragon to fight, I have to fly up to a rock to engage the fight or else hitting the stone produces the boss endlessly.  When I finish the battle the other dragons I summoned from hitting the stone multiple times follow me until I die.

**How to reproduce:**
Hit the stone with the mallet multiple times, fly up and land on a stone and beat a dragon and try to run away.

**How it should work:**
Terrath is supposed to pick you up after hitting the stone with the mallet and it engages the fight.  Shouldn't have to fly up to the stone.
<img width="1520" alt="Resonating Blow" src="https://user-images.githubusercontent.com/82425397/132999210-ca4a5ca6-4bdc-4848-9f5c-d02675a6c0cf.png">

**Database links:**
https://www.wowhead.com/quest=26659/resonating-blow

**Comment by Afgann** [comment]
fixed
