### ISSUE TITLE
[Inciting the Elements] quest, Hidden Twilight inciters appearing when player is near.

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#774]
**Description:**
I am not sure if this is a bug or not but when a player passes by a hidden Twilight Inciter in Mount Hyjal, in the Nordrassil zone near Nordrassil inn the Twilight Inciter NPC's become visible to the player and the player is able to attack them, however the Twilight Inciters do not attack the player unless the player attacks them.

**How to reproduce:**
Roam the area around Nordrassil Inn until a stealthed Twilight Inciter is found and attack the npc.

**How it should work:**
A Twilight Inciter can be found by picking Juniper Berries in the area around Nordsrassil Inn and feeding them to Faerie dragons
that then search for and reveal a Twilight Inciter npc, I am not certain if Twilight Inciters are supposed to be found by being near them.

**Database links:**
https://www.wowhead.com/quest=25370/inciting-the-elements

**Comment by UltraNix** [comment]
Not a bug.
