### ISSUE TITLE
Flamebreaker quest (quest item bug)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#780]
**Description:**
The Flameseer's staff item can be used while mounted and while moving while mounted but the game shows the interrupted text on the screen while using the item and moving.

**How to reproduce:**
Use the Flameseer's staff on a Blazebound elemental in Mount Hyjal near the Circle of Cinders while mounted and/or while moving.

**How it should work:**
The Flameseer's staff effect should stop while the player is moving during the channeling effect.

**Database links:**
https://www.wowhead.com/item=53107/flameseers-staff

**Comment by UltraNix** [comment]
Nope. Item can be casted on mount - have special attribute.
https://www.wowhead.com/spell=75206/flamebreaker
`Can be used while mounted`
