### ISSUE TITLE
This Can Only Mean One Thing... (quest description typo)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#781]
**Description:**
The final sentence of the turn in quest for the [This Can Only Mean One Thing...] quest has a typo.

**How to reproduce:**
Read the last sentence of the quest text for the turn in quest of [This Can Only Mean One Thing...] quest.

**How it should work:**
There should not be a typo in the turn in quest text.

**Database links:**
https://www.wowhead.com/quest=28732/this-can-only-mean-one-thing

**Comment by UltraNix** [comment]
I see no bug here.
