### ISSUE TITLE
Through the Dream quest (quest npc bug)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#782]
**Description:**
The npc Arch Druid Fandral Staghelm can move through objects as he follows the player.

**How to reproduce:**
Accept the quest [Through the Dream] from the npc Captain Saynna Stormrunner and escort the quest npc Arch Druid Fandral Staghelm out of the Hyjal Barrow Dens to the entrance of the barrow.

**How it should work:**
The quest npc Arch Druid Fandral Staghelm should not go through objects while following the player.

**Database links:**
https://www.wowhead.com/quest=25325/through-the-dream

**Comment by Afgann** [comment]
fixed
