### ISSUE TITLE
Through the Dream (quest npc bug)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#783]
**Description:**
The quest npc Arch Druid Fandral Staghelm stays with the player after abandoning the quest but when the quest is re-accepted the npc version of the npc that continued to follow the player disappears and a new version of the npc spawns and follows the player in the dream phase of the quest.

**How to reproduce:**
accept and abandon the Through the Dream quest and re-accept the quest to have a new version of the quest npc Arch Druid Fandral Staghelm follow you in the dream phase of the quest.

**How it should work:**
The npc Arch Druid Fandral Staghlem should not continue to follow the player after abandoning the quest and should disappear 
when the player un-phases.

**Database links:**
https://www.wowhead.com/quest=25325/through-the-dream

**Comment by Afgann** [comment]
fixed
