### ISSUE TITLE
Through the Dream quest (Visual quest bug)

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#785]
**Description:**
The green hue that is supposed to be around the edges of the players screen  while phased into the emerald dream during the quest does not show.

**How to reproduce:**
Accept the quest Through the Dream and observe the edges of the players screen.

**How it should work:**
A green hue is supposed to show around the players screen while phased into the emerald dream during this quest.

**Database links:**
https://www.wowhead.com/quest=25325/through-the-dream

**Comment by Afgann** [comment]
works fine
