### ISSUE TITLE
[QUEST] Never Trust A Big Barb And A Smile

### ISSUE THREAD

**Issue by CarducciVDM** [GameFreedomGG/Maelstrom#786]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Durotar, Sen'jin Village Quest.
When totem is placed, Scorpion fixates to it and applies It's "venom" but there is no quest credit given

**How to reproduce:**
Just place totem, Scorpion aggroes to it and It's clearly visible that the animation of the scorpion is cast, but no quest credit is awarded.
E : After further testing it sometimes awards credit, but is very inconsistent

**How it should work:**
Totem should be placed while attacking scorpions, player should stay close to the totem and when the scorpion casts It's venom credit is awarded, multiple scorpion can be used for the same totem.

**Database links:**
https://www.wowhead.com/quest=25165/never-trust-a-big-barb-and-a-smile

**Comment by Afgann** [comment]
fixed
