### ISSUE TITLE
[QUEST] Breaking the Chain

### ISSUE THREAD

**Issue by CarducciVDM** [GameFreedomGG/Maelstrom#787]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
A "supply line" of NPCs is carrying crates. NPCs are spawning to frequently and NPCs are stacking on top of eachother.
I will link a screenshot

**How to reproduce:**
Just random spawns when Observed, NPCs stacked on top of each other sometimes.
[https://imgur.com/a/gnKQYgA
](url)

**How it should work:**
Should not stack on top like shown in screenshot.

**Database links:**
https://www.wowhead.com/quest=25167/breaking-the-chain

**Comment by UltraNix** [comment]
Cannot reproduce it.
