### ISSUE TITLE
Return to Graveyard always ports you to Barrens/Westfall

### ISSUE THREAD

**Issue by Pocokk** [GameFreedomGG/Maelstrom#791]
**Description:**
Title, no matter where you are. Once you sickress with the Spirit Healer (as you can't do anything else) you got teleported back at the previous graveyard.

**How to reproduce:**
Die inside a dungeon, release spirit and push that button at the top of the screen.

**Comment by UltraNix** [comment]
Works okay. Need more info about that dungeon.

**Comment by Pocokk** [comment]
> Works okay. Need more info about that dungeon.

Is there a way to grant me a PTR access to help out further?

**Comment by UltraNix** [comment]
There is no PTR.
