### ISSUE TITLE
The Abyssal Maw - Losing breath outside the dungeon/in the hub area.

### ISSUE THREAD

**Issue by Pocokk** [GameFreedomGG/Maelstrom#792]
**Description:**
When you go outside the dungeon called Throne of the Tides, you start losing your breath and eventually die.

**How to reproduce:**
Walk outside the dungeon.

**How it should work:**
There should be breathable air there.

**Database links:**
https://wowpedia.fandom.com/wiki/Abyssal_Maw

**Comment by UltraNix** [comment]
Fixed.
