### ISSUE TITLE
[Quest] [Deepholm] Without a Captain or Crew and On Second Thought, Take One Prisoner and Some Spraining to Do

### ISSUE THREAD

**Issue by pkumar313** [GameFreedomGG/Maelstrom#793]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The bottle of whiskey is nowhere to be found on the gunship, pathing of all the Twilight Saboteurs are messed up, Mor'norokk the Hateful was not in the ship but the quest was still completable. Some Spraining to Do was auto completed as well right after accepting the quest

**How to reproduce:**
![image](https://user-images.githubusercontent.com/54285227/133161391-fefcfd93-a91c-4904-bfd9-e9b7cfd3829d.png)
![image](https://user-images.githubusercontent.com/54285227/133161620-478d0028-4bd3-4004-9e64-3778b8a1505d.png)

**How it should work:**
https://www.youtube.com/watch?v=2IxxaHapcKM
https://www.youtube.com/watch?v=TIKoHDqCjFM&list=PLj1cxYTRfVukVJJVmEWdGpvu1wttdMxWG&index=89
https://www.youtube.com/watch?v=DsGAOAfHa2s&list=PLj1cxYTRfVukVJJVmEWdGpvu1wttdMxWG&index=91

**Database links:**
https://www.wowhead.com/quest=26427/without-a-captain-or-crew
https://www.wowhead.com/quest=26250/on-second-thought-take-one-prisoner
https://www.wowhead.com/quest=26254/some-spraining-to-do

**Comment by UltraNix** [comment]
`The bottle of whiskey is nowhere to be found on the gunship`
Works okay.
