### ISSUE TITLE
[Dungeon Lost City of Tol'vir

### ISSUE THREAD

**Issue by pkumar313** [GameFreedomGG/Maelstrom#794]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Zoned into the dungeon to complete the quest Return to the Lost City and I'm unable to zone back out the dungeon, character stuck is not working as well. I guess I will heart out but this needs to be fixed

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Afgann** [comment]
works fine
