### ISSUE TITLE
[QUEST] Thrill of Discovery

### ISSUE THREAD

**Issue by Pocokk** [GameFreedomGG/Maelstrom#795]
**Description:**
The marked location of Northern and Southern Hieroglyphs are wrong.

**How to reproduce:**
Go to the marked spots and try to discover them, it won't happen because the credit giving NPC is not there.

**How it should work:**
The "credit giving hidden npc" is missing at both locations, they are at the other corners. 

**Database links:**
https://www.wowhead.com/quest=27511/the-thrill-of-discovery

**Comment by Pocokk** [comment]
> 
> 
> I already did that quest, works ok but next 2-3 quests need to be rewritten.

I try to fly to the marked locations and it just don't complete at all. Tried to relog, tried to delete cache folder.

**Comment by xHAGENx** [comment]
Probably marked locations on map are wrong , check on wow head where exacly that location is.

**Comment by Afgann** [comment]
fixed
