### ISSUE TITLE
[QUEST] Lessons From the Past

### ISSUE THREAD

**Issue by Pocokk** [GameFreedomGG/Maelstrom#796]
**Description:**
The npc doesn't give the quest.

**How to reproduce:**
Be on the "Thrill of Discovery" quest (same phase) and try to pick it up from the NPC, it's not there.

**How it should work:**
If you are in the same phase with "Thrill of Discovery" you should able to pick it up.

**Database links:**
https://www.wowhead.com/quest=27541/lessons-from-the-past#comments:id=1604713

**Comment by xHAGENx** [comment]
Atm ppl could take that quest after making thrill of discovery.

**Comment by UltraNix** [comment]
`Thrill of Discovery` must be done.
