### ISSUE TITLE
[SPELL] Dormus's Rage phase change

### ISSUE THREAD

**Issue by Pocokk** [GameFreedomGG/Maelstrom#797]
**Description:**
When you find the good mysterious camel figurine npc and you got teleported to Feralas, you get this debuff that put you into a different phase, however once you are done there and go away, the phase is stuck on you, can't see any NPC or anything. Once the debuff expires, everything goes back to normal (maybe a relog is required too) 
**How to reproduce:**
Put yourself the Dormus's Rage (93269) debuff and try to find any NPC, you won't be able to.

**How it should work:**
Once you kill Dormus the Camel-Hoarder, the debuff should disappear.

**Database links:**
https://www.wowhead.com/npc=50245/dormus-the-camel-hoarder
https://www.wowhead.com/spell=93269/dormus-rage

**Comment by Afgann** [comment]
fixed
