### ISSUE TITLE
(Q) Oh, Deer!

### ISSUE THREAD

**Issue by Sodah96** [GameFreedomGG/Maelstrom#799]
**Description:**
- Injured Fawn are being targeted by Twilight Inferno Lords + Raging Firestorms killing them in seconds

**How to reproduce:**
Click on the Fawn and you will see that mobs will instantly target them far far away.

**How it should work:**
Should be immune 

**Database links:**
https://www.wowhead.com/quest=25392/oh-deer

**Comment by Afgann** [comment]
fixed
