### ISSUE TITLE
[HUNTER] [PET] + Hunter Raid Buffs

### ISSUE THREAD

**Issue by xHAGENx** [GameFreedomGG/Maelstrom#806]
**Description:**
All buffs which hunter could get from other players, are not castable on hunter pets, but pets should get every buff hunter stats (like ap / meele haste / 3% dps etc) its work good probably i dont have oportunity to test that all.
But every raid buff which hunter gives to raid (Trueshot Aura / Hunting Party / Ferocius Inspiration) stack twice on their pets.
![image](https://user-images.githubusercontent.com/90351303/133897543-ab99c00d-1c45-4ec3-b69d-ea1f01ce7195.png)
![image](https://user-images.githubusercontent.com/90351303/133897550-db06a11c-9767-455a-8dab-67583ef4190d.png)

**How to reproduce:**
Tame pet, have dual spec with some raid buff, second spec without talents and just compare.

**How it should work:**
Every hunter aura should effect on pet only once.

**Database links:**

**Comment by UltraNix** [comment]
I cannot reproduce it. For me works okay. Every stats looks okay.
