### ISSUE TITLE
[HUNTER] Trap spawn location  without launcher

### ISSUE THREAD

**Issue by xHAGENx** [GameFreedomGG/Maelstrom#812]
**Description:**
This is spawn location of trap when I used that without launcher.
![image](https://user-images.githubusercontent.com/90351303/133923645-21667674-e6d2-4a57-a5d9-40008b1a1410.png)

**How to reproduce:**
Just use some hunter traps.

**How it should work:**
Trap placed without launcher should be spawned before hunter.
0:47 / 5:32 / 6:39
https://www.youtube.com/watch?v=6U4zveFkK7A
**Database links:**

**Comment by UltraNix** [comment]
Cannot reproduce it - works okay to me.
