### ISSUE TITLE
(ULDUM) Invisible underwater drowning area underground

### ISSUE THREAD

**Issue by Sodah96** [GameFreedomGG/Maelstrom#815]
**Description:** Invisible underwater drowning area underground

**How to reproduce:** Stand next to High Priest Amet

**How it should work:** This underground tunnel should be a normal ground area.

**Database links:**
![image](https://user-images.githubusercontent.com/90869655/133925349-f3e15a3b-d3e3-484b-9496-604cec0585a7.png)

**Comment by UltraNix** [comment]
Fixed.
