### ISSUE TITLE
(Q) ULDUM - Gnomebliteration

### ISSUE THREAD

**Issue by Sodah96** [GameFreedomGG/Maelstrom#817]
**Description:** After completing the quest, quest orb mob disappears and you cannot turn in the quest until you relog then it spawns back.

**How to reproduce:** Complete the Gnomebliteration quest and return to givein quest marker. 

**How it should work:** The orb should respawn without relogging

**Database links:**
https://www.wowhead.com/quest=27779/gnomebliteration

**Comment by xHAGENx** [comment]
Player accepting quest enter special layer, and after leaving the orb he should to normal layer.
