### ISSUE TITLE
[HUNTER] [SPELL] Camouflage

### ISSUE THREAD

**Issue by xHAGENx** [GameFreedomGG/Maelstrom#820]
**Description:**
Comouflage doesn't affects on enemy npc pull range.
![image](https://user-images.githubusercontent.com/90351303/133928475-eec1dc11-1000-4bdc-82d0-c46db4f45e03.png)

**How to reproduce:**
1. Be hunter 
2. Lern Camouflage
3. Use Camouflage
4. get close to the hostile NPC

**How it should work:**
https://www.youtube.com/watch?v=IDVTNdj22Zk

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=51753#issues

**Comment by UltraNix** [comment]
It works okay, but only for creatures <= 80 lvl. I believe it's blizzlike.
