### ISSUE TITLE
(Q) DEEPHOLM - Petrified Delicacies

### ISSUE THREAD

**Issue by Sodah96** [GameFreedomGG/Maelstrom#822]
**Description:** When you are picking up bats from the ground, there is some inner ability cooldown that prevents you to successfully pick them up one after another

![image](https://user-images.githubusercontent.com/90869655/133935396-e3a6a1db-4943-485d-a06e-765cd9633c4a.png)

**How to reproduce:**
Pick up the first bat then go the the new one and pick it up. You will get spell error that the ability is not ready yet.

**How it should work:**
Normally pick them up 1 after another without getting spell error.

**Database links:**
https://www.wowhead.com/quest=26507/petrified-delicacies

**Comment by Afgann** [comment]
fixed
