### ISSUE TITLE
[HUNTER] Melee attack power scaled from agility 

### ISSUE THREAD

**Issue by xHAGENx** [GameFreedomGG/Maelstrom#826]
**Description:**
Hunter doesn't get any melee atack power from agility.
![image](https://user-images.githubusercontent.com/90351303/134015872-52881e9f-de0a-4780-8cf9-2c194fb49388.png)

**How to reproduce:**

**How it should work:**
Hunter should get 1 melee attack power and 2 ranged attack power for each agility.

**Database links:**
https://wowpedia.fandom.com/wiki/Attack_power#Hunter
"Agility increases melee attack power for Rogues and Shamans, while Hunters, Rogues and Warriors gain ranged AP for every point of agility. *Druids gain AP from both strength and agility, while in feral form."

**Comment by Godmatik** [comment]
That link clearly states that hunters gain 2 ranged attack power per agility only.

**Comment by xHAGENx** [comment]
> That link clearly states that hunters gain 2 ranged attack power per agility only.
You are blind or are u kidding me.
There are more than once mentioned about meele attack power on hunters. Even in table u have - (Level x 2) + (Strength - 10) + **(Agility - 10).**
