### ISSUE TITLE
Mount Hyjal, Wolf's Run (possible npc bug) Twilight Proveditor

### ISSUE THREAD

**Issue by Kreanor** [GameFreedomGG/Maelstrom#828]
**Description:**
The spawn rate of this npc seems unusually high, this may be a bug but i am not certain if this is a bug.

**How to reproduce:**
observe the spawn rate of the npc at the bridge that passes over a waterfall in Mount Hyjal on Wolfs Run.

**How it should work:**
I am not certain what the spawn rate should be.

**Database links:**
https://www.wowhead.com/npc=39436/twilight-proveditor

**Comment by Afgann** [comment]
fixed
