### ISSUE TITLE
arms in the air when mount summoning

### ISSUE THREAD

**Issue by Pallaladin** [GameFreedomGG/Maelstrom#83]
**Description:**

when using mount our character get stuck in the animation with the arms in the air

**How to reproduce:**

summon an hawkstrider, didn't try with other mount

**How it should work:**

it shouldn't stuck our character like this
![image](https://user-images.githubusercontent.com/51074371/114438075-95dcba00-9bc7-11eb-9f32-92dc34698903.png)

**Comment by UltraNix** [comment]
Can't reproduce it.
