### ISSUE TITLE
[Hunter] Starting orc pet does not have growl

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Maelstrom#830]
The starting "young boar" pet you have when you create a level 1 Orc hunter does not have growl and can't hold aggro on mob, so it always runs straight to you.

It should start with growl and hold aggro - even before you get access to control the pet at level 10.

https://www.youtube.com/watch?v=dOiF960YyI0

**Comment by xHAGENx** [comment]
Confirmed.
+ Pet should be set on assist from 1lvl by default
+ On 1. lvl there also is visible big scaling problem ( connected with #804 #805) - Hunter 96hp pet 516
![image](https://user-images.githubusercontent.com/90351303/135424666-da3de9b8-f5c8-4c00-903c-a19dc5619047.png)
