### ISSUE TITLE
[Death Knight ZONE][Quest][Tonight We Dine in Heavenshire]

### ISSUE THREAD

**Issue by Liadryns** [GameFreedomGG/Maelstrom#834]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Saronite Arrow have 10 s opening time

**How it should work:**
Saronite Arrow opening time should be instant
https://www.youtube.com/watch?v=KlTDzmnnQ70

**Database links:**
https://www.wowhead.com/quest=12679/tonight-we-dine-in-havenshire
https://www.wowhead.com/object=190691/saronite-arrow

**Comment by Afgann** [comment]
works fine
