### ISSUE TITLE
[Quest][Vashj'ir] Intro quest

### ISSUE THREAD

**Issue by Liadryns** [GameFreedomGG/Maelstrom#837]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After complete quest "Warchief's Command: Vashj'ir!"  Commander Thorak doesn't have more quest . making quest chain undoable 
**How to reproduce:**
Pick quest from Warchief's Board "Warchief's Command: Vashj'ir!" and speak with Commander Thorak

**How it should work:**
Commander should give u quest "Call of Duty" 

**Database links:**
https://www.wowhead.com/quest=25924/call-of-duty
https://www.wowhead.com/npc=41621/commander-thorak

**Comment by Pocokk** [comment]
The zone itself wasn't done back then, only this initial quest was done.

**Comment by UltraNix** [comment]
https://www.wowhead.com/quest=28816/to-the-depths required.
