### ISSUE TITLE
[Quest] Magma monarch

### ISSUE THREAD

**Issue by malekd1** [GameFreedomGG/Maelstrom#839]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
tortolla isn't helping ,doesn't appear either

**How to reproduce:**

**How it should work:**
torotolla should come help killing king Moltor

**Database links:**
https://www.youtube.com/watch?v=m-IRXiHRR9Y

https://www.wowhead.com/quest=25550/magma-monarch

**Comment by xHAGENx** [comment]
Duplicated with #736
