### ISSUE TITLE
Rebellious Trolls stuck bug. 

### ISSUE THREAD

**Issue by Z4-Zaiks** [GameFreedomGG/Maelstrom#84]
**Description:**
The Rebellious Trolls on Kezan, in The Kaja ' mine AFTER, The death wing encounter, which leads to the quest: Liberate the Kaja' mine. The Trolls will note your precemse and put you in combat. However, The Trolls Remain stuck at their spawn point, and will not move nor attack you. 

**How to reproduce:**
Complete The quests in The goblin starter zone Kezan until The Football course quest where in you will encounter Deathwing (unsure what The Name of said quest is.) After that, you will process to the HQ, then speak to Gallywix. After that, The HQ area will alter, and you will be given a quest; Liberate the Kaja 'mine. Where you will go down to the Kaja' mine and gather chunks of Kaja mite. It is here where these rebellious Trolls stans as hostile, but will not move. 

**How it should work:**
Obviously, The Trolls should move and actually attack. As to how, I do not know. Perhaps there is problems with some coding, but I dont know. As for any comments, videos etc, I was unable to find anything leading to any advance om The matter.

**Comment by HerodDev** [comment]
https://www.wowhead.com/npc=35294/rebellious-troll
