### ISSUE TITLE
Movement Related Issues

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#850]
This ugly visual of them skipping up and down when traveling heights, I think just related to flying mobs.
https://i.imgur.com/QLkPn8L.mp4

This mob just got stuck and refused to keep moving from his location. Idk if it is related to movement system or mob.
https://i.imgur.com/lVr0LSa.mp4

Height issue is very abusable tho Can solo many bosses with this.
https://i.imgur.com/r91rQlC.mp4
https://i.imgur.com/wVh9qD5.mp4

Some strange behavior.
https://i.imgur.com/vJ5oTDS.mp4

Shouldn't mobs go straight for you? They're taking these choppy turns in their pathing.
https://i.imgur.com/KXSHDox.mp4

Can bug out mobs pathing also. (This is hard to reproduce)
https://i.imgur.com/FQWC47p.mp4
https://i.imgur.com/727ZWfN.mp4
https://i.imgur.com/9xZoJYM.mp4

These guys fly, go through the ground, and after following the path from Stormwind to the bridge of Eastvale Camp through the road they don't head back same way, instead they just go straight through the forest through trees and terrain back to original start position of their path outside SW gates.
https://i.imgur.com/As68oPe.mp4

Also noticed one of the normal guards are walking under the ground in his path, corrects once inside SW tho, also doesn't stop when you talk to him.
https://i.imgur.com/P9wkEeQ.mp4

**Comment by UltraNix** [comment]
All of these problems should be resolved. The last ones (about guards) are related to their bad paths - please report them as a separate report.
