### ISSUE TITLE
Goblin Gumbo Kettle

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#854]
https://tbc.wowhead.com/item=33219/goblin-gumbo-kettle
When you place the Kettle and right click it you get a consumable item which is supposed to give you a green fire breath effect now and then. But it gives you the bubble gum visual instead.

**Comment by UltraNix** [comment]
Works okay - you need to kill something that gives you honor/experience (33% chance of that effect).

**Comment by WarlordXecc** [comment]
https://youtu.be/LNuzg2G1G2k?t=54

Yeah here is video from MoP Retail confirming the Goblin Gumbo. Maybe they changed the item after TBC, or Wowhead info is just wrong.

**Comment by WarlordXecc** [comment]
Actually it worked the same way on Atlantiss 2.4.3 too so I think Wowhead is just wrong.

**Comment by UltraNix** [comment]
Okay - I think I see the problem.

**Comment by WarlordXecc** [comment]
Blizzard must have made some spaghetti with their DBCs then.
https://youtu.be/5hju9GTvKEo?t=19
There are tons of videos on YouTube showing it working the way I described.

**Comment by WarlordXecc** [comment]
There is an issue with the effect from Goblin Gumbo Spell ID 42760
When the animation/green breath effect is activated it interrupts any sort of cast that the player is doing. So if you're trying to mount up or cast a Frostbolt then the animation will stop it.
