### ISSUE TITLE
Speedbarge Diving Helm

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#858]
![WoWScrnShot_030622_193751](https://user-images.githubusercontent.com/66841484/161970576-5493c0bf-9863-4c5a-a488-0f11415a9c58.jpg)
https://www.wowhead.com/spell=75627/speedbarge-diving-helm
Speedbarge Diving Helm 75651
It is supposed to leave a trail behind your feet but instead it goes sideways.
Also, I want to create a Shop Item called "Anti-Gravity Boots" which would allow you to switch running animation anywhere in the world to that of Speedbarge Diving Helm when below 1K but without the Bubble on head, and maybe trail. It should be able to be turned on/off at will by clicking the item. If you know how to do this feel free.

**Comment by UltraNix** [comment]
That item is not available ingame anymore. The visual of that spell is clientside. That spell can be casted in Thousand Needles.
