### ISSUE TITLE
Alliance Deadmines Quests

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#859]
![WoWScrnShot_042022_232221](https://user-images.githubusercontent.com/66841484/164576124-330b44b2-7d75-4afe-9aff-48e3a1a13391.jpg)
Allliance doesn't have any quests in Deadmines. The quest giver gives the starting quest to Westfall, maybe wrong spawn ID of same quest giver idk.

**Comment by UltraNix** [comment]
![obraz_2022-09-30_110516224](https://user-images.githubusercontent.com/80540499/193235214-cbd0a034-8e7e-442a-a87f-94343d133628.png)
Works okay now.
