### ISSUE TITLE
Gnomeregan Quests

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#861]
![WoWScrnShot_042022_234617](https://user-images.githubusercontent.com/66841484/164576279-8956b18c-69bc-46f3-9da0-1178c1f2ec75.jpg)
Gnomeregan doesn't have any quests for Alliance or Horde.

**Comment by UltraNix** [comment]
![obraz_2022-09-30_111913413](https://user-images.githubusercontent.com/80540499/193238045-e7a04d69-0a97-4f4b-8a67-60a4191fc487.png)
Works okay now.
