### ISSUE TITLE
Explore Achievements

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#869]
![WoWScrnShot_042922_123758](https://user-images.githubusercontent.com/66841484/166070491-7b6fbe00-9245-452d-9a68-b5398bc19723.jpg)

When I ran around in Hillsbrad I ended up getting Explore Durotar, Northern Barrens and Uldum achievement. I've ran into many such instances before with exploration achievements just being granted from zones I am not even in, sometimes never even been in so it is a somewhat global issue.

**Comment by UltraNix** [comment]
@WarlordXecc Cannot reproduce it on my local. Just run over the hilsbrad, discovered all areas and got only Hilsbrad achievements

**Comment by gaga-whitemane** [comment]
![WoWScrnShot_091522_190718](https://user-images.githubusercontent.com/4954400/190467943-912b10d4-d62a-4030-a9fb-5ab5dc450653.jpg)
Mulgore's achievement for being in Durotar seems that something is still wrong with it.

**Comment by UltraNix** [comment]
@gaga-whitemane New char?

**Comment by WarlordXecc** [comment]
Just got Explore Northern Barrens while running around in Desolace on a fresh character, so the bug is still present.

![WoWScrnShot_102022_010940](https://user-images.githubusercontent.com/66841484/196821385-c5b4790e-0775-4e3f-a91b-fb9998f1745a.jpg)
