### ISSUE TITLE
Enthralled Val'kyr

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#870]
![WoWScrnShot_042922_123600](https://user-images.githubusercontent.com/66841484/166070773-d41a607b-8a0d-44d5-8abd-264f431bb22f.jpg)

https://cata-twinhead.twinstar.cz/?npc=45080
As soon as I enter "Felstone Field" in Western Plaguelands it gives me a Enthralled Val'kyr as Pet which will automatically attack everything in sight. This event might be part of a quest or something, not sure. Definitely should not appear like this for no reason tho.

**Comment by UltraNix** [comment]
It's summoned during https://www.wowhead.com/quest=26937/when-death-is-not-enough and https://www.wowhead.com/quest=26938/combat-training.
Tested and NPCs are summoned only during these quests.

**Comment by WarlordXecc** [comment]
> It's summoned during https://www.wowhead.com/quest=26937/when-death-is-not-enough and https://www.wowhead.com/quest=26938/combat-training. Tested and NPCs are summoned only during these quests.

Hmm yeah, seems he doesn't spawn randomly anymore.
I tried adding myself those quests but he still didn't spawn, maybe I need to pick it up like a player.
Can you make sure you can't take the Val'kyr with you outside Western Plaguelands? You could bring her everywhere before.
