### ISSUE TITLE
NPC Caster Mob Behavior

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#873]
https://cdn.discordapp.com/attachments/960987276614185050/970399094268907530/2022-04-29_12-45-55.mp4

Caster Mobs won't run after you while not casting spells. For example by creating distance when I aggro him he won't follow my path to keep auto attacking as I run away. And if you interrupt his cast then he will just stare at you from a distance until he is able to start casting again instead of switching to melee and chasing me down until that happens.

**Comment by UltraNix** [comment]
I'm gonna do some generic solution, but thousands of scripts require rewrite.
