### ISSUE TITLE
Seal of righteousness - scale dmg

### ISSUE THREAD

**Issue by adorovsky** [GameFreedomGG/Maelstrom#874]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Seal of righteousness doesn't scale with lvl. At lvl 7 should add +3 dmg instead +2 like now.

**How to reproduce:**

**How it should work:**
Should scale with lvl - there is info on "buff" with specific dmg.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=20154

![WoWScrnShot_063022_221549](https://user-images.githubusercontent.com/22754760/176771824-802b5e20-2e6c-4562-a0ea-722847acf400.jpg)

**Comment by UltraNix** [comment]
It scales with AP and SPH, not level. Just wear better gear.
