### ISSUE TITLE
Ainamiss animation issue

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#876]
Ainamiss is missing animations, just gliding forward.
https://cata-twinhead.twinstar.cz/?npc=47386

![WoWScrnShot_091622_174852](https://user-images.githubusercontent.com/66841484/191835135-9f040cc6-c506-4183-8b64-2664829673d0.jpg)

**Comment by UltraNix** [comment]
@WarlordXecc What "missing animations"?

**Comment by UltraNix** [comment]
Hmm, on my local works okay.

**Comment by WarlordXecc** [comment]
> Hmm, on my local works okay.

Hmm, I restarted server and it works now. Not sure if maybe it breaks after a certain amount of time has passed or something. Idk, not very important bug either I'll close it for now and reopen if I notice it again.
