### ISSUE TITLE
Warcaller Gorlach Pathing

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#878]
Warcaller Gorlach has a really fucked up pathing making him fly through the sky across Orgrimmar.
https://cata-twinhead.twinstar.cz/?npc=10880

![WoWScrnShot_092122_210611](https://user-images.githubusercontent.com/66841484/191835548-bbdda56e-291c-4fcc-b6fe-ea4c306a8ccc.jpg)

**Comment by UltraNix** [comment]
Already fixed.

**Comment by WarlordXecc** [comment]
The path he takes is good now, but it seems his height is too high or has the wrong animation. Because as he patrols through Orgrimmar he constantly has the falling animation.

**Comment by WarlordXecc** [comment]
Still not fixed

https://user-images.githubusercontent.com/66841484/198069680-40fa70e3-09d8-4084-a3ba-dfeed7b15a6d.mp4
