### ISSUE TITLE
Desolation Raider

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#887]
https://cata-twinhead.twinstar.cz/?npc=37922
Another mob that has a buff automatically activated when you're close... 
There has to be some global issue causing this, the amount of mobs I find with random buffs/debuffs activated as soon as you move close to them is silly at this point. 

![WoWScrnShot_092422_120547](https://user-images.githubusercontent.com/66841484/192130858-b6fde9ec-93d9-4a64-b547-202348757651.jpg)

**Comment by UltraNix** [comment]
@WarlordXecc There is no generic solution - just wrong scripts. The only way to fix is to report them all.
