### ISSUE TITLE
Lil' Tarecgosa Pet

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#889]
Lil' Tarecgosa ID 71033 is not consumed when learned. This is a big problem as we've removed Soulbound from the server so people can learn it, trade it to people which will lead to them learning it.

**Comment by UltraNix** [comment]
This item is bound to account. Cannot be placed in AH or traded/mailed to other accounts.

**Comment by WarlordXecc** [comment]
You misunderstand, as I said we have removed Soulbound all together from ALL items. This is so you can for example buy Store mounts/pets and place them on Auction House or simply give away to a friend.
We're working on making all Mounts and Pets you learn account-wide just like in MoP so there is no use for this Cataclysm Account Wide system of simply sending your items to other characters manually.

https://cdn.discordapp.com/attachments/960987276614185050/1024239801077080095/2022-09-27_10-40-50.mp4
^Look at this video as an example.

https://github.com/GameFreedomGG/Maelstrom/issues/855
^Two of the items from this issue are also still not being consumed. 

Onyxian Whelpling 49362 https://www.wowhead.com/item=49362/onyxian-whelpling
Blue Murloc Egg 20371 https://www.wowhead.com/item=20371/blue-murloc-egg

**Comment by UltraNix** [comment]
@WarlordXecc Where/When did you removed it? I don't see any changes in DB/core.

**Comment by UltraNix** [comment]
I don't get it. So you want people to trade it/place on AH or not?

**Comment by WarlordXecc** [comment]
Ohh I see, we made this change over a year ago so maybe they never put it on the github idk.
But yes players should be able to trade it, but it should be consumed so you can't trade it to others infinitely. If one player learns the Pet then it should disappear.
This is so players don't need to spam world chat like "SELLING DONATION POINTS" and risk getting scammed when using a Website Gift function like on other servers as Atlantiss.
So player can for example tell another he wants you to buy him Pet from the store, and then this player trades him the pet for some gold, or maybe he sells it on Auction House or something.
But if it doesn't consume at all then one player can buy the pet, and give it to every single person on the server so everyone has it.

**Comment by UltraNix** [comment]
Okay. Thx for clarification
