### ISSUE TITLE
Vanishing Projectiles

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#895]
https://cata-twinhead.twinstar.cz/?spell=1856

When you use Vanish during a projectiles travel time it should make the projectile not hit at all.
As long as you Vanish at least 0.1 seconds before a projectile actually hits your body then it should simply do nothing.
In the video I posted you'll see that the Death Coil still deals damage and CCs me even tho I Vanished it.

https://user-images.githubusercontent.com/66841484/193077032-63f28cdd-25d1-407e-9821-40abbdfa72be.mp4

**Comment by UltraNix** [comment]
Are you sure?:
https://www.mmo-champion.com/threads/700379-Why-is-the-broken-vanish-fix-not-easy/page2
`...and you shouldn't be able to vanish a missile/DoT/incoming spell anyway.`

**Comment by UltraNix** [comment]
`For the first 3sec after vanishing, damage and harmful effects received will not break stealth`
We can assume that spells can hit and damage target, but will not remove stealth.

**Comment by WarlordXecc** [comment]
> Are you sure?: https://www.mmo-champion.com/threads/700379-Why-is-the-broken-vanish-fix-not-easy/page2 `...and you shouldn't be able to vanish a missile/DoT/incoming spell anyway.`

This thread is Pre-Cata complaining about Dot damage taking them out of stealth which is true :
https://wotlk.evowow.com/?spell=1856

Not sure why they're saying incoming spell would tho? It is true something like Shadowfury will still hit someone using Vanish since it is not a projectile, but vanishing projectiles is a feature that existed all the way since Vanilla.
It is one of the few features that requires a high skillcap to use frequently. I myself mained Warlock for 18 years and understand the pain of my Death Coil getting Vanished.

Here is video from Classic :
https://www.youtube.com/watch?v=MHIlGfUwjDg&ab_channel=Vargath

Video from Arena-Tournament :
https://youtu.be/XG-0PtFH-tU

Here is a video about Shadowmeld doing similar stuff :
https://youtu.be/Lop6sr9SOpw

I looked through Reckful 3 compilation from Cata but sadly didn't contain any clips vs Warlocks, but gamepedia shows no change in logs anyway so idk why it would be different now.
