### ISSUE TITLE
Ice Block vs Faerie Fire

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#896]
https://cata-twinhead.twinstar.cz/?spell=45438
https://cata-twinhead.twinstar.cz/?spell=770
https://cata-twinhead.twinstar.cz/?spell=16857

Ice Block does not remove Faerie Fire.

**Comment by UltraNix** [comment]
Source of this info?

**Comment by WarlordXecc** [comment]
> Source of this info?

To clarify, it **should** remove Faerie Fire, but it does not. I tried to use for example Corruption, Moonfire, Death Coil, and many other Debuffs and Ice Block removes all except Faerie Fire for some reason. Ice Block should remove Faerie Fire also.
