### ISSUE TITLE
Frenzied Regeneration

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#897]
https://cata-twinhead.twinstar.cz/?spell=22842

Frenzied Regeneration is not converting Rage into Health.
The Max Health increase works, but the healing during its Duration is not.

https://user-images.githubusercontent.com/66841484/193079248-6459ade8-714c-403b-86e2-3d3d3a699350.mp4

**Comment by Afgann** [comment]
fixed
