### ISSUE TITLE
Killing Spree Bug

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#898]
https://cata-twinhead.twinstar.cz/?spell=51690

Killing Spree can be activated regardless of enemies being close to you or not.
It should tell you you're outside of range of your target / no targets available.

https://user-images.githubusercontent.com/66841484/193080228-5d1a568e-2cc1-4b15-8d5b-4d5b51a6f6a4.mp4

**Comment by Afgann** [comment]
fixed
