### ISSUE TITLE
Everything Immune to Bleeds

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#899]
Every single mob in the game is Immune to Bleeds.
Training Dummies, Animals, Humanoids, Demons, you name it... There are very few enemies in WoW that should be immune to Bleeds, I know stuff like Elementals are.

Edit: Players are also immune to all Bleeds!! This is a new bug, not sure where it came from but this used to work fine.

https://user-images.githubusercontent.com/66841484/193082860-3e87b793-42bc-4055-ad82-c5600ff49e6e.mp4

https://user-images.githubusercontent.com/66841484/193082868-c1dbcc79-c636-4167-a085-c69f148c3c95.mp4

**Comment by Afgann** [comment]
fixed
