### ISSUE TITLE
Chaos Bolt Pierce

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#905]
https://cata-twinhead.twinstar.cz/?spell=50796

Chaos Bolt should ignore all absorb effects but it does not.

https://user-images.githubusercontent.com/66841484/193115850-1c71d2a5-afc1-474d-9b17-4f14029b4b46.mp4

**Comment by UltraNix** [comment]
![obraz_2022-10-05_112306464](https://user-images.githubusercontent.com/80540499/194027204-bab99756-62fa-4fb8-adaa-423bc578fd7c.png)
Works okay.
