### ISSUE TITLE
Consecration broken

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#906]
https://cata-twinhead.twinstar.cz/?spell=26573

Consecration does not work at all. The Spell Visual appears but it doesn't deal any damage, does not miss or anything it just doesn't register as a hit.

https://user-images.githubusercontent.com/66841484/193116268-b973f2b4-a72f-4074-ac0c-8d0e1e959abf.mp4

**Comment by Afgann** [comment]
fixed
