### ISSUE TITLE
Farwatcher's Glen Missing Patrols

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#922]
I've provided a list of screenshots with .npc info of all the mobs which I assume have missing patrols.
It's not impossible a few of them simply has incorrect spawn locations & rotations. I am just assuming that the NPCs standing in weird locations to be missing their waypoints.

![WoWScrnShot_100422_134553](https://user-images.githubusercontent.com/66841484/193820716-df63328f-d503-41c1-83c3-06982198aed2.jpg)
![WoWScrnShot_100422_134556](https://user-images.githubusercontent.com/66841484/193820719-f0a4dc6b-8618-4b61-bf52-b364e9d47085.jpg)
![WoWScrnShot_100422_134558](https://user-images.githubusercontent.com/66841484/193820722-3d45a899-a269-4e92-bd16-4ece38457ee4.jpg)

**Comment by UltraNix** [comment]
Fixed
