### ISSUE TITLE
Mr. D's Wild Ride Quest

### ISSUE THREAD

**Issue by PendingtonFlex** [GameFreedomGG/Maelstrom#93]
**Description:**
After turning in it should either prompt you when speaking with Large Daddy to enter and control it, or just automatically from picking up the quest.

**How to reproduce:**
Grab quest, and be unable to progress on it.
**How it should work:**
@description.

**Comment by HerodDev** [comment]
https://www.wowhead.com/quest=26028/mr-ds-wild-ride

**Comment by HerodDev** [comment]
also fixing similar quest https://www.wowhead.com/quest=25728/mr-ps-wild-ride
