### ISSUE TITLE
Zalduun Very Bad Waypoints

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#957]
It's safe to say at this point that about 90-95% of all Patrols that should be in the game are missing from the Core.
And the ones that actually do exist are 99% of the time broken in ways like this with terrible keyframes for the waypoints. They take weird directions quite often, change speed a lot and just look weird overall.

https://user-images.githubusercontent.com/66841484/193856488-cbf66a26-360b-43dd-be79-db11f5044dca.mp4

**Comment by UltraNix** [comment]
Duplicate of #966

**Comment by UltraNix** [comment]
Duplciate of #966.
