### ISSUE TITLE
Avarus Kharag

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#965]
I'm not sure if this guy has some different kind of random movements or if he has some crazy patrol waypoints, he walks way further than a random movement mob but all his movements also seem so random I can't really tell what the issue is.

![WoWScrnShot_100422_161406](https://user-images.githubusercontent.com/66841484/193865915-bb131826-10b3-494a-91e7-c3f0c11847ca.jpg)

**Comment by UltraNix** [comment]
Already fixed.
