### ISSUE TITLE
Patrols break from interactions.

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#968]
When you interact with an NPC through chatting or shopping then the patrol breaks permanently, they never stop walking again.

https://user-images.githubusercontent.com/66841484/194345086-0f2aabef-7522-4ad8-919e-3afa88dc094b.mp4

**Comment by WarlordXecc** [comment]
Actually I noticed it doesn't permanently break the patrol. But they stand still for approx 2 minutes before starting to talk again. On Retail they start walking again after like 5 seconds.

**Comment by UltraNix** [comment]
I doubt it's 5 sec. Imagine talking to NPC and then it starts walking again after 5 sec and you have to talk to him again and again and again every 5 sec :P

**Comment by WarlordXecc** [comment]
> I doubt it's 5 sec. Imagine talking to NPC and then it starts walking again after 5 sec and you have to talk to him again and again and again every 5 sec :P

To clarify, I mean when you've closed the shop, not when you're still talking.
I went on Retail to verify and that is the case. On our server they stand still for 2-3 minutes straight before continuing their patrol.


https://user-images.githubusercontent.com/66841484/194528897-689c47a1-303a-41ec-862a-757e383bcbcf.mp4

**Comment by UltraNix** [comment]
Okay.

**Comment by UltraNix** [comment]
Sadly, there is no clientside packet telling that nobody is talking to NPC anymore so they can move again.
