### ISSUE TITLE
Thief Catcher Shadowdelve

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#969]
You sure that the Patrols you fixed were from sniffed retail Data? At least that's what GaGa claimed.
I noticed the Patrols that you did fix in Ironforge has the same issues other patrols does, bad waypoints, changing speed, going back and forth changing direction. This is definitely not how they should be patrolling.

https://user-images.githubusercontent.com/66841484/194346175-b882a9e2-f85c-4d69-885e-9c30836ecf44.mp4

https://user-images.githubusercontent.com/66841484/194346243-b4f9b6d7-1b13-4d6a-8608-e763f5a2d146.mp4

The issues with patrols going back and forth is especially noticable on one of the gryphons you fixed :

https://user-images.githubusercontent.com/66841484/194347346-3968dc89-0fa0-420b-af3b-e8bf1d157685.mp4

https://user-images.githubusercontent.com/66841484/194347353-63825aee-3c59-4219-85ed-71141e31ba01.mp4

**Comment by UltraNix** [comment]
Do not report something that is already reported. Problems with changing speed, going back,forth changing direction is a generic problem and will be fixed.

**Comment by WarlordXecc** [comment]
> Do not report something that is already reported. Problems with changing speed, going back,forth changing direction is a generic problem and will be fixed. Duplicate of #966. I don;t know what Ga-Ga claimed.

Well it is not 100% duplicated reports.


https://user-images.githubusercontent.com/66841484/194529294-2a0c9564-bf26-4a2e-8f16-66069f0f2ff1.mp4

Above you see the waypoints on here.

And here you see the waypoints on Retail : https://cdn.discordapp.com/attachments/960987276614185050/1027624872928612503/2022-10-06_18-53-46.mp4

This guy doesn't just walk back and forth slightly here, I think his waypoints are messed up to begin with since he walks back and forth very long distances unlike the generic fast back and forth which looks more like this :


https://user-images.githubusercontent.com/66841484/194529650-5f300f75-b810-43fb-84e6-860d2c87c1d3.mp4

All tho if they're related or not I am not sure, but this one seems different from the rest is all I am saying.
