### ISSUE TITLE
Gnomish Death Ray

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#970]
https://cata-twinhead.twinstar.cz/?item=10645

Gnomish Death Ray should damage yourself during a channel and then damage your target.
Currently it does nothing, the animation shows but no cast bar is shown, doesn't damage yourself, and doesn't damage the enemy.
https://youtu.be/0UGNLtZjCuw

I know it can crit for very high amounts, but I can't find any information on scaling. There are some comments about the spell on Wowhead tho : https://www.wowhead.com/item=10645/gnomish-death-ray#comments

https://user-images.githubusercontent.com/66841484/194923374-6a231594-4e6c-4f3e-a4a0-ca4be78ef03d.mp4

**Comment by Afgann** [comment]
fixed
