### ISSUE TITLE
Goblin Bomb Dispenser

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#971]
https://cata-twinhead.twinstar.cz/?item=10587

This Trinket should spawn a Pet Bomb which charges the first enemy in sight and explodes itself. Currently it does nothing, you can't activate the trinket at all so not sure if Spell itself is broken or not.
https://youtu.be/QZQib3t8Bis

**Comment by Afgann** [comment]
fixed
