### ISSUE TITLE
Gnomish Mind Control Cap

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#974]
https://www.wowhead.com/item=10726/gnomish-mind-control-cap#comments

This hat should make your target becomes like a hunter pet. You have the attack/follow/stay and agressive/defensive/passive buttons.

If you control an NPC, you also get buttons for their abilities (or the first 4, though most monsters have only one or two... if it has 5 abilities it's probably a boss and immune).

When you mind control players, you only get the 6 behavior buttons; the crazy mind control AI takes over from there. Tends to use up big cooldown abilities. So the controlled players should use their abilities, but player has no control of which or when.

Currently it does nothing at all, just goes on Cooldown upon activation against both players and npcs.

https://user-images.githubusercontent.com/66841484/194934522-af1cee16-821b-48c2-a03f-fd4d661229f6.mp4

**Comment by Afgann** [comment]
fixed
