### ISSUE TITLE
Gnomish Shrink Ray

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#975]
https://www.wowhead.com/item=10716/gnomish-shrink-ray#comments

This trinket should shrink the enemy player and reduce his attack power. It has a lot of different malfunction effects as can be explained in Wowhead comments.

Currently does nothing at all, just goes on Cooldown, uses no animation or anything.

https://user-images.githubusercontent.com/66841484/194934833-39cf5165-d87f-4203-a377-d2cc7a26b1ca.mp4

**Comment by Afgann** [comment]
fixed
