### ISSUE TITLE
Larval Acid

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#978]
https://cata-twinhead.twinstar.cz/?item=18512

Larval Acid does not drop from Carrion Devourers or Carrion Grubs. I killed like 50 of them and didn't find any.
NOTE: It is possible that these should no longer drop from these mobs in Cata, I know they did in Wotlk but I want them to drop here regardless due to them being used in some recipes for lvl 60.

**Comment by Afgann** [comment]
fixed
