### ISSUE TITLE
Ranged NPC Combat

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#982]
NPCs which has Ranged alternatives in their combat acts as if they're permanently rooted. If you move into deadzone where you're too close for a ranged attack but too far away from a melee attack they just stand still watching you. This is the case for both Doomforge Dragoon and Anvilrage Officer so pretty sure it is global issue across NPCs.

https://user-images.githubusercontent.com/66841484/196822640-b10e823d-c671-4e13-a673-ee233f5e9dc7.mp4

**Comment by UltraNix** [comment]
As previous - bad AI. Not fixable by generic solution. Just list all mobs affected by this.

**Comment by Afgann** [comment]
So, actually its 3 issues that can appear similarly, 2 of them should be fixed. If there are any other problems with creatures with SmartAI (that aren't on the list posted below) then let me know in new issue.

Third one is as @UltraNix said bad AI, they need to be fixed individually (i'll try to fix them in several batches). Heres the list of broken npcs (should be mostly correct, there may be some false positives):
| Creature Entry  | Creature Name |
| ------------- | ------------- |
|416|Imp|
|458|Murloc Hunter|
|487|Protector Bialon|
|488|Protector Weaver|
|489|Protector Dutfield|
|490|Protector Gariel|
|500|Riverpaw Scout|
|677|Venture Co. Tinkerer|
|699|Bloodscalp Beastmaster|
|752|Marsh Oracle|
|759|Lost One Hunter|
|869|Protector Dorana|
|870|Protector Deni|
|873|Saltscale Oracle|
|874|Protector Korelor|
|875|Saltscale Tide Lord|
|876|Protector Leick|
|941|Kurzen Headshrinker|
|979|Kurzen Shadow Hunter|
|1060|Mogh the Undying|
|1276|Mountaineer Brokk|
|1277|Mountaineer Ganin|
|1278|Mountaineer Stenn|
|1279|Mountaineer Flint|
|1280|Mountaineer Droken|
|1281|Mountaineer Zaren|
|1282|Mountaineer Veek|
|1283|Mountaineer Kalmir|
|1329|Mountaineer Naarh|
|1331|Mountaineer Luxst|
|1332|Mountaineer Morran|
|1336|Mountaineer Zwarn|
|1337|Mountaineer Gwarth|
|1338|Mountaineer Dalk|
|1449|Witch Doctor Unbagwa|
|1507|Scarlet Initiate|
|1564|Bloodsail Warlock|
|1642|Northshire Guard|
|1652|Deathguard Burgess|
|1653|Bloodsail Elder Magus|
|1735|Deathguard Abraham|
|1736|Deathguard Randolph|
|1737|Deathguard Oliver|
|1738|Deathguard Terrence|
|1739|Deathguard Phillip|
|1741|Deathguard Bartrand|
|1742|Deathguard Bartholomew|
|1743|Deathguard Lawrence|
|1745|Deathguard Morris|
|1746|Deathguard Cyrus|
|1848|Lord Maldazzar|
|2105|Mountaineer Dokkin|
|2120|Archmage Ataeric|
|2151|Moon Priestess Amara|
|2184|Lady Moongazer|
|2206|Greymist Hunter|
|2506|Mountaineer Harn|
|2507|Mountaineer Uthan|
|2508|Mountaineer Wuar|
|2509|Mountaineer Cragg|
|2510|Mountaineer Ozmok|
|2511|Mountaineer Bludd|
|2512|Mountaineer Roghan|
|2513|Mountaineer Janha|
|2514|Mountaineer Modax|
|2515|Mountaineer Fazgard|
|2516|Mountaineer Kamdar|
|2517|Mountaineer Langarr|
|2518|Mountaineer Swarth|
|2639|Vilebranch Axe Thrower|
|2641|Vilebranch Headhunter|
|2645|Vilebranch Shadow Hunter|
|2951|Palemane Poacher|
|3210|Brave Proudsnout|
|3211|Brave Lightninghorn|
|3212|Brave Ironhorn|
|3213|Brave Running Wolf|
|3214|Brave Greathoof|
|3217|Brave Dawneagle|
|3219|Brave Leaping Deer|
|3220|Brave Darksky|
|3221|Brave Rockhorn|
|3222|Brave Wildrunner|
|3223|Brave Rainchaser|
|3265|Razormane Hunter|
|3282|Venture Co. Mercenary|
|3297|Sen'jin Watcher|
|3377|Bael'dun Rifleman|
|3382|Southsea Cannoneer|
|3394|Barak Kodobane|
|3501|Horde Guard|
|3691|Raene Wolfrunner|
|3696|Ran Bloodtooth|
|3745|Foulweald Pathfinder|
|3763|Felmusk Shadowstalker|
|3845|Shindrell Swiftfire|
|3926|Thistlefur Pathfinder|
|4053|Daughter of Cenarius|
|4061|Mirkfallon Dryad|
|4070|Venture Co. Builder|
|4281|Scarlet Scout|
|4359|Mirefin Murloc|
|4459|Murkgill Oracle|
|4638|Magram Scout|
|4654|Maraudine Scout|
|4673|Hatefury Betrayer|
|4716|Slitherblade Tidehunter|
|4831|Lady Sarevess|
|5251|Woodpaw Trapper|
|5336|Hatecrest Sorceress|
|5337|Hatecrest Siren|
|5643|Tyranis Malem|
|5725|Deathguard Lundmark|
|5838|Brokespear|
|5847|Heggin Stonewhisker|
|5952|Den Grunt|
|5996|Nethergarde Miner|
|6087|Astranaar Sentinel|
|6117|Highborne Lichling|
|6129|Draconic Magelord|
|6131|Draconic Mageweaver|
|6172|Henze Faulk|
|6177|Narm Faulk|
|6188|Timbermaw Shaman|
|6199|Blood Elf Reclaimer|
|6224|Leprous Machinesmith|
|6647|Magister Hawkhelm|
|6649|Lady Sesspira|
|6906|Baelog|
|7016|Lady Vespira|
|7047|Black Broodling|
|7048|Scalding Broodling|
|7049|Flamescale Broodling|
|7111|Jadefire Hellcaller|
|7155|Deadwood Pathfinder|
|7442|Winterfall Pathfinder|
|7461|Hederine Initiate|
|7730|Stonetalon Grunt|
|7856|Southsea Freebooter|
|7865|Wildhammer Sentry|
|7956|Kindal Moonweaver|
|7980|Deathguard Elite|
|8015|Ashenvale Sentinel|
|8147|Camp Mojache Brave|
|8151|Nijel's Point Guard|
|8154|Ghost Walker Brave|
|8214|Jalinde Summerdrake|
|8283|Slave Master Blackheart|
|8386|Horizon Scout Crewman|
|8409|Caravan Master Tset|
|8444|Trade Master Kovic|
|8566|Dark Iron Lookout|
|8578|Magus Rimtori|
|8636|Morta'gya the Keeper|
|8763|Mistwing Rogue|
|8901|Anvilrage Reservist|
|8928|Burrowing Thundersnout|
|9044|Scarshield Sentry|
|9817|Blackhand Dreadweaver|
|10082|Zerillis|
|10157|Moonkin Oracle|
|10290|Captured Felwood Ooze|
|10540|Vol'jin|
|10558|Hearthsinger Forresten|
|10608|Scarlet Priest|
|10660|Cobalt Broodling|
|10802|Hitah'ya the Keeper|
|11054|Risen Rifleman|
|11076|Cauldron Lord Razarch|
|11077|Cauldron Lord Malvinious|
|11492|Alzzin the Wildshaper|
|11560|Magrami Spectre|
|11613|Huntsman Radley|
|11680|Horde Scout|
|11686|Ghostly Raider|
|11794|Sister of Celebras|
|11822|Moonglade Warden|
|12321|Stormscale Toxicologist|
|12338|Shadowprey Guardian|
|12856|Ashenvale Outrunner|
|12864|Warsong Outrider|
|12865|Ambassador Malcin|
|12896|Silverwing Sentinel|
|12903|Splintertree Guard|
|12996|Mounted Ironforge Mountaineer|
|13016|Deeprun Rat|
|13076|Dun Morogh Mountaineer|
|13839|Royal Dreadguard|
|14522|Ur'dan|
|14523|Ulathek|
|14622|Thorium Brotherhood Lookout|
|14715|Silverwing Elite|
|14717|Horde Elite|
|14730|Revantusk Watcher|
|14733|Sentinel Farsong|
|14753|Illiyana Moonblaze|
|14859|Guard Taruc|
|14893|Guard Kurall|
|15088|Booty Bay Elite|
|15617|Orgrimmar Legion Axe Thrower|
|15634|Priestess of the Moon|
|15641|Amani Axe Thrower|
|15938|Eversong Ranger|
|15961|Lunar Festival Sentinel|
|16096|Steamwheedle Bruiser|
|16097|Isalien|
|16332|Darnassian Huntress|
|16344|Shadowpine Headhunter|
|16403|Withered Grimscale|
|16574|Far Seer Regulkut|
|16579|Falcon Watch Sentinel|
|16582|Thrallmar Marksman|
|16769|Firewing Warlock|
|16799|Ikan|
|16801|Halduron Brightwing|
|16810|Bonechewer Backbreaker|
|16833|Makuru|
|16836|Escaped Dreghood|
|16844|Crust Burster|
|16857|Marauding Crust Burster|
|16905|Unyielding Sorcerer|
|16912|Mag'har Hunter|
|16966|Haal'eshi Windwalker|
|16977|Arch Mage Xintor|
|16994|Draenei Anchorite|
|17150|Vir'aani Arcanist|
|17192|Siltfin Hunter|
|17270|Bleeding Hollow Archer|
|17282|Falcon Watch Ranger|
|17439|Stillpine Hunter|
|17468|Prophet Velen|
|17609|Sunhawk Saboteur|
|17612|Quel'dorei Magewraith|
|17729|Murkblood Spearman|
|17815|Lordaeron Sentry|
|17820|Durnholde Rifleman|
|17870|Angered Nether-wraith|
|18044|Rajis Fyashe|
|18079|Umbrafen Seer|
|18087|Darkcrest Siren|
|18094|Tarren Mill Lookout|
|18114|Feralfen Mystic|
|18118|Ango'rosh Shaman|
|18121|Ango'rosh Souleater|
|18256|Alliance Halaani Guard|
|18450|Shienor Sorcerer|
|18457|Tuurem Hunter|
|18501|Unliving Stalker|
|18539|Ashkaz|
|18541|Urdak|
|18559|Phasing Stalker|
|18583|Lisaile Fireweaver|
|18658|Kil'sorrow Ritualist|
|18670|Ironjaw|
|18678|Fulgorge|
|18681|Coilfang Emissary|
|18686|Doomsayer Jurim|
|18693|Speaker Mar'grom|
|18697|Chief Engineer Lorthander|
|18855|Sunfury Magister|
|18965|Darnassian Archer|
|19000|High Elf Ranger|
|19136|Flamewaker Imp|
|19411|Shattered Hand Warlock|
|19413|Shattered Hand Mage|
|19422|Bleeding Hollow Necrolyte|
|19504|Scryer Guardian|
|19544|Conjurer Luminrath|
|19545|Cohlien Frostweaver|
|19657|Summoner Kanthin|
|19701|Bonechewer Evoker|
|19705|Master Daellis Dawnstrike|
|19707|Sunfury Archer|
|19732|Ango'rosh Warlock|
|19767|Coilskar Sorceress|
|19768|Coilskar Siren|
|19789|Coilskar Waterkeeper|
|19826|Dark Conclave Shadowmancer|
|19881|Severed Spirit|
|19947|Darkcrest Sorceress|
|20089|Bloodscale Wavecaller|
|20113|Lashh'an Matriarch|
|20135|Sunfury Arch Mage|
|20139|Sunfury Conjurer|
|20159|Magister Aledis|
|20161|Vekh'nir Matriarch|
|20207|Sunfury Bowman|
|20211|Ruuan'ok Matriarch|
|20248|Sunfury Nethermancer|
|20329|Grishna Matriarch|
|20444|Ango'rosh Shadowmage|
|20456|Ethereum Researcher|
|20516|Warp Monstrosity|
|20731|Droggam|
|20732|Gorr'Dim|
|20757|Fingrom|
|20795|Keeper of the Cistern|
|20859|Arcatraz Warder|
|20872|Deathforge Summoner|
|20887|Deathforge Imp|
|20901|Sargeron Archer|
|21021|Scorch Imp|
|21065|Tormented Citizen|
|21135|Fel Imp|
|21200|Screeching Spirit|
|21207|Summoner Skartax|
|21242|Auchenai Death-Speaker|
|21287|Warbringer Razuun|
|21300|Fel Corrupter|
|21370|Ethereal Nethermancer|
|21380|Greater Crust Burster|
|21383|Wyrmcult Acolyte|
|21385|Dark Conclave Scorncrow|
|21427|Strider Jock|
|21428|Corrupted Water Elemental|
|21492|Wyrmcult Blessed|
|21503|Sunfury Warlock|
|21505|Sunfury Summoner|
|21706|Corrupted Fire Elemental|
|21707|Corrupted Air Elemental|
|21718|Dragonmaw Subjugator|
|21811|Wyrmcult Broodling|
|21849|Bone Crawler|
|21911|Skettis Soulcaller|
|21925|Avatar of Sathal|
|21979|Val'zareq the Conqueror|
|22038|Hai'shulud|
|22081|Shadowmoon Darkweaver|
|22102|Shadowmoon Retainer|
|22273|Fel Warden|
|22274|Dragonmaw Skybreaker|
|22298|Vile Fire-Soul|
|22308|Wyrmcult Hunter|
|22309|Crashing Wave-Spirit|
|22310|Storming Wind-Ripper|
|22362|Deathshadow Imp|
|22363|Deathshadow Warlock|
|22393|Deathshadow Overlord|
|22408|Furious Nether-wraith|
|22466|Bone Sifter|
|22482|Mature Bone Sifter|
|22847|Ashtongue Primalist|
|22859|Shadowhoof Summoner|
|22862|Anchorite Caalen|
|22912|Sundered Spirit|
|22993|Guardian of the Eagle|
|23022|Gordunni Soulreaper|
|23078|Fel Imp Defender|
|23162|Vakkiz the Windrager|
|23188|Dragonmaw Transporter|
|23285|Nethermine Burster|
|23636|Mudsprocket Bruiser|
|23652|Dragonflayer Vrykul|
|23653|Winterskorn Spearman|
|23739|Valgarde Defender|
|23760|Forsaken Plaguebringer|
|23779|Vengeance Landing Deathguard|
|23842|Westguard Defender|
|23844|Westguard Officer|
|23883|Forsaken Crossbowman|
|23932|Yanis the Mystic|
|23946|North Fleet Marksman|
|23949|Lieutenant Nath|
|23951|Lieutenant Aden|
|23983|North Fleet Marine|
|24031|Camp Winterhoof Brave|
|24039|Sundered Ghost|
|24050|Wildervar Sentry|
|24051|Dragonflayer Invader|
|24071|Dragonflayer Heartsplitter|
|24151|Daegarn|
|24195|Winterhoof Longrunner|
|24197|Westguard Rifleman|
|24253|Dragonflayer Prisoner|
|24254|Dragonflayer Prisoner|
|24255|Dragonflayer Prisoner|
|24317|Expedition Deathguard|
|24398|Steel Gate Excavator|
|24440|Gjalerbron Gargoyle|
|24460|Chillmere Tidehunter|
|24491|Deathguard Florence|
|24635|Dragonflayer Harpooner|
|24644|Harpoon Master Yavus|
|24683|Sunblade Mage Guard|
|24696|Coilskar Witch|
|24738|Elenna Edune|
|24779|Dragonflayer Ambusher|
|24841|Marine Halters|
|24842|Marine Anderson|
|24911|Cursed Sea Dog|
|24938|Shattered Sun Marksman|
|24979|Dawnblade Marksman|
|25242|Warsong Battleguard|
|25243|Warsong Honor Guard|
|25244|Warsong Marksman|
|25311|Valiance Keep Rifleman|
|25439|Warsong Scout|
|25522|Skadir Raider|
|25601|Prince Valanar|
|25764|Kaskala Defender|
|25791|Oil-stained Wolf|
|25800|Clam Master K|
|25801|Nedar, Lord of Rhinos|
|26157|Taunka'le Brave|
|26198|Snowfall Glade Wolvar|
|26250|Scourged Burrower|
|26295|Magnataur Patriarch|
|26356|Redfang Hunter|
|26389|Solstice Hunter|
|26434|Frostpaw Trapper|
|26448|Stars' Rest Sentinel|
|26601|Fizzcrank Airman|
|26663|Winterskorn Hunter|
|26679|Silverbrook Trapper|
|26780|7th Legion Cleric|
|26827|Howling Wolvar Lookout|
|26839|Conquest Hold Legionnaire|
|27035|Venomspite Deathguard|
|27073|Bor'gorok Battleguard|
|27117|Amberpine Scout|
|27126|Camp Oneqwah Brave|
|27160|7th Legion Infantryman|
|27178|Moa'ki Warrior|
|27351|Argent Crusade Rifleman|
|27377|Thane Torvald Eriksson|
|27540|Fordragon Marksman|
|27546|Silverbrook Hunter|
|27560|Darkspear Spear Thrower|
|27576|Fordragon Sentinel|
|27588|7th Legion Elite|
|27615|Scourge Deathspeaker|
|27633|Azure Inquisitor|
|27749|Horde Conscript|
|27791|7th Legion Rifleman|
|27953|Wyrmrest Protector|
|28005|Wastes Scavenger|
|28034|Drakkari Snake Handler|
|28079|Frenzyheart Hunter|
|28081|Frenzyheart Scavenger|
|28083|Serfex the Reaver|
|28118|Watery Lord|
|28132|Don Carlos|
|28246|Sky Terror|
|28254|Mistwhisper Lightning Target|
|28342|Trapdoor Ambusher|
|28388|Jin'Alai Warrior|
|28451|Hemet Nesingwary|
|28529|Scarlet Crusader|
|28530|Scarlet Commander|
|28575|Rhunok's Tormentor|
|28579|Hardened Steel Berserker|
|28580|Hardened Steel Skycaller|
|28594|Scarlet Preacher|
|28608|Scarlet Medic|
|28611|Scarlet Captain|
|28801|Argent Stand Defender|
|28856|Scarlet Fleet Guardian|
|28936|Scarlet Commander|
|28965|Titanium Thunderer|
|29080|Scarlet Champion|
|29231|Shadow Construct|
|29404|Savage Hill Scavenger|
|29439|Rageclaw Hunter|
|29519|Unworthy Initiate|
|29520|Unworthy Initiate|
|29565|Unworthy Initiate|
|29566|Unworthy Initiate|
|29567|Unworthy Initiate|
|29617|Valiance Keep Defender|
|29621|Grand Admiral Westwind|
|29652|Stormforged Tracker|
|29699|Drakuru Raptor Rider|
|29820|Drakkari God Hunter|
|29836|Drakkari Battle Rider|
|29910|K3 Bruiser|
|29973|Tunka'lo Brave|
|30233|Sunreaver Scout|
|30238|Silver Covenant Scout|
|30241|Lanudal Silverhart|
|30256|Scout Ordimbral|
|30263|Silver Covenant Horseman|
|30265|Sunreaver Hawkrider|
|30299|Overseer Narvir|
|30737|Nesingwary Game Warden|
|30860|Unbound Dryad|
|30864|Shandaral Hunter Spirit|
|30952|Hungering Plaguehound|
|31414|Valiance Commando|
|31715|Deathguard Hicks|
|31726|Grunt Gritch|
|31727|Grunt Grikee|
|31737|Skybreaker Squad Leader|
|31746|Ymirheim Defender|
|31808|Ground Commander Koup|
|31832|Kor'kron Infantry|
|31833|Kor'kron Squad Leader|
|32358|Fumblub Gearwind|
|32375|Warmage Yurias|
|32438|Syreian the Bonecarver|
|32869|Sheya Stormweaver|
|33071|Shatterspear Raider|
|33207|Lady Janira|
|33262|Greymist Tidehunter|
|34052|Splintertree Guard|
|34204|Protector Arminon|
|34208|Protector Endolar|
|34241|Warsong Guardian|
|34242|Guardian Gurtar|
|34309|Shatterspear Raider|
|34326|Doomspeaker Trevellion|
|34339|Greymist Refugee|
|34346|Dave's Industrial Light and Magic Bunny|
|34406|Foreman Balsoth|
|34419|Astranaar Skirmisher|
|34420|Astranaar Officer|
|34504|Grol'dom Grunt|
|34590|Goblin Technician|
|34591|Chief Bombgineer Sploder|
|34603|Ashenvale Assassin|
|34706|Theramore Sharpshooter|
|34907|Kvaldir Harpooner|
|34946|Merchant Kendra|
|34969|Corrupted Sentinel|
|35090|Captain Aerthas Firehawk|
|35098|Wavecrest Mariner|
|35103|Unleashed Magic|
|35149|Talrendis Sniper|
|35333|Goblin Technician|
|35880|Lady Silisthra|
|35884|Lady Silisthra|
|36015|Blackmaw Pathfinder|
|36057|Northgate Rebel|
|36144|Kolkar Centaur|
|36211|Duskhaven Watchman|
|36312|Dark Ranger Thyala|
|36599|Arcane Construct|
|36624|Caladis Brightspear|
|36636|Twilight Dragon Hunter|
|36642|Myralion Sunblaze|
|36654|Dave's Big Giant Industrial Light and Magic Bunny|
|36660|Talrendis Marksman|
|36708|Bristleback Gun Thief|
|36752|Private Worcester|
|36815|Valormok Grunt|
|36914|Talrendis Sentinel|
|36925|Bilgewater Soldier|
|36975|Volt|
|36976|Ticker|
|36989|Spitelash Invader|
|37144|Skybreaker Marksman|
|37146|Kor'kron Sniper|
|37177|Coldridge Defender|
|37180|Honor's Stand Guard|
|37204|Hunter Hill Brave|
|37220|Una'fe Watcher|
|37583|Dark Ranger Kalira|
|37779|Dark Ranger Loralen|
|37925|Sapper Specialist|
|37984|Crown Duster|
|38006|Crown Hoodlum|
|38022|Veteran Dark Ranger|
|38070|Desolation Guard|
|38210|Forsaken Crossbowman|
|38259|Bael'dun Explosion View Vehicle|
|38290|Barrens Brave|
|38385|Walpole's Bodyguard|
|38636|Northwatch Guard|
|38875|Ol' Durty Pete|
|38899|Deathguard Balteus|
|39136|Triumph Sentry|
|39156|Twinbraid's Bodyguard|
|39196|Deathguard Swallon|
|39254|Stardust Sentinel|
|39280|Frazzlecraz Miner|
|39951|Summit Defender|
|40063|Galak Wrangler|
|40069|Horde Poacher|
|40360|Feathermoon Archer|
|40736|Erunak Stonespeaker|
|40746|Erunak Stonespeaker|
|40832|Daisy|
|41015|Northgate Rebel|
|41039|Windshear Hold Guardian|
|41138|Okril'lon Defender|
|41182|Kharanos Rifleman|
|41230|Krom'gar Rifleman|
|41284|Battok the Berserker|
|41292|Loramus the Defiled|
|41306|Galak Wrangler|
|41408|Goblin Stripminer|
|41423|Bloodwash Acolyte|
|41432|Mirkfallon Post Scout|
|41544|Frostmane Raider|
|41627|Farwatcher Guardian|
|41673|Krom'gar Enforcer|
|41864|Huntress Davinia|
|41865|Darnassian Scout|
|41870|Krom'gar Enforcer|
|42040|Cliffwalker Brave|
|42125|Krom'gar Enforcer|
|43322|Zanzil the Outcast|
|43325|Rockjaw Fungus-Flinger|
|43440|Lor'danel Sentinel|
|43653|Hellscream Grunt|
|43715|Hiri'watha Deathguard|
|44161|Mosshide Scout|
|44323|Darkmaster Gandling|
|44492|Enthralled Val'kyr|
|44612|Wastewander Tracker|
|44632|Dark Ranger|
|44637|Dark Ranger Velonara|
|44914|Orc Sea Pup|
|44935|Mutant Bush Chicken|
|45099|Magmatooth|
|46038|Worgen Commando|
|46041|Colossus of the Sun|
|46042|Colossus of the Moon|
|46144|Twilight Pillager|
|46250|Riverpaw Poacher|
|46377|Cliff Thundermar|
|46476|Tracker Yoro|
|46478|Highvale Sentry|
|46526|Twilight Shadeprowler|
|46715|Wibson Mainframe|
|46839|Servias Windterror|
|46947|Cadaver Collage|
|46948|Lord Geoffery Tulvan|
|47003|Bolgaff|
|47130|Crazed Guard|
|47214|Dreadguard|
|47229|Mullan Gryphon Rider|
|47313|Firebeard Gryphon Rider|
|47479|Twilight Trapper|
|47510|Twilight Skymaster Richtofen|
|47528|Aerie Ace|
|48022|Salhet|
|48032|Seedling Protector|
|48042|Sapling Protector|
|48556|Talonbranch Guardian|
|49004|Volt|
|49124|Highbank Marksman|
|50427|Moore Gryphon Rider|
|51323|Tirisfal Deathguard|
|51522|Bulwark Dreadguard|
|51542|Surwich Warden|
|51791|Okril'lon Defender|
|51824|Hiri'watha Deathguard|
|51848|Thelsamar Mountaineer|
|51850|Deathguard Elite|
|51888|New Agamand Deathguard|
|51901|Revantusk Watcher|
|51912|Dun Morogh Mountaineer|
|51915|Westfall Brigade Guard|
|51923|Wildhammer Sentry|
|52084|Wildhammer Sentry|
|54590|Arcurion|
|54938|Archbishop Benedictus|
|54968|Asira Dawnslayer|
