### ISSUE TITLE
Emperor Dagran Thaurissan HUGE issue

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#983]
Not only does he still not pull the entire room when you attack him as he screams "Come to aid the Throne" when you initiate combat with him.
He is now completely static, he just stands still while you kill him and does nothing. Very upsetting issue to see after all the BRD bug reports, looks like I have to retest all dungeons again.

https://user-images.githubusercontent.com/66841484/196824097-fb52ea42-ff59-409d-82d0-e81d446a5df0.mp4

**Comment by WarlordXecc** [comment]
Found another mob that's just staring at you as you fight it.
Not sure if this is related to the same issue with Emperor or if it is due to him being a caster mob and missing his ability.

https://user-images.githubusercontent.com/66841484/196870038-b805e5e7-be70-46b2-a5a1-0d1fdbe4cf9f.mp4

**Comment by WarlordXecc** [comment]
I checked this bug on Maelstrom PTR and on there he worked fine. He both pulled the room to assist him and didn't stand still being static.
Maelstrom PTR has not been updated for over two months tho, so something during this time has broken various things.

![WoWScrnShot_102022_084856](https://user-images.githubusercontent.com/66841484/196877456-2f5ef549-9628-4806-b800-07a4a65b3cb3.jpg)


https://user-images.githubusercontent.com/66841484/196877800-7eb5d22d-948b-4d8e-8465-013cf93cd936.mp4

**Comment by Afgann** [comment]
fixed
