### ISSUE TITLE
Caster Mob Behavior

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#984]
Caster mobs will not move during downtime between spells. So if they have some spells that has a cooldown or something they will just stare at you. 
I reported this a long time ago, back then they would also just stand still if you interrupted their cast which works fine now, but they won't move for any other reason than getting interrupted.
They also seem to take quite a long time before they start casting as you initiate combat.

https://user-images.githubusercontent.com/66841484/196824757-9c076f46-d258-4ead-9143-4337a3ec94da.mp4

https://user-images.githubusercontent.com/66841484/196824886-8aa50b1b-4f47-45af-87be-7ec4af296d60.mp4

**Comment by UltraNix** [comment]
As previous - bad AI. Not fixable by generic solution.

**Comment by UltraNix** [comment]
No. As I said - it's bad AI scripts.

**Comment by Afgann** [comment]
fixed (see https://github.com/GameFreedomGG/Maelstrom/issues/982 for explanation)
