### ISSUE TITLE
Craggle Wobbletop Cart

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#987]
This guy should be pushing around this toy cart, I think he has different animation while doing it also kind of like the goblin toy seller in Orgrimmar.

https://user-images.githubusercontent.com/66841484/197586932-8d8e6f1e-c849-4ac9-bee3-636c9f3716e4.mp4

**Comment by UltraNix** [comment]
https://imgur.com/a/VOp9ZDI on my local - works okay. Need to load the new world database.
