### ISSUE TITLE
Rockpool Murlock Slaves

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#989]
These Murlocks should be dragging these crates to a location instead of standing still.

You can see an example here in the background : https://youtu.be/SeTGofMAncQ?t=24

https://user-images.githubusercontent.com/66841484/197737905-4bce48e5-ffbe-47aa-9527-b9b33aba6164.mp4

**Comment by UltraNix** [comment]
https://imgur.com/a/VOp9ZDI
My local - works okay. Need to load the new world database.
