### ISSUE TITLE
Grunts spawn where they shouldnt

### ISSUE THREAD

**Issue by ElectrickFun** [GameFreedomGG/Maelstrom#99]
**Description:** Grunts spawn too close to a alliance camp https://i.imgur.com/u9kcpZb.jpeg

**How to reproduce:**

**How it should work:** https://www.youtube.com/watch?v=z_FrnpJZ098 it can be seen in the video that no grunts are there. or at least the sentinels should battle them.

**Comment by HerodDev** [comment]
TODO: rescript whole area
