### ISSUE TITLE
Rockpool Gladiators

### ISSUE THREAD

**Issue by WarlordXecc** [GameFreedomGG/Maelstrom#990]
The Rockpool Gladiators inside the two pools should be fighting each other.
There should also be more Gamblers standing around the pools, example here : https://youtu.be/Ox7wC-wSJ3I?t=276

https://user-images.githubusercontent.com/66841484/197738971-9b5b0a79-248f-4553-a2dd-c60bea7bee73.mp4

**Comment by UltraNix** [comment]
As #989 - need new world database.
